ALTER TABLE EXERCISE_PLANE 
ADD (CIRCLE NUMBER DEFAULT 0 );

CREATE TABLE EXERCISE_CIRCLE_TYPE 
(
  ID NUMBER NOT NULL 
, NAME VARCHAR2(20) NOT NULL 
, CONSTRAINT EXERCISE_CIRCLE_TYPE_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

REM INSERTING into EXERCISE_CIRCLE_TYPE
Insert into EXERCISE_CIRCLE_TYPE (ID,NAME) values (0,'No');
Insert into EXERCISE_CIRCLE_TYPE (ID,NAME) values (1,'Yes');
commit;

ALTER TABLE EXERCISE_PLANE  
MODIFY (CIRCLE NOT NULL);

ALTER TABLE EXERCISE_PLANE
ADD CONSTRAINT EXERCISE_PLANE_EXERCISE_C_FK1 FOREIGN KEY
(
  CIRCLE 
)
REFERENCES EXERCISE_CIRCLE_TYPE
(
  ID 
)
ENABLE;
