--------------------------------------------------------
--  DDL for Table INPUTTELEGRAMS
--------------------------------------------------------

  CREATE TABLE "INPUTTELEGRAMS" 
   (	"ID" NUMBER, 
	"CREATED" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), 
	"TYPE" VARCHAR2(20 CHAR), 
	"SENDER" VARCHAR2(10 CHAR), 
	"MESSAGE" VARCHAR2(4000 CHAR),
	"TELEGRAM_NUMBER" NUMBER 
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
  
  --------------------------------------------------------
--  DDL for Sequence INPUTTELEGRAMS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "INPUTTELEGRAMS_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

--------------------------------------------------------
--  DDL for Index INPUTTELEGRAMS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "INPUTTELEGRAMS_PK" ON "INPUTTELEGRAMS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table INPUTTELEGRAMS
--------------------------------------------------------

  ALTER TABLE "INPUTTELEGRAMS" ADD CONSTRAINT "INPUTTELEGRAMS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "INPUTTELEGRAMS" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "INPUTTELEGRAMS" MODIFY ("CREATED" NOT NULL ENABLE);
--------------------------------------------------------
--  DDL for Trigger INPUTTELEGRAMS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "INPUTTELEGRAMS_TRG" BEFORE INSERT ON INPUTTELEGRAMS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF :NEW.ID IS NULL THEN
      SELECT INPUTTELEGRAMS_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "INPUTTELEGRAMS_TRG" ENABLE;
