-- Generated by Ora2Pg, the Oracle database Schema converter, version 13.0
-- Copyright 2000-2014 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.20.1.81;sid=XE

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON

CREATE SCHEMA aero;

SET search_path = aero, pg_catalog;
CREATE TABLE holding_type (
	id bigint NOT NULL,
	name varchar(100) NOT NULL
);
COMMENT ON TABLE holding_type IS E'Provide convertion from numberic type of holding zone to textual';
COMMENT ON COLUMN holding_type.ID IS E'Primary key';
COMMENT ON COLUMN holding_type.NAME IS E'Textual description';

CREATE TABLE oldi_fpl (
	aircraft_id varchar(7) NOT NULL,
	adep varchar(4) NOT NULL,
	ades varchar(4) NOT NULL,
	reciever varchar(100) NOT NULL
);
COMMENT ON COLUMN oldi_fpl.ADES IS E'Destination aerodrome';
COMMENT ON COLUMN oldi_fpl.AIRCRAFT_ID IS E'Aircraft identificator';
COMMENT ON COLUMN oldi_fpl.ADEP IS E'Departure aerodrome';

CREATE TABLE settings (
	key varchar(64) NOT NULL,
	value bytea
);

CREATE TABLE restriction (
	id bigint NOT NULL,
	name varchar(30),
	type bigint NOT NULL,
	designation varchar(10) NOT NULL,
	zone_id bigint NOT NULL,
	multi_code varchar(1),
	h_min bigint,
	h_max bigint,
	schedule_mode bigint
);
COMMENT ON TABLE restriction IS E'Zones of restriction';
COMMENT ON COLUMN restriction.ID IS E'Primary key';
COMMENT ON COLUMN restriction.NAME IS E'Name of restriction zone';
COMMENT ON COLUMN restriction.H_MAX IS E'Top border of restriction zone';
COMMENT ON COLUMN restriction.TYPE IS E'Type of restriction zone';
COMMENT ON COLUMN restriction.H_MIN IS E'Bottom border of restriction zone';
COMMENT ON COLUMN restriction.ZONE_ID IS E'FIR id which restriction zone is belonged';

CREATE TABLE border_terms (
	name varchar(1) NOT NULL
);

CREATE TABLE airplane_type (
	name varchar(4) NOT NULL,
	level_max double precision NOT NULL DEFAULT 6.0,
	bank_max integer NOT NULL DEFAULT 1,
	bank_default integer NOT NULL DEFAULT 2
);

CREATE TABLE arc_aftn (
	id bigint NOT NULL,
	created timestamp NOT NULL DEFAULT (now() AT TIME ZONE 'UTC'),
	text varchar(4000) NOT NULL,
	header varchar(4000)
);
COMMENT ON TABLE arc_aftn IS E'Archive of aftn messages';
COMMENT ON COLUMN arc_aftn.ID IS E'identifier';
COMMENT ON COLUMN arc_aftn.TEXT IS E'AFTN message text';
COMMENT ON COLUMN arc_aftn.CREATED IS E'UTC timestamp of inserting message';
COMMENT ON COLUMN arc_aftn.HEADER IS E'AFTN message header';

CREATE TABLE wind (
	zone_id bigint NOT NULL,
	flevel_start double precision NOT NULL,
	flevel_end double precision NOT NULL,
	speed double precision NOT NULL,
	azimuth double precision,
	id bigint NOT NULL
);

CREATE TABLE commands (
	commandid bigint NOT NULL,
	commandtime timestamp NOT NULL,
	commandexecutor varchar(25) NOT NULL,
	commandcode smallint NOT NULL
);

CREATE TABLE zone_map_note (
	id bigint NOT NULL,
	zone_id bigint NOT NULL,
	latitude double precision DEFAULT 0,
	longitude double precision DEFAULT 0,
	description varchar(2000)
);

CREATE TABLE squawk (
	id bigint NOT NULL,
	squawk bigint NOT NULL,
	zone_id bigint NOT NULL
);

CREATE TABLE inputmessages (
	msgid bigint NOT NULL,
	msgtime timestamp NOT NULL,
	msgfrom varchar(50) NOT NULL,
	msgto varchar(50) NOT NULL,
	msgtext text NOT NULL,
	msgtype varchar(20) NOT NULL
);

CREATE TABLE arinc_changes (
	id bigint NOT NULL,
	statement varchar(4000) NOT NULL,
	time timestamp NOT NULL DEFAULT now()
);

CREATE TABLE ssa_type (
	id bigint NOT NULL,
	name varchar(40) NOT NULL
);
COMMENT ON TABLE ssa_type IS E'Provide convertion from numberic type of ssa to textual reprisentation';
COMMENT ON COLUMN ssa_type.ID IS E'Primaty key';
COMMENT ON COLUMN ssa_type.NAME IS E'Textual description';

CREATE TABLE fpl_status_types (
	name varchar(1) NOT NULL
);

CREATE TABLE client (
	id bigint NOT NULL,
	name varchar(128) NOT NULL,
	password bytea,
	role_id bigint,
	full_name varchar(2000)
);

CREATE TABLE sfpl_master_table (
	id bigint NOT NULL,
	fir_name varchar(4),
	aircraft_id varchar(7),
	taircraft varchar(4),
	frules varchar(1),
	tflight varchar(1),
	num smallint,
	wtc varchar(1),
	equipment varchar(222),
	adep varchar(4),
	time timestamp DEFAULT (now() AT TIME ZONE 'UTC'),
	speed varchar(5),
	flevel varchar(5),
	route varchar(4000),
	ades varchar(4),
	eet varchar(5),
	alt1 varchar(4),
	alt2 varchar(4),
	other varchar(4000),
	trtime timestamp DEFAULT (now() AT TIME ZONE 'UTC'),
	exfpl char(1),
	entry_fir_eet varchar(5),
	code bigint,
	sectors varchar(512),
	cs varchar(20),
	ns varchar(20),
	state bigint,
	time_entry timestamp DEFAULT LOCALTIMESTAMP,
	ins varchar(20),
	copin varchar(20),
	copinfl double precision,
	visibility smallint
);

CREATE TABLE client_role (
	id bigint NOT NULL,
	name varchar(128) NOT NULL,
	permission varchar(2000)
);

CREATE TABLE route (
	id bigint NOT NULL,
	name varchar(20) NOT NULL,
	zone_id bigint NOT NULL
);
COMMENT ON TABLE route IS E'Reprisent routed - the set of POINTs';
COMMENT ON COLUMN route.ID IS E'Primary key';
COMMENT ON COLUMN route.NAME IS E'Zone name';
COMMENT ON COLUMN route.ZONE_ID IS E'Pointer to the FIR id which route is belonged';

CREATE TABLE restriction_point_type (
	id bigint NOT NULL,
	name varchar(100) NOT NULL
);
COMMENT ON TABLE restriction_point_type IS E'Provide convertion from numberic type boundary point of restriction zone to textual reprisentation';
COMMENT ON COLUMN restriction_point_type.ID IS E'Primaty key';
COMMENT ON COLUMN restriction_point_type.NAME IS E'Textual description';

CREATE TABLE holding_turn (
	id bigint NOT NULL,
	name varchar(100) NOT NULL
);
COMMENT ON TABLE holding_turn IS E'Provide convertion from numberic type of type of turning inside holding zone to textual';
COMMENT ON COLUMN holding_turn.ID IS E'Primary key';
COMMENT ON COLUMN holding_turn.NAME IS E'Textual description';

CREATE TABLE route_point (
	id bigint NOT NULL,
	sn bigint NOT NULL,
	point_id bigint NOT NULL,
	route_id bigint NOT NULL,
	end_flag smallint NOT NULL DEFAULT '0'
);
COMMENT ON TABLE route_point IS E'The sequence of poince for current route';
COMMENT ON COLUMN route_point.ID IS E'Primary key';
COMMENT ON COLUMN route_point.SN IS E'Sequence number';
COMMENT ON COLUMN route_point.POINT_ID IS E'Reference to POINT.ID';
COMMENT ON COLUMN route_point.ROUTE_ID IS E'Reference to ROUTE.ID';

CREATE TABLE template_chg (
	id bigint NOT NULL,
	name varchar(40) NOT NULL,
	aircraft varchar(7),
	adep varchar(4),
	ades varchar(4),
	other varchar(4000),
	taircraft varchar(4),
	frules varchar(1),
	tflight varchar(1),
	num bigint,
	wtc varchar(1),
	equipment varchar(40),
	chg_adep varchar(4),
	departure_time timestamp,
	speed varchar(5),
	flevel varchar(5),
	route varchar(4000),
	chg_ades varchar(4),
	eet varchar(5),
	alt1 varchar(4),
	alt2 varchar(4),
	chg_other varchar(4000),
	changes_flags bigint,
	receivers varchar(4000)
);

CREATE TABLE fpl_master (
	id bigint NOT NULL,
	fir_name varchar(4) NOT NULL DEFAULT 'UMMV',
	aircraft_id varchar(7) NOT NULL,
	taircraft varchar(4),
	frules varchar(1),
	tflight varchar(1),
	num smallint,
	wtc varchar(1),
	equipment varchar(222),
	adep varchar(4) NOT NULL,
	time timestamp,
	speed varchar(5) NOT NULL,
	flevel varchar(5) NOT NULL,
	route varchar(4000),
	ades varchar(4) NOT NULL,
	eet varchar(5),
	alt1 varchar(4),
	alt2 varchar(4),
	other varchar(4000),
	trtime timestamp NOT NULL DEFAULT (now() AT TIME ZONE 'UTC'),
	exfpl char(1),
	visibility smallint,
	message_id bigint,
	entry_fir_eet varchar(5)
);

CREATE TABLE template_cnl (
	id bigint NOT NULL,
	name varchar(40) NOT NULL,
	aircraft varchar(7),
	adep varchar(4),
	ades varchar(4),
	other varchar(4000),
	receivers varchar(4000)
);

CREATE TABLE t_migration_order (
	id bigint NOT NULL,
	type bigint NOT NULL,
	sn bigint NOT NULL,
	latitude double precision,
	longitude double precision,
	zone_id bigint NOT NULL,
	arc_latitude double precision,
	arc_longitude double precision,
	arc_distance double precision
);

CREATE TABLE exercise (
	id_exercise bigint NOT NULL,
	name varchar(100) NOT NULL
);

CREATE TABLE zone_point (
	id bigint NOT NULL,
	zone_id bigint NOT NULL,
	point_id bigint NOT NULL
);
COMMENT ON TABLE zone_point IS E'Many-to-many lick describing belong POINT to ZONE. Do not foreget recalculate this table afret change in zones or points.';
COMMENT ON COLUMN zone_point.ID IS E'Primary key';
COMMENT ON COLUMN zone_point.ZONE_ID IS E'Foreign key to ZONE.ID';
COMMENT ON COLUMN zone_point.POINT_ID IS E'Foreign key to POINT.ID';

CREATE TABLE equipment (
	name varchar(1) NOT NULL
);

CREATE TABLE meteo_airport_stg (
	airport_id bigint NOT NULL,
	runway_id bigint NOT NULL,
	last_edit timestamp
);
COMMENT ON COLUMN meteo_airport_stg.LAST_EDIT IS E'????? ?????????? ??????????????';
COMMENT ON COLUMN meteo_airport_stg.AIRPORT_ID IS E'????????????? ?????????';
COMMENT ON COLUMN meteo_airport_stg.RUNWAY_ID IS E'????????? ????? ???';

CREATE TABLE msg_from_fdp (
	id bigint,
	fir_name varchar(4) DEFAULT 'UMMV',
	aircraft_id varchar(7),
	taircraft varchar(4),
	frules varchar(1),
	tflight varchar(1),
	num smallint,
	wtc varchar(1),
	equipment varchar(222),
	adep varchar(4),
	time timestamp,
	speed varchar(5),
	flevel varchar(5),
	route varchar(4000),
	ades varchar(4),
	eet varchar(5),
	alt1 varchar(4),
	alt2 varchar(4),
	other varchar(4000),
	trtime timestamp DEFAULT (now() AT TIME ZONE 'UTC'),
	exfpl char(1),
	visibility smallint,
	message_id bigint,
	entry_fir_eet varchar(5),
	oper varchar(7),
	oper_time timestamp,
	message_text varchar(4000),
	status smallint DEFAULT 0,
	pod_in varchar(10),
	t_in timestamp,
	h_in varchar(10),
	pod_out varchar(10),
	t_out timestamp,
	h_out varchar(10),
	fpl_id varchar(40)
);

CREATE TABLE vehicle (
	id bigint NOT NULL,
	name varchar(100) NOT NULL
);

CREATE TABLE received_aftn (
	id bigint NOT NULL,
	created timestamp NOT NULL DEFAULT (now() AT TIME ZONE 'UTC'),
	text varchar(4000),
	header varchar(4000),
	message varchar(4000) DEFAULT NULL,
	processed bigint NOT NULL DEFAULT 0,
	type varchar(10),
	sender varchar(8),
	fill_time varchar(6)
);

CREATE TABLE fpl_cfg (
	sectors varchar(1024) DEFAULT ' ',
	monitor_period bigint DEFAULT 30,
	sfpl_clean_time bigint DEFAULT 300,
	efpl_clean_time bigint DEFAULT 1440,
	pps bigint DEFAULT 0
);

CREATE TABLE template_fpl (
	id bigint NOT NULL,
	name varchar(40) NOT NULL,
	aircraft varchar(7),
	taircraft varchar(4),
	frules varchar(1),
	tflight varchar(1),
	num bigint,
	wtc varchar(1),
	equipment varchar(40),
	adep varchar(4),
	departure_time timestamp,
	speed varchar(5),
	flevel varchar(5),
	route varchar(4000),
	ades varchar(4),
	eet varchar(5),
	alt1 varchar(4),
	alt2 varchar(4),
	other varchar(4000),
	receivers varchar(4000)
);

CREATE TABLE archivecommands (
	commandid bigint NOT NULL,
	commandtime timestamp NOT NULL,
	commandexecutor varchar(25) NOT NULL,
	commandcode smallint NOT NULL,
	executiontime timestamp NOT NULL
);

CREATE TABLE zone (
	id bigint NOT NULL,
	name varchar(45),
	type bigint NOT NULL,
	id_name varchar(10) NOT NULL,
	parent_id bigint DEFAULT NULL,
	low_limit bigint NOT NULL DEFAULT 0,
	up_limit bigint NOT NULL DEFAULT 0,
	short_name varchar(100),
	label_name varchar(100),
	frequency double precision
);
COMMENT ON TABLE zone IS E'???????? ?????? ? ????? ? ????????.
Contains FIRs and sectors. I hope we will separate sectors and firs... one day...';
COMMENT ON COLUMN zone.ID IS E'Primary key';
COMMENT ON COLUMN zone.NAME IS E'The full name of zone.';
COMMENT ON COLUMN zone.LOW_LIMIT IS E'Lowest limit for sectors';
COMMENT ON COLUMN zone.TYPE IS E'Type of zone (FIR/SECTOR/etc). There is descriprion in the ZONE_TYPE table.';
COMMENT ON COLUMN zone.PARENT_ID IS E'Pointer to the zone which include current zone. This is actual for FIR-Sector including. If zone is not included the value is null.';
COMMENT ON COLUMN zone.ID_NAME IS E'The unique textual id of zone. As usual contains 4 capital letters';
COMMENT ON COLUMN zone.UP_LIMIT IS E'Higest limit for sectors';

CREATE TABLE zone_airport (
	id bigint NOT NULL,
	zone_id bigint NOT NULL,
	airport_id bigint NOT NULL
);
COMMENT ON TABLE zone_airport IS E'Provide many-to-many link belonging AIRPORT to ZONE. Do not foregot recalculate this table after changing AIRPORT or ZONE table.';
COMMENT ON COLUMN zone_airport.ID IS E'Primary key';
COMMENT ON COLUMN zone_airport.ZONE_ID IS E'Foreign key to ZONE.ID';
COMMENT ON COLUMN zone_airport.AIRPORT_ID IS E'Foreign key to AIRPORT.ID';

CREATE TABLE sectoring_zone (
	id bigint NOT NULL,
	sect_id bigint NOT NULL,
	zone_id bigint NOT NULL,
	main_fir bigint
);

CREATE TABLE sfpl_table (
	id bigint NOT NULL,
	trtime timestamp DEFAULT LOCALTIMESTAMP,
	aircraft_id varchar(7),
	frules varchar(1),
	tflight varchar(1),
	num bigint,
	taircraft varchar(4),
	wtc varchar(1),
	equipment varchar(222),
	adep varchar(4),
	time timestamp DEFAULT LOCALTIMESTAMP,
	speed varchar(5),
	flevel varchar(5),
	route varchar(4000),
	ades varchar(4),
	eet varchar(5) DEFAULT NULL,
	alt1 varchar(4),
	alt2 varchar(4),
	other varchar(2000),
	code bigint,
	sectors varchar(512),
	cs varchar(20),
	ns varchar(20),
	state bigint,
	time_entry timestamp DEFAULT LOCALTIMESTAMP,
	fir_name varchar(4)
);

CREATE TABLE bearing (
	workstation varchar(100) NOT NULL,
	acid varchar(10) NOT NULL
);

CREATE TABLE boundary_point_type (
	id bigint NOT NULL,
	name varchar(100) NOT NULL
);
COMMENT ON TABLE boundary_point_type IS E'?????? ??????? ???????? ????????? ??????? ???????? ????? ????? ????????? ?????.
This table provides textual descriprion for numberic type of boundary points.';
COMMENT ON COLUMN boundary_point_type.ID IS E'Primary key';
COMMENT ON COLUMN boundary_point_type.NAME IS E'Textual descriprion';

CREATE TABLE rlp (
	id bigint NOT NULL,
	name varchar(128) NOT NULL,
	latitude double precision NOT NULL,
	longitude double precision NOT NULL,
	angle double precision NOT NULL DEFAULT 0,
	radius double precision NOT NULL DEFAULT 300
);
COMMENT ON COLUMN rlp.ANGLE IS E'Angle in degree';

CREATE TABLE hist_outputtelegrams (
	id bigint NOT NULL,
	created timestamp NOT NULL,
	text varchar(4000) NOT NULL,
	header varchar(4000),
	message varchar(4000),
	addresses varchar(4000),
	hist_id bigint NOT NULL,
	modified_by bigint NOT NULL,
	modified_at timestamp NOT NULL DEFAULT (now() AT TIME ZONE 'UTC'),
	modification_type char(1)
);
COMMENT ON TABLE hist_outputtelegrams IS E'History of changes OUTPUTTELEGRAMS table';
COMMENT ON COLUMN hist_outputtelegrams.ID IS E'identifier';
COMMENT ON COLUMN hist_outputtelegrams.ADDRESSES IS E'AFTN addresses';
COMMENT ON COLUMN hist_outputtelegrams.TEXT IS E'AFTN message text';
COMMENT ON COLUMN hist_outputtelegrams.CREATED IS E'UTC timestamp of inserting message';
COMMENT ON COLUMN hist_outputtelegrams.MODIFIED_BY IS E'Who modified';
COMMENT ON COLUMN hist_outputtelegrams.HIST_ID IS E'History record id';
COMMENT ON COLUMN hist_outputtelegrams.MODIFICATION_TYPE IS E'Modified type (i - inserted; u - updated; d - deleted)';
COMMENT ON COLUMN hist_outputtelegrams.MESSAGE IS E'AFTN message';
COMMENT ON COLUMN hist_outputtelegrams.HEADER IS E'AFTN message header';
COMMENT ON COLUMN hist_outputtelegrams.MODIFIED_AT IS E'When modified';

CREATE TABLE vehicle_route_points (
	id bigint NOT NULL,
	latitude double precision NOT NULL,
	longitude double precision NOT NULL,
	route_id bigint NOT NULL,
	sn bigint NOT NULL
);

CREATE TABLE fpl (
	id bigint NOT NULL,
	fir_name varchar(4) NOT NULL DEFAULT 'UMMV',
	aircraft_id varchar(7) NOT NULL,
	taircraft varchar(4),
	frules varchar(1),
	tflight varchar(1),
	num smallint,
	wtc varchar(1),
	equipment varchar(222),
	adep varchar(4) NOT NULL,
	time timestamp,
	speed varchar(5) NOT NULL,
	flevel varchar(5) NOT NULL,
	route varchar(4000),
	ades varchar(4) NOT NULL,
	eet varchar(5),
	alt1 varchar(4),
	alt2 varchar(4),
	other varchar(4000),
	trtime timestamp NOT NULL DEFAULT (now() AT TIME ZONE 'UTC'),
	exfpl char(1),
	visibility smallint,
	message_id bigint,
	entry_fir_eet varchar(5)
);
COMMENT ON TABLE fpl IS E'Today flight planes';
COMMENT ON COLUMN fpl.ID IS E'Identificator';
COMMENT ON COLUMN fpl.ENTRY_FIR_EET IS E'EET on entry in fir';
COMMENT ON COLUMN fpl.ADEP IS E'Departure aerodrome';
COMMENT ON COLUMN fpl.SPEED IS E'Speed of flight';
COMMENT ON COLUMN fpl.NUM IS E'Number of aircrafts';
COMMENT ON COLUMN fpl.VISIBILITY IS E'Visibility of this fpl (customer asked this field)';
COMMENT ON COLUMN fpl.FRULES IS E'Flight rules';
COMMENT ON COLUMN fpl.MESSAGE_ID IS E'Message id in arc_aftn';
COMMENT ON COLUMN fpl.FIR_NAME IS E'Flight region identificator';
COMMENT ON COLUMN fpl.TRTIME IS E'Time of getting this record by aftnservice';
COMMENT ON COLUMN fpl.EQUIPMENT IS E'Equipment on aircraft';
COMMENT ON COLUMN fpl.ADES IS E'Destination aerodrome';
COMMENT ON COLUMN fpl.OTHER IS E'Other information';
COMMENT ON COLUMN fpl.AIRCRAFT_ID IS E'Aircraft identificator';
COMMENT ON COLUMN fpl.TIME IS E'Time of flight start';
COMMENT ON COLUMN fpl.TAIRCRAFT IS E'Aircraft type';
COMMENT ON COLUMN fpl.FLEVEL IS E'Flight level';
COMMENT ON COLUMN fpl.EXFPL IS E'FPL status (c - cancelled, d - delayed, a -arrived, f - departure,)';
COMMENT ON COLUMN fpl.WTC IS E'Turbulence category';
COMMENT ON COLUMN fpl.ALT2 IS E'Another alternative destination aerodrome';
COMMENT ON COLUMN fpl.EET IS E'??? Time of flight end';
COMMENT ON COLUMN fpl.ALT1 IS E'Alternative destination aerodrome';
COMMENT ON COLUMN fpl.TFLIGHT IS E'Flight type';
COMMENT ON COLUMN fpl.ROUTE IS E'Flight route';

CREATE TABLE point (
	id bigint NOT NULL,
	type bigint NOT NULL,
	name varchar(10) NOT NULL,
	latitude double precision NOT NULL,
	longitude double precision NOT NULL,
	icao varchar(5),
	airport varchar(5)
);
COMMENT ON TABLE point IS E'Monument point. It could belong to zone.';
COMMENT ON COLUMN point.ID IS E'Primary key';
COMMENT ON COLUMN point.LONGITUDE IS E'The longitude part of the coordinates';
COMMENT ON COLUMN point.NAME IS E'The short name (as usual less then 7 letters) of the point.';
COMMENT ON COLUMN point.ICAO IS E'The ICAO index';
COMMENT ON COLUMN point.AIRPORT IS E'I pretty dont know what is this =(';
COMMENT ON COLUMN point.LATITUDE IS E'The latitude part of the coordinates';
COMMENT ON COLUMN point.TYPE IS E'Type of the point. For textual description see POINT_TYPE table';

CREATE TABLE runway (
	id bigint NOT NULL,
	name varchar(10) NOT NULL,
	latitude double precision NOT NULL,
	longitude double precision NOT NULL,
	length bigint NOT NULL DEFAULT '0',
	azimuth double precision NOT NULL,
	airport_id bigint NOT NULL,
	width double precision NOT NULL DEFAULT 100,
	widget varchar(100)
);
COMMENT ON TABLE runway IS E'Runway of an airport';
COMMENT ON COLUMN runway.ID IS E'Primary key';
COMMENT ON COLUMN runway.NAME IS E'Name of runway';
COMMENT ON COLUMN runway.LENGTH IS E'Length of the runway';
COMMENT ON COLUMN runway.AIRPORT_ID IS E'Reference to AIRPORT.ID';
COMMENT ON COLUMN runway.LONGITUDE IS E'Longitude coordinate part';
COMMENT ON COLUMN runway.AZIMUTH IS E'Azimuth turning of runway';
COMMENT ON COLUMN runway.LATITUDE IS E'Latitude coordinate part';

CREATE TABLE users (
	id bigint NOT NULL,
	created timestamp NOT NULL DEFAULT (now() AT TIME ZONE 'UTC'),
	user_name varchar(256) NOT NULL,
	password varchar(256),
	isactive bigint,
	lasttouch timestamp DEFAULT (now() AT TIME ZONE 'UTC'),
	fullname varchar(128),
	addressbook bigint DEFAULT 0,
	edittable bigint DEFAULT 0
);
COMMENT ON TABLE users IS E'User list';
COMMENT ON COLUMN users.ID IS E'Identifier. 1 for superuser';
COMMENT ON COLUMN users.PASSWORD IS E'md5(password, salt)';
COMMENT ON COLUMN users.LASTTOUCH IS E'Last touching to this row';
COMMENT ON COLUMN users.CREATED IS E'Timestamp when user created';
COMMENT ON COLUMN users.ISACTIVE IS E'Show whether this user is active';
COMMENT ON COLUMN users.USER_NAME IS E'User name';

CREATE TABLE ffpl (
	id bigint NOT NULL,
	fir_name varchar(4) NOT NULL DEFAULT 'UMMV',
	aircraft_id varchar(7) NOT NULL,
	taircraft varchar(4),
	frules varchar(1),
	tflight varchar(1),
	num smallint,
	wtc varchar(1),
	equipment varchar(222),
	adep varchar(4) NOT NULL,
	time timestamp,
	speed varchar(5) NOT NULL,
	flevel varchar(5) NOT NULL,
	route varchar(4000),
	ades varchar(4) NOT NULL,
	eet varchar(5),
	alt1 varchar(4),
	alt2 varchar(4),
	other varchar(4000),
	trtime timestamp NOT NULL DEFAULT (now() AT TIME ZONE 'UTC'),
	exfpl char(1),
	visibility smallint,
	message_id bigint,
	entry_fir_eet varchar(5)
);
COMMENT ON TABLE ffpl IS E'Today flight planes';
COMMENT ON COLUMN ffpl.ID IS E'Identificator';
COMMENT ON COLUMN ffpl.ENTRY_FIR_EET IS E'EET on entry in fir';
COMMENT ON COLUMN ffpl.ADEP IS E'Departure aerodrome';
COMMENT ON COLUMN ffpl.SPEED IS E'Speed of flight';
COMMENT ON COLUMN ffpl.NUM IS E'Number of aircrafts';
COMMENT ON COLUMN ffpl.VISIBILITY IS E'Visibility of this fpl (customer asked this field)';
COMMENT ON COLUMN ffpl.FRULES IS E'Flight rules';
COMMENT ON COLUMN ffpl.MESSAGE_ID IS E'Message id in arc_aftn';
COMMENT ON COLUMN ffpl.FIR_NAME IS E'Flight region identificator';
COMMENT ON COLUMN ffpl.TRTIME IS E'Time of getting this record by aftnservice';
COMMENT ON COLUMN ffpl.EQUIPMENT IS E'Equipment on aircraft';
COMMENT ON COLUMN ffpl.ADES IS E'Destination aerodrome';
COMMENT ON COLUMN ffpl.OTHER IS E'Other information';
COMMENT ON COLUMN ffpl.AIRCRAFT_ID IS E'Aircraft identificator';
COMMENT ON COLUMN ffpl.TIME IS E'Time of flight start';
COMMENT ON COLUMN ffpl.TAIRCRAFT IS E'Aircraft type';
COMMENT ON COLUMN ffpl.FLEVEL IS E'Flight level';
COMMENT ON COLUMN ffpl.EXFPL IS E'FPL status (c - cancelled, d - delayed, a -arrived, f - departure,)';
COMMENT ON COLUMN ffpl.WTC IS E'Turbulence category';
COMMENT ON COLUMN ffpl.ALT2 IS E'Another alternative destination aerodrome';
COMMENT ON COLUMN ffpl.EET IS E'??? Time of flight end';
COMMENT ON COLUMN ffpl.ALT1 IS E'Alternative destination aerodrome';
COMMENT ON COLUMN ffpl.TFLIGHT IS E'Flight type';
COMMENT ON COLUMN ffpl.ROUTE IS E'Flight route';

CREATE TABLE meteo_runway (
	runway_id bigint NOT NULL,
	control_time timestamp,
	magnetic_wind smallint,
	average_speed bigint,
	max_speed bigint,
	side_wind bigint,
	longitudial_wind bigint,
	sight_dist bigint,
	sdist_start_ovi bigint,
	sdist_middle_ovi bigint,
	sdist_end_ovi bigint,
	cloud_lower bigint,
	pressure_threshould bigint,
	pressure_sea bigint,
	temperature bigint,
	condensation_point bigint
);
COMMENT ON COLUMN meteo_runway.SIGHT_DIST IS E'????????????????? ????????? ????????? ?? ??? ? ??????';
COMMENT ON COLUMN meteo_runway.CONTROL_TIME IS E'????? ?????????? (??? ???)';
COMMENT ON COLUMN meteo_runway.AVERAGE_SPEED IS E'??????? ???????? ? ?/?';
COMMENT ON COLUMN meteo_runway.TEMPERATURE IS E'??????????? ???????';
COMMENT ON COLUMN meteo_runway.MAX_SPEED IS E'???????????? ???????? ? ?/?';
COMMENT ON COLUMN meteo_runway.LONGITUDIAL_WIND IS E'?????????? ???????????? ????? ???????????? ??? ? ?/?';
COMMENT ON COLUMN meteo_runway.SDIST_START_OVI IS E'????????????????? ????????? ????????? ??? ? ?????? ??? ? ??????';
COMMENT ON COLUMN meteo_runway.PRESSURE_THRESHOULD IS E'???????? ?? ??????? ?????? ??? ? ??. ??.??.';
COMMENT ON COLUMN meteo_runway.SIDE_WIND IS E'??????? ???????????? ????? ???????????? ??? ? ?/?';
COMMENT ON COLUMN meteo_runway.CONDENSATION_POINT IS E'????? ????';
COMMENT ON COLUMN meteo_runway.SDIST_MIDDLE_OVI IS E'????????????????? ????????? ????????? ??? ? ???????? ??? ? ??????';
COMMENT ON COLUMN meteo_runway.CLOUD_LOWER IS E'?????? ?????? ??????? ?????????? ? ??????';
COMMENT ON COLUMN meteo_runway.SDIST_END_OVI IS E'????????????????? ????????? ????????? ??? ? ????? ??? ? ??????';
COMMENT ON COLUMN meteo_runway.MAGNETIC_WIND IS E'????????? ??????????? ????? ? ????????';
COMMENT ON COLUMN meteo_runway.PRESSURE_SEA IS E'????????, ??????????? ? ?????? ???? ? ???';

CREATE TABLE template_dla (
	id bigint NOT NULL,
	name varchar(40) NOT NULL,
	aircraft varchar(7),
	adep varchar(4),
	departure_time timestamp,
	ades varchar(4),
	other varchar(4000),
	receivers varchar(4000)
);

CREATE TABLE aftn_abonent (
	id bigint NOT NULL,
	name varchar(200) NOT NULL,
	address varchar(8) NOT NULL
);

CREATE TABLE currentstatus (
	statusid bigint NOT NULL,
	statusgiver varchar(50) NOT NULL,
	statustime timestamp NOT NULL,
	statuscode smallint NOT NULL
);

CREATE TABLE asterix (
	id bigint NOT NULL,
	sac bigint NOT NULL,
	sic bigint NOT NULL,
	track_number bigint NOT NULL,
	mode_3a_reply bigint,
	track_time timestamp,
	latitude double precision,
	longitude double precision,
	flight_level double precision,
	v_x double precision,
	v_y double precision,
	v_z double precision
);

CREATE TABLE hist_rpl (
	id bigint NOT NULL,
	fir_name varchar(4) NOT NULL DEFAULT 'UMMV',
	aircraft_id varchar(7) NOT NULL,
	taircraft varchar(4),
	frules varchar(1),
	tflight varchar(1),
	num smallint,
	wtc varchar(1),
	equipment varchar(222),
	adep varchar(4),
	time timestamp,
	speed varchar(5),
	flevel varchar(5),
	route varchar(4000),
	ades varchar(4),
	eet varchar(5),
	alt1 varchar(4),
	alt2 varchar(4),
	other varchar(4000),
	trtime timestamp,
	exfpl char(1),
	days char(7),
	hist_id bigint NOT NULL,
	modified_by bigint NOT NULL,
	modified_at timestamp NOT NULL DEFAULT (now() AT TIME ZONE 'UTC'),
	modification_type char(1),
	entry_fir_eet varchar(5),
	valid_from timestamp,
	valid_to timestamp
);

CREATE TABLE exercise_circle_type (
	id bigint NOT NULL,
	name varchar(20) NOT NULL
);

CREATE TABLE flight_types (
	name varchar(1) NOT NULL
);

CREATE TABLE user_rights (
	id bigint NOT NULL,
	user_id bigint NOT NULL,
	object_id varchar(100) NOT NULL,
	rights bigint NOT NULL
);
COMMENT ON COLUMN user_rights.ID IS E'Identifier';
COMMENT ON COLUMN user_rights.OBJECT_ID IS E'String object identifier';
COMMENT ON COLUMN user_rights.USER_ID IS E'User identifier';
COMMENT ON COLUMN user_rights.RIGHTS IS E'RIghts. (0 - disallow, not 0 - allow)';

CREATE TABLE archivemessages (
	msgid bigint NOT NULL,
	msgoriginalid bigint,
	msgdirection smallint NOT NULL,
	msgtime timestamp NOT NULL,
	msgfrom varchar(50),
	msgto varchar(50),
	msgtext text NOT NULL,
	msgtype varchar(20),
	msgstatus smallint NOT NULL
);

CREATE TABLE bearing_point (
	id bigint NOT NULL,
	name varchar(256),
	fir_name varchar(20) NOT NULL,
	rdf_latitude double precision NOT NULL,
	rdf_longitude double precision NOT NULL,
	sac bigint,
	sic bigint,
	channel bigint
);

CREATE TABLE hist_report (
	id bigint NOT NULL,
	text varchar(4000),
	time timestamp
);

CREATE TABLE outputtelegrams (
	id bigint NOT NULL,
	created timestamp NOT NULL DEFAULT (now() AT TIME ZONE 'UTC'),
	text varchar(4000) NOT NULL,
	header varchar(4000),
	message varchar(4000),
	addresses varchar(4000),
	processed bigint NOT NULL DEFAULT 0,
	send_now bigint NOT NULL DEFAULT 0,
	type varchar(10),
	fill_time varchar(6)
);
COMMENT ON TABLE outputtelegrams IS E'AFTN messages(telegrams)';
COMMENT ON COLUMN outputtelegrams.ID IS E'identifier';
COMMENT ON COLUMN outputtelegrams.TEXT IS E'AFTN message text';
COMMENT ON COLUMN outputtelegrams.CREATED IS E'UTC timestamp of inserting message';
COMMENT ON COLUMN outputtelegrams.MESSAGE IS E'AFTN addresses';
COMMENT ON COLUMN outputtelegrams.HEADER IS E'AFTN message header';

CREATE TABLE exercise_plane (
	id_exercise bigint NOT NULL,
	id_plane bigint NOT NULL,
	start_time bigint NOT NULL,
	id_parentfpl bigint,
	op varchar(20),
	sector varchar(512),
	circle bigint NOT NULL DEFAULT 0
);

CREATE TABLE sectoring (
	id bigint NOT NULL,
	name varchar(256) NOT NULL,
	type_id bigint NOT NULL
);

CREATE TABLE restriction_user_sync (
	id bigint NOT NULL,
	type smallint NOT NULL DEFAULT 1,
	lasttouch timestamp NOT NULL DEFAULT now()
);
COMMENT ON COLUMN restriction_user_sync.ID IS E'Identifier of Restriction user zone';
COMMENT ON COLUMN restriction_user_sync.LASTTOUCH IS E'Last touch (insert, update, delete data from restriction_user table) timestamp';
COMMENT ON COLUMN restriction_user_sync.TYPE IS E'Type of an action: delete = 0, insert(or update) = 1';

CREATE TABLE fpl_changes_master (
	id bigint NOT NULL,
	fir_name varchar(4) NOT NULL DEFAULT 'UMMV',
	aircraft_id varchar(7) NOT NULL,
	taircraft varchar(4),
	frules varchar(1),
	tflight varchar(1),
	num smallint,
	wtc varchar(1),
	equipment varchar(222),
	adep varchar(4) NOT NULL,
	time timestamp,
	speed varchar(5) NOT NULL,
	flevel varchar(5) NOT NULL,
	route varchar(4000),
	ades varchar(4) NOT NULL,
	eet varchar(5),
	alt1 varchar(4),
	alt2 varchar(4),
	other varchar(4000),
	trtime timestamp NOT NULL DEFAULT (now() AT TIME ZONE 'UTC'),
	exfpl char(1),
	visibility smallint,
	message_id bigint,
	entry_fir_eet varchar(5),
	oper varchar(7),
	oper_time timestamp,
	message_text varchar(4000),
	status smallint DEFAULT 0,
	pod_in varchar(10),
	t_in timestamp,
	h_in varchar(10),
	pod_out varchar(10),
	t_out timestamp,
	h_out varchar(10),
	fpl_id varchar(40)
);
COMMENT ON TABLE fpl_changes_master IS E'Changes in FPL table';
COMMENT ON COLUMN fpl_changes_master.FPL_ID IS E'id in master';
COMMENT ON COLUMN fpl_changes_master.ENTRY_FIR_EET IS E'EET on entry in fir';
COMMENT ON COLUMN fpl_changes_master.T_OUT IS E'Exit time';
COMMENT ON COLUMN fpl_changes_master.STATUS IS E'The current status of the plan: 0-free, 1-activated, 2-assumed, 3-transferred';
COMMENT ON COLUMN fpl_changes_master.SPEED IS E'Speed of flight';
COMMENT ON COLUMN fpl_changes_master.NUM IS E'Number of aircrafts';
COMMENT ON COLUMN fpl_changes_master.VISIBILITY IS E'Visibility of this fpl (customer asked this field)';
COMMENT ON COLUMN fpl_changes_master.MESSAGE_ID IS E'Message id in arc_aftn';
COMMENT ON COLUMN fpl_changes_master.FIR_NAME IS E'Flight region identificator';
COMMENT ON COLUMN fpl_changes_master.OTHER IS E'Other information';
COMMENT ON COLUMN fpl_changes_master.POD_OUT IS E'Exit point from the area of responsibility';
COMMENT ON COLUMN fpl_changes_master.POD_IN IS E'Entry point to the area of responsibility';
COMMENT ON COLUMN fpl_changes_master.FLEVEL IS E'Flight level';
COMMENT ON COLUMN fpl_changes_master.WTC IS E'Turbulence category';
COMMENT ON COLUMN fpl_changes_master.ALT1 IS E'Alternative destination aerodrome';
COMMENT ON COLUMN fpl_changes_master.ROUTE IS E'Flight route';
COMMENT ON COLUMN fpl_changes_master.OPER IS E'Type operation';
COMMENT ON COLUMN fpl_changes_master.ID IS E'Identificator';
COMMENT ON COLUMN fpl_changes_master.ADEP IS E'Departure aerodrome';
COMMENT ON COLUMN fpl_changes_master.T_IN IS E'Time of entry into the area of responsibility';
COMMENT ON COLUMN fpl_changes_master.FRULES IS E'Flight rules';
COMMENT ON COLUMN fpl_changes_master.TRTIME IS E'Time of getting this record by aftnservice';
COMMENT ON COLUMN fpl_changes_master.EQUIPMENT IS E'Equipment on aircraft';
COMMENT ON COLUMN fpl_changes_master.ADES IS E'Destination aerodrome';
COMMENT ON COLUMN fpl_changes_master.MESSAGE_TEXT IS E'Message text in arc_aftn';
COMMENT ON COLUMN fpl_changes_master.TIME IS E'Time of flight start';
COMMENT ON COLUMN fpl_changes_master.AIRCRAFT_ID IS E'Aircraft identificator';
COMMENT ON COLUMN fpl_changes_master.OPER_TIME IS E'Time operation';
COMMENT ON COLUMN fpl_changes_master.TAIRCRAFT IS E'Aircraft type';
COMMENT ON COLUMN fpl_changes_master.EXFPL IS E'FPL status (c - cancelled, d - delayed, a -arrived, f - departure,)';
COMMENT ON COLUMN fpl_changes_master.H_OUT IS E'Exit height';
COMMENT ON COLUMN fpl_changes_master.ALT2 IS E'Another alternative destination aerodrome';
COMMENT ON COLUMN fpl_changes_master.EET IS E'??? Time of flight end';
COMMENT ON COLUMN fpl_changes_master.TFLIGHT IS E'Flight type';
COMMENT ON COLUMN fpl_changes_master.H_IN IS E'Height of entry into the area of responsibility';

CREATE TABLE fpl_on_future (
	id bigint,
	fir_name varchar(4) DEFAULT 'UMMV',
	aircraft_id varchar(7),
	taircraft varchar(4),
	frules varchar(1),
	tflight varchar(1),
	num smallint,
	wtc varchar(1),
	equipment varchar(222),
	adep varchar(4),
	time timestamp,
	speed varchar(5),
	flevel varchar(5),
	route varchar(4000),
	ades varchar(4),
	eet varchar(5),
	alt1 varchar(4),
	alt2 varchar(4),
	other varchar(4000),
	trtime timestamp,
	exfpl char(1),
	visibility smallint,
	message_id bigint,
	entry_fir_eet varchar(5)
);
COMMENT ON TABLE fpl_on_future IS E'Today flight planes';
COMMENT ON COLUMN fpl_on_future.ID IS E'Identificator';
COMMENT ON COLUMN fpl_on_future.ADEP IS E'Departure aerodrome';
COMMENT ON COLUMN fpl_on_future.SPEED IS E'Speed of flight';
COMMENT ON COLUMN fpl_on_future.NUM IS E'Number of aircrafts';
COMMENT ON COLUMN fpl_on_future.VISIBILITY IS E'Visibility of this fpl (customer asked this field)';
COMMENT ON COLUMN fpl_on_future.FRULES IS E'Flight rules';
COMMENT ON COLUMN fpl_on_future.FIR_NAME IS E'Flight region identificator';
COMMENT ON COLUMN fpl_on_future.TRTIME IS E'Time of getting this record by AEROservice';
COMMENT ON COLUMN fpl_on_future.EQUIPMENT IS E'Equipment on aircraft';
COMMENT ON COLUMN fpl_on_future.ADES IS E'Destination aerodrome';
COMMENT ON COLUMN fpl_on_future.OTHER IS E'Other information';
COMMENT ON COLUMN fpl_on_future.AIRCRAFT_ID IS E'Aircraft identificator';
COMMENT ON COLUMN fpl_on_future.TIME IS E'Time of flight start';
COMMENT ON COLUMN fpl_on_future.TAIRCRAFT IS E'Aircraft type';
COMMENT ON COLUMN fpl_on_future.FLEVEL IS E'Flight level';
COMMENT ON COLUMN fpl_on_future.EXFPL IS E'FPL status (c - cancelled, d - delayed, a -arrived, f - departure,)';
COMMENT ON COLUMN fpl_on_future.WTC IS E'Turbulence category';
COMMENT ON COLUMN fpl_on_future.ALT2 IS E'Another alternative destination aerodrome';
COMMENT ON COLUMN fpl_on_future.EET IS E'??? Time of flight end';
COMMENT ON COLUMN fpl_on_future.ALT1 IS E'Alternative destination aerodrome';
COMMENT ON COLUMN fpl_on_future.TFLIGHT IS E'Flight type';
COMMENT ON COLUMN fpl_on_future.ROUTE IS E'Flight route';

CREATE TABLE oldi_clients (
	id bigint NOT NULL,
	client varchar(8) NOT NULL,
	status smallint NOT NULL,
	sector varchar(100) NOT NULL
);

CREATE TABLE point_type (
	id bigint NOT NULL,
	name varchar(20) NOT NULL
);
COMMENT ON TABLE point_type IS E'Provide convertion from numberic type of point to textual';
COMMENT ON COLUMN point_type.ID IS E'Primary key';
COMMENT ON COLUMN point_type.NAME IS E'Textual description';

CREATE TABLE fpl_additional (
	fpl_id_ref bigint NOT NULL,
	additional_info varchar(4000)
);
COMMENT ON TABLE fpl_additional IS E'FPL additional info (field 19 and more)';
COMMENT ON COLUMN fpl_additional.FPL_ID_REF IS E'ID in FPL table (primary and foreign key)';
COMMENT ON COLUMN fpl_additional.ADDITIONAL_INFO IS E'Additional info (field 19)';

CREATE TABLE notam (
	id bigint NOT NULL,
	series char(1) NOT NULL,
	snumber smallint NOT NULL,
	year smallint,
	nature char(1) NOT NULL,
	replace_series char(1),
	replace_snumber smallint,
	replace_year bigint,
	fir char(4),
	subject char(2),
	condition char(2),
	traffic varchar(2),
	scope varchar(4),
	q_lower_limit smallint,
	q_upper_limit smallint,
	location varchar(11),
	radius smallint,
	aerodrome char(4),
	valid_from timestamp,
	valid_until timestamp,
	valid_until_t varchar(4),
	schedule varchar(450),
	description varchar(4000),
	lower_limit varchar(24),
	upper_limit varchar(24),
	sequence_id bigint,
	state char(1),
	purpose char(4)
);
COMMENT ON COLUMN notam.ID IS E'?????????????';
COMMENT ON COLUMN notam.TRAFFIC IS E'????????
I =  ??? (IVR)
V = ??? (VFR)
IV = ???/???.';
COMMENT ON COLUMN notam.FIR IS E'FIR, ?? ??????? ????????? ?????????';
COMMENT ON COLUMN notam.VALID_UNTIL_T IS E'?????????? ????????:
- PERM ? ?????????? ??? ?????????
- EST ? ????????????????.';
COMMENT ON COLUMN notam.SUBJECT IS E'??? NOTAM - ????????????? ??? ????
- ??????? ????????? (??? ???????? ??? ???????);';
COMMENT ON COLUMN notam.REPLACE_YEAR IS E'??? ??????????? ?????????';
COMMENT ON COLUMN notam.SCHEDULE IS E'??????????';
COMMENT ON COLUMN notam.Q_UPPER_LIMIT IS E'??????? ???????
000 ? ??????? ??????? ???? (MSL);
000/999 ? ?????? ???????????.';
COMMENT ON COLUMN notam.CONDITION IS E'???????
????????? ? ????? ????? ?????????? ???????, ??????????? ? ???????? ????????? (??? ????????? ? ???????????????? ?????????).';
COMMENT ON COLUMN notam.SEQUENCE_ID IS E'????????????? ??????? NOTAM ?? ????????? ????? NOTAM???';
COMMENT ON COLUMN notam.SCOPE IS E'????? ????????
? ? ????????;
? ? ???????;
W ? ????????????? ??????????????;
?? ? ?????????????????? ???????? ???????????? ? ???????? ??????????? ? ??????????.';
COMMENT ON COLUMN notam.Q_LOWER_LIMIT IS E'?????? ???????
000 ? ??????? ??????? ???? (MSL);
000/999 ? ?????? ???????????.';
COMMENT ON COLUMN notam.AERODROME IS E'????????';
COMMENT ON COLUMN notam.SERIES IS E'?????';
COMMENT ON COLUMN notam.VALID_UNTIL IS E'????????? ??';
COMMENT ON COLUMN notam.UPPER_LIMIT IS E'??????? ??????? ??????????? ?????????? ???????????? ??? ????????????? ??????????????
- UNL ? ??? ???????????;
- 16200MSL ? 16200 ????? ??? ??????? ??????? ????;
- 6500m AGL ? 6500 ?????? ??? ??????? ?????;
- ? ??.';
COMMENT ON COLUMN notam.LOCATION IS E'??????????';
COMMENT ON COLUMN notam.LOWER_LIMIT IS E'?????? ??????? ??????????? ?????????? ???????????? ??? ????????????? ??????????????
- MSL ? ??????? ????;
- GND ? ??????? ?????;
- FL120 ? ?? ??????? 120;
- CFC ? ???????????;
- ? ??.';
COMMENT ON COLUMN notam.REPLACE_SNUMBER IS E'???????? ????? ??????????? ?????????';
COMMENT ON COLUMN notam.PURPOSE IS E'????
N ? ???????? NOTAM ??? ????????????????? ??????????? ???????????? ??; 
B ? NOTAM ?????????? ? ????????? ???????????? ?????????? ??? (PIB);
O ? ?????? ???????????????? ?????????? ??? ??????? ?? ???;
M ? NOTAM ??? ????????????? ??????????? ????????????.';
COMMENT ON COLUMN notam.SNUMBER IS E'???????? ?????';
COMMENT ON COLUMN notam.DESCRIPTION IS E'????????';
COMMENT ON COLUMN notam.STATE IS E'NULL ???? NOTAM ?????????, ? ? ???? ??? ???????, R ? ???? ??? ???????';
COMMENT ON COLUMN notam.VALID_FROM IS E'????????? ?';
COMMENT ON COLUMN notam.RADIUS IS E'??????';

CREATE TABLE restriction_user (
	id bigint NOT NULL,
	name varchar(30),
	zone_id bigint NOT NULL,
	h_min bigint,
	h_max bigint,
	time_start timestamp,
	time_end timestamp,
	type smallint NOT NULL,
	guid varchar(128)
);
COMMENT ON COLUMN restriction_user.ID IS E'Первичный и уникальный ключ совместно с таблицей RESTRICTION';
COMMENT ON COLUMN restriction_user.NAME IS E'Имя зоны';
COMMENT ON COLUMN restriction_user.H_MAX IS E'Верхняя граница зоны';
COMMENT ON COLUMN restriction_user.H_MIN IS E'Нижняя граница зоны';
COMMENT ON COLUMN restriction_user.TYPE IS E'Тип зоны ограничения из таблицы RESTRICTION_USER_TYPE';
COMMENT ON COLUMN restriction_user.TIME_START IS E'Начальное время появления зоны';
COMMENT ON COLUMN restriction_user.GUID IS E'Уникальный идентификатор';
COMMENT ON COLUMN restriction_user.ZONE_ID IS E'Идентификатор ФИР-а';
COMMENT ON COLUMN restriction_user.TIME_END IS E'Время исчезновения зоны';

CREATE TABLE restriction_type (
	id bigint NOT NULL,
	name varchar(100) NOT NULL
);
COMMENT ON TABLE restriction_type IS E'Provide convertion from numberic type of restriction zone to textual reprisentation';
COMMENT ON COLUMN restriction_type.ID IS E'Primaty key';
COMMENT ON COLUMN restriction_type.NAME IS E'Textual description';

CREATE TABLE client_sectoring (
	id bigint NOT NULL,
	client_role_id bigint NOT NULL,
	sectoring_id bigint NOT NULL
);

CREATE TABLE aftn_group (
	id bigint NOT NULL,
	name varchar(200) NOT NULL
);

CREATE TABLE meteo (
	id bigint NOT NULL,
	zone_id bigint NOT NULL,
	name varchar(255) NOT NULL,
	type bigint NOT NULL,
	utc_time bigint,
	sic bigint,
	sac bigint,
	course bigint,
	speed bigint,
	h bigint
);

CREATE TABLE airplane_speed (
	id bigint NOT NULL,
	flevel double precision NOT NULL DEFAULT NULL,
	v_climb double precision NOT NULL DEFAULT NULL,
	v_climb_max double precision NOT NULL DEFAULT NULL,
	v_descend double precision NOT NULL DEFAULT NULL,
	v_descend_max double precision NOT NULL DEFAULT NULL,
	ias double precision NOT NULL DEFAULT NULL,
	ias_min double precision NOT NULL DEFAULT NULL,
	ias_max double precision NOT NULL DEFAULT NULL,
	airplane_id varchar(4)
);

CREATE TABLE ssa_point_type (
	id bigint NOT NULL,
	name varchar(40)
);
COMMENT ON TABLE ssa_point_type IS E'Provide convertion from numberic type of ssa point to textual reprisentation';
COMMENT ON COLUMN ssa_point_type.ID IS E'Primaty key';
COMMENT ON COLUMN ssa_point_type.NAME IS E'Textual description';

CREATE TABLE msg_from_tan (
	id bigint,
	fir_name varchar(5),
	aircraft_id varchar(10),
	taircraft varchar(4),
	frules varchar(1),
	tflight varchar(1),
	num bigint,
	wtc varchar(1),
	equipment varchar(222),
	adep varchar(4),
	time timestamp,
	speed varchar(6),
	flevel varchar(6),
	route varchar(4000),
	ades varchar(4),
	eet varchar(5),
	alt1 varchar(4),
	alt2 varchar(4),
	other varchar(4000),
	trtime timestamp,
	exfpl varchar(1),
	visibility bigint,
	entry_fir_eet varchar(5),
	oper varchar(7),
	oper_time timestamp,
	message_text varchar(4000)
);

CREATE TABLE hist_fpl (
	id bigint NOT NULL DEFAULT NULL,
	fir_name varchar(4) NOT NULL DEFAULT 'UMMV',
	aircraft_id varchar(7) NOT NULL,
	taircraft varchar(4),
	frules varchar(1),
	tflight varchar(1),
	num smallint,
	wtc varchar(1),
	equipment varchar(222),
	adep varchar(4),
	time timestamp,
	speed varchar(5),
	flevel varchar(5),
	route varchar(4000),
	ades varchar(4),
	eet varchar(5),
	alt1 varchar(4),
	alt2 varchar(4),
	other varchar(4000),
	trtime timestamp,
	exfpl char(1),
	visibility smallint,
	hist_id bigint NOT NULL,
	modified_by bigint NOT NULL,
	modified_at timestamp NOT NULL DEFAULT (now() AT TIME ZONE 'UTC'),
	modification_type char(1),
	actual char(1) NOT NULL DEFAULT 1,
	message_id bigint,
	entry_fir_eet varchar(5)
);
COMMENT ON TABLE hist_fpl IS E'Today flight planes';
COMMENT ON COLUMN hist_fpl.ID IS E'Identificator';
COMMENT ON COLUMN hist_fpl.ADEP IS E'Departure aerodrome';
COMMENT ON COLUMN hist_fpl.SPEED IS E'Speed of flight';
COMMENT ON COLUMN hist_fpl.ACTUAL IS E'Is actual fpl';
COMMENT ON COLUMN hist_fpl.NUM IS E'Number of aircrafts';
COMMENT ON COLUMN hist_fpl.VISIBILITY IS E'Visibility of this fpl (customer asked this field)';
COMMENT ON COLUMN hist_fpl.FRULES IS E'Flight rules';
COMMENT ON COLUMN hist_fpl.MODIFICATION_TYPE IS E'I - insert, U - update, D - delete';
COMMENT ON COLUMN hist_fpl.MESSAGE_ID IS E'Identifier of AFTN message';
COMMENT ON COLUMN hist_fpl.FIR_NAME IS E'Flight region identificator';
COMMENT ON COLUMN hist_fpl.TRTIME IS E'Time of getting this record by aftnservice';
COMMENT ON COLUMN hist_fpl.MODIFIED_AT IS E'When modify current fpl';
COMMENT ON COLUMN hist_fpl.EQUIPMENT IS E'Equipment on aircraft';
COMMENT ON COLUMN hist_fpl.ADES IS E'Destination aerodrome';
COMMENT ON COLUMN hist_fpl.OTHER IS E'Other information';
COMMENT ON COLUMN hist_fpl.TIME IS E'Time of flight start';
COMMENT ON COLUMN hist_fpl.AIRCRAFT_ID IS E'Aircraft identificator';
COMMENT ON COLUMN hist_fpl.TAIRCRAFT IS E'Aircraft type';
COMMENT ON COLUMN hist_fpl.FLEVEL IS E'Flight level';
COMMENT ON COLUMN hist_fpl.EXFPL IS E'FPL status (c - cancelled, d - delayed, a -arrived, f - departure,)';
COMMENT ON COLUMN hist_fpl.WTC IS E'Turbulence category';
COMMENT ON COLUMN hist_fpl.MODIFIED_BY IS E'Who modify current fpl';
COMMENT ON COLUMN hist_fpl.ALT2 IS E'Another alternative destination aerodrome';
COMMENT ON COLUMN hist_fpl.EET IS E'??? Time of flight end';
COMMENT ON COLUMN hist_fpl.ALT1 IS E'Alternative destination aerodrome';
COMMENT ON COLUMN hist_fpl.TFLIGHT IS E'Flight type';
COMMENT ON COLUMN hist_fpl.ROUTE IS E'Flight route';

CREATE TABLE template_dep (
	id bigint NOT NULL,
	name varchar(40) NOT NULL,
	aircraft varchar(7),
	adep varchar(4),
	departure_time timestamp,
	ades varchar(4),
	other varchar(4000),
	receivers varchar(4000)
);

CREATE TABLE radio_devices (
	name varchar(1) NOT NULL
);

CREATE TABLE restriction_point_master (
	id bigint NOT NULL,
	restriction_id bigint NOT NULL,
	latitude double precision NOT NULL,
	longitude double precision NOT NULL,
	sn bigint NOT NULL
);
COMMENT ON TABLE restriction_point_master IS E'Provide line aproximation for restriction zones';
COMMENT ON COLUMN restriction_point_master.ID IS E'Primary key';
COMMENT ON COLUMN restriction_point_master.RESTRICTION_ID IS E'Reference to RESTRICTION.ID';
COMMENT ON COLUMN restriction_point_master.LONGITUDE IS E'Longitude coordinate part of a point';
COMMENT ON COLUMN restriction_point_master.SN IS E'Sequence number of points';
COMMENT ON COLUMN restriction_point_master.LATITUDE IS E'Latitude coordinate part of a point';

CREATE TABLE aftn_abonent_autotypes (
	id bigint NOT NULL,
	aftn_abonent_id bigint NOT NULL,
	free_text smallint NOT NULL DEFAULT 0,
	fpl smallint NOT NULL DEFAULT 0,
	arr smallint NOT NULL DEFAULT 0,
	chg smallint NOT NULL DEFAULT 0,
	cnl smallint NOT NULL DEFAULT 0,
	dep smallint NOT NULL DEFAULT 0,
	dla smallint NOT NULL DEFAULT 0
);
COMMENT ON COLUMN aftn_abonent_autotypes.DLA IS E'This is bool';
COMMENT ON COLUMN aftn_abonent_autotypes.CHG IS E'This is bool';
COMMENT ON COLUMN aftn_abonent_autotypes.ARR IS E'This is bool';
COMMENT ON COLUMN aftn_abonent_autotypes.CNL IS E'This is bool';
COMMENT ON COLUMN aftn_abonent_autotypes.DEP IS E'This is bool';
COMMENT ON COLUMN aftn_abonent_autotypes.FREE_TEXT IS E'This is bool';
COMMENT ON COLUMN aftn_abonent_autotypes.FPL IS E'This is bool';

CREATE TABLE vehicle_plan (
	id bigint NOT NULL,
	name varchar(100) NOT NULL,
	vehicle_id bigint,
	route_id bigint,
	speed bigint,
	starttime bigint NOT NULL DEFAULT 0
);

CREATE TABLE ssa_point (
	id bigint NOT NULL,
	ssa_id bigint NOT NULL,
	point_id bigint,
	sn bigint NOT NULL,
	flevel double precision,
	speed double precision,
	type bigint NOT NULL DEFAULT NULL,
	course double precision,
	turn bigint,
	altitude1 double precision,
	fly_over smallint DEFAULT 0
);
COMMENT ON TABLE ssa_point IS E'Squence of points for SSA ways';
COMMENT ON COLUMN ssa_point.ID IS E'Primary key';
COMMENT ON COLUMN ssa_point.SSA_ID IS E'Reference to SSA.ID';
COMMENT ON COLUMN ssa_point.TYPE IS E'Type of the point. See SSA_POINT_TYPE table';
COMMENT ON COLUMN ssa_point.SN IS E'Sequnce number of the point';
COMMENT ON COLUMN ssa_point.TURN IS E'Turn type of the point. See SSA_POINT_TURN table';

CREATE TABLE archiveinputmessages (
	msgid bigint NOT NULL,
	msgtime timestamp NOT NULL,
	msgfrom varchar(50) NOT NULL,
	msgto varchar(50) NOT NULL,
	msgtext text NOT NULL,
	msgtype varchar(20) NOT NULL
);

CREATE TABLE ssa_point_turn (
	id bigint NOT NULL,
	name varchar(40)
);
COMMENT ON TABLE ssa_point_turn IS E'Provide convertion from numberic type of ssa turning to textual reprisentation';
COMMENT ON COLUMN ssa_point_turn.ID IS E'Primaty key';
COMMENT ON COLUMN ssa_point_turn.NAME IS E'Textual description';

CREATE TABLE oldi_sfpl (
	aircraft_id varchar(7) NOT NULL,
	adep varchar(4) NOT NULL,
	ades varchar(4) NOT NULL,
	reciever varchar(100) NOT NULL
);
COMMENT ON COLUMN oldi_sfpl.ADES IS E'Destination aerodrome';
COMMENT ON COLUMN oldi_sfpl.AIRCRAFT_ID IS E'Aircraft identificator';
COMMENT ON COLUMN oldi_sfpl.ADEP IS E'Departure aerodrome';

CREATE TABLE outputmessages (
	msgid bigint NOT NULL,
	msgtime timestamp,
	msgfrom varchar(50) NOT NULL,
	msgto varchar(50) NOT NULL,
	msgtext text NOT NULL,
	msgtype varchar(20) NOT NULL,
	msgstatus smallint NOT NULL
);

CREATE TABLE template_free_text (
	id bigint NOT NULL,
	name varchar(40) NOT NULL,
	text varchar(4000) NOT NULL,
	receivers varchar(4000)
);

CREATE TABLE holding_point_master (
	id bigint NOT NULL,
	holding_id bigint NOT NULL,
	latitude double precision NOT NULL,
	longitude double precision NOT NULL,
	sn bigint NOT NULL
);
COMMENT ON TABLE holding_point_master IS E'Polygonal aproximation of the holding zone. Contains points with linked with line.';
COMMENT ON COLUMN holding_point_master.ID IS E'Primary key';
COMMENT ON COLUMN holding_point_master.LONGITUDE IS E'The longitude coordinate part of the boundaty point';
COMMENT ON COLUMN holding_point_master.SN IS E'The suquintal number of the point';
COMMENT ON COLUMN holding_point_master.LATITUDE IS E'The latitude coordinate part of the boundaty point';
COMMENT ON COLUMN holding_point_master.HOLDING_ID IS E'The id of holdinf zone';

CREATE TABLE t_migration (
	id bigint NOT NULL,
	type bigint NOT NULL,
	sn bigint NOT NULL,
	latitude double precision,
	longitude double precision,
	zone_id bigint NOT NULL,
	arc_latitude double precision,
	arc_longitude double precision,
	arc_distance double precision
);

CREATE TABLE holding (
	id bigint NOT NULL,
	point_id bigint NOT NULL,
	type bigint NOT NULL,
	in_course double precision NOT NULL,
	turn_direction bigint NOT NULL,
	leg_length double precision NOT NULL,
	leg_time bigint NOT NULL,
	speed double precision NOT NULL,
	zone_id bigint NOT NULL,
	h_min bigint DEFAULT 0,
	h_max bigint DEFAULT 0
);
COMMENT ON TABLE holding IS E'Describe the holding zone.';
COMMENT ON COLUMN holding.ID IS E'Primary key';
COMMENT ON COLUMN holding.LEG_TIME IS E'The other variant leng assignment is LEG_TIME*SPEED';
COMMENT ON COLUMN holding.POINT_ID IS E'The entry point of the holding zone';
COMMENT ON COLUMN holding.H_MAX IS E'Top border of holding (in meters)';
COMMENT ON COLUMN holding.TYPE IS E'Type of holding zone. For textual descriprion see HOLDING_TYPE table';
COMMENT ON COLUMN holding.SPEED IS E'The other variant leng assignment is LEG_TIME*SPEED';
COMMENT ON COLUMN holding.H_MIN IS E'Bottom border of holding (in meters)';
COMMENT ON COLUMN holding.IN_COURSE IS E'Entering course';
COMMENT ON COLUMN holding.ZONE_ID IS E'The zone id which holding is belonged';
COMMENT ON COLUMN holding.LEG_LENGTH IS E'The length of the holding zone';
COMMENT ON COLUMN holding.TURN_DIRECTION IS E'Turn direction after entering holding zone';

CREATE TABLE activation (
	acid varchar(10) NOT NULL,
	code varchar(10) NOT NULL,
	first_point varchar(100),
	start_time timestamp,
	echelon numeric,
	sector varchar(512)
);

CREATE TABLE ssa (
	id bigint NOT NULL,
	runway_id bigint NOT NULL,
	name varchar(10) NOT NULL,
	type bigint DEFAULT NULL,
	trans_alt double precision
);
COMMENT ON TABLE ssa IS E'Seed Star and aproach for the runway';
COMMENT ON COLUMN ssa.ID IS E'Primary key';
COMMENT ON COLUMN ssa.NAME IS E'Name of ssa way';
COMMENT ON COLUMN ssa.TYPE IS E'Type of ssa way. For textual represintation see SSA_TYPE table.';
COMMENT ON COLUMN ssa.RUNWAY_ID IS E'Reference to RUNWAY.ID';

CREATE TABLE restriction_user_type (
	id smallint NOT NULL,
	name varchar(20) NOT NULL
);

CREATE TABLE restriction_point (
	id bigint NOT NULL,
	sn bigint NOT NULL,
	type bigint NOT NULL,
	latitude double precision NOT NULL,
	longitude double precision NOT NULL,
	arc_latitude double precision NOT NULL,
	arc_longitude double precision NOT NULL,
	arc_distance double precision NOT NULL,
	restriction_id bigint NOT NULL
);
COMMENT ON TABLE restriction_point IS E'Boundary points of restriction zone';
COMMENT ON COLUMN restriction_point.ID IS E'Primary key';
COMMENT ON COLUMN restriction_point.ARC_DISTANCE IS E'Distance for arcs';
COMMENT ON COLUMN restriction_point.TYPE IS E'Type of boundery point';
COMMENT ON COLUMN restriction_point.RESTRICTION_ID IS E'Reference to RESTRICTION.ID';
COMMENT ON COLUMN restriction_point.SN IS E'Sequence number';
COMMENT ON COLUMN restriction_point.LONGITUDE IS E'Longitude coordinate part';
COMMENT ON COLUMN restriction_point.ARC_LATITUDE IS E'Latitude coordinate part for arcs';
COMMENT ON COLUMN restriction_point.LATITUDE IS E'Latitude coordinate part';
COMMENT ON COLUMN restriction_point.ARC_LONGITUDE IS E'longitude coordinate part for arcs';

CREATE TABLE turbulence_category (
	name varchar(1) NOT NULL
);

CREATE TABLE login_log (
	user_id bigint,
	user_name varchar(64),
	logged_time timestamp NOT NULL DEFAULT (now() AT TIME ZONE 'UTC'),
	logged_type char(1) NOT NULL DEFAULT 1
);
COMMENT ON TABLE login_log IS E'Table for storing login user information';
COMMENT ON COLUMN login_log.USER_ID IS E'User identifier';
COMMENT ON COLUMN login_log.USER_NAME IS E'User name';
COMMENT ON COLUMN login_log.LOGGED_TIME IS E'When user logged in/out';
COMMENT ON COLUMN login_log.LOGGED_TYPE IS E'Type in/out';

CREATE TABLE vehicle_route (
	id bigint NOT NULL,
	name varchar(100) NOT NULL,
	airport_id bigint NOT NULL
);

CREATE TABLE zone_schedule (
	id bigint NOT NULL,
	beg_date varchar(6),
	beg_time varchar(6),
	end_date varchar(6),
	end_time varchar(6),
	weekly_day bigint
);

CREATE TABLE level_types (
	name varchar(1) NOT NULL
);

CREATE TABLE sectoring_type (
	id bigint NOT NULL,
	name varchar(256) NOT NULL,
	permission varchar(4000)
);

CREATE TABLE vehicle_exercise (
	id bigint NOT NULL,
	exercise_id bigint NOT NULL,
	vehicle_plan_id bigint NOT NULL
);

CREATE TABLE stand_state (
	id bigint NOT NULL,
	name varchar(20) NOT NULL
);

CREATE TABLE man_aftn (
	id bigint NOT NULL,
	created timestamp NOT NULL DEFAULT (now() AT TIME ZONE 'UTC'),
	text varchar(4000),
	header varchar(4000),
	message varchar(4000) DEFAULT NULL,
	processed bigint NOT NULL DEFAULT 0,
	type varchar(10),
	sender varchar(8),
	fill_time varchar(6)
);
COMMENT ON TABLE man_aftn IS E'Non-valid flight planes';
COMMENT ON COLUMN man_aftn.ID IS E'Identifier';
COMMENT ON COLUMN man_aftn.TEXT IS E'AFTN message source text';
COMMENT ON COLUMN man_aftn.CREATED IS E'When message created';

CREATE TABLE stand (
	id bigint NOT NULL,
	airport_id bigint NOT NULL,
	name varchar(200) NOT NULL
);

CREATE TABLE meteo_type (
	id bigint NOT NULL,
	name varchar(20) NOT NULL,
	full_name varchar(100) NOT NULL
);

CREATE TABLE echelons (
	id bigint NOT NULL,
	echelon bigint,
	meters bigint,
	feet bigint,
	azimuth bigint,
	vfr_ifr bigint
);
COMMENT ON COLUMN echelons.ID IS E'Identifier';
COMMENT ON COLUMN echelons.AZIMUTH IS E'Azimuth (1 to 179 is 179;
180 to 359 is 359)';
COMMENT ON COLUMN echelons.METERS IS E'About meters for echelon.';
COMMENT ON COLUMN echelons.FEET IS E'Feet for echelon';
COMMENT ON COLUMN echelons.VFR_IFR IS E'VFR flight = 0
IFR flight = 1';
COMMENT ON COLUMN echelons.ECHELON IS E'Echelon';

CREATE TABLE meteo_point (
	id bigint NOT NULL,
	meteo_id bigint NOT NULL,
	latitude double precision NOT NULL,
	longitude double precision NOT NULL,
	sn bigint NOT NULL
);

CREATE TABLE sent_aftn (
	id bigint NOT NULL,
	created timestamp NOT NULL,
	text varchar(4000),
	header varchar(4000),
	message varchar(4000),
	addresses varchar(4000),
	processed bigint NOT NULL DEFAULT 0,
	type varchar(10),
	serial_number varchar(10),
	fill_time varchar(6)
);

CREATE TABLE hist_man_aftn (
	id bigint NOT NULL,
	created timestamp NOT NULL,
	text varchar(4000),
	hist_id bigint NOT NULL,
	modified_by bigint NOT NULL,
	modified_at timestamp NOT NULL DEFAULT (now() AT TIME ZONE 'UTC'),
	modification_type char(1),
	header varchar(4000)
);
COMMENT ON TABLE hist_man_aftn IS E'History of changes MAN_AFTN table';
COMMENT ON COLUMN hist_man_aftn.TEXT IS E'message text';
COMMENT ON COLUMN hist_man_aftn.CREATED IS E'When record is created';
COMMENT ON COLUMN hist_man_aftn.MODIFIED_BY IS E'Who modified';
COMMENT ON COLUMN hist_man_aftn.HIST_ID IS E'History record id';
COMMENT ON COLUMN hist_man_aftn.MODIFICATION_TYPE IS E'Modified type (i - inserted; u - updated; d - deleted)';
COMMENT ON COLUMN hist_man_aftn.MODIFIED_AT IS E'When modified';

CREATE TABLE flight_rules (
	name varchar(1) NOT NULL
);

CREATE TABLE zone_boundary (
	id bigint NOT NULL,
	type bigint NOT NULL,
	sn bigint NOT NULL,
	latitude double precision DEFAULT 0,
	longitude double precision DEFAULT 0,
	zone_id bigint NOT NULL,
	arc_latitude double precision DEFAULT 0,
	arc_longitude double precision DEFAULT 0,
	arc_distance double precision DEFAULT 0
);
COMMENT ON TABLE zone_boundary IS E'Provide boundary for zones.';
COMMENT ON COLUMN zone_boundary.ID IS E'Primary key';
COMMENT ON COLUMN zone_boundary.ARC_DISTANCE IS E'The radius of circle for arcs';
COMMENT ON COLUMN zone_boundary.TYPE IS E'Type of the line. For textual description see BOUNDARY_POINT_TYPE';
COMMENT ON COLUMN zone_boundary.SN IS E'The sequence number of the boundary point.';
COMMENT ON COLUMN zone_boundary.LONGITUDE IS E'The longitude part of coordiants';
COMMENT ON COLUMN zone_boundary.ARC_LATITUDE IS E'The latitute perameter for arcs';
COMMENT ON COLUMN zone_boundary.ZONE_ID IS E'The reference to zone which point is belonged';
COMMENT ON COLUMN zone_boundary.LATITUDE IS E'The latitude part of coordiants';
COMMENT ON COLUMN zone_boundary.ARC_LONGITUDE IS E'The longitude perameter for arcs';

CREATE TABLE trashtelegrams (
	id bigint NOT NULL,
	created timestamp NOT NULL DEFAULT (now() AT TIME ZONE 'UTC'),
	text varchar(4000) NOT NULL,
	header varchar(4000),
	message varchar(4000),
	processed bigint DEFAULT 0
);

CREATE TABLE login (
	user_id bigint,
	user_name varchar(32),
	logged_in timestamp NOT NULL DEFAULT (now() AT TIME ZONE 'UTC'),
	replicate char(1) NOT NULL DEFAULT 1
);
COMMENT ON TABLE login IS E'Temporary table for storing login user information';
COMMENT ON COLUMN login.LOGGED_IN IS E'When user logged in';
COMMENT ON COLUMN login.USER_ID IS E'User identifier';
COMMENT ON COLUMN login.USER_NAME IS E'User name';

CREATE TABLE server_list (
	name varchar(100) NOT NULL,
	address varchar(100) NOT NULL,
	username varchar(100) NOT NULL,
	password varchar(100) NOT NULL,
	active char(1)
);

CREATE TABLE currentstatistics (
	statsid bigint NOT NULL,
	statsgiver varchar(50) NOT NULL,
	statstime timestamp NOT NULL,
	statsmsgtype varchar(20) NOT NULL,
	statsoutmsgcount bigint NOT NULL,
	statsinmsgcount bigint NOT NULL
);

CREATE TABLE zone_type (
	id bigint NOT NULL,
	name varchar(80) NOT NULL
);
COMMENT ON TABLE zone_type IS E'Provide textual desctiption for ZONE.TYPE id';
COMMENT ON COLUMN zone_type.ID IS E'Primaty key';
COMMENT ON COLUMN zone_type.NAME IS E'Textual description';

CREATE TABLE rpl (
	id bigint NOT NULL,
	fir_name varchar(4) NOT NULL DEFAULT 'UMMV',
	aircraft_id varchar(7) NOT NULL,
	taircraft varchar(4),
	frules varchar(1),
	tflight varchar(1),
	num smallint,
	wtc varchar(1),
	equipment varchar(222),
	adep varchar(4),
	time timestamp,
	speed varchar(5),
	flevel varchar(5),
	route varchar(4000),
	ades varchar(4),
	eet varchar(5),
	alt1 varchar(4),
	alt2 varchar(4),
	other varchar(4000),
	trtime timestamp DEFAULT (now() AT TIME ZONE 'UTC'),
	exfpl char(1),
	days char(7),
	entry_fir_eet varchar(5),
	valid_from timestamp,
	valid_to timestamp
);
COMMENT ON COLUMN rpl.ID IS E'Identifier';
COMMENT ON COLUMN rpl.ADEP IS E'Departure aerodrome';
COMMENT ON COLUMN rpl.SPEED IS E'Speed';
COMMENT ON COLUMN rpl.NUM IS E'Number of aircraft';
COMMENT ON COLUMN rpl.FRULES IS E'Flight rules';
COMMENT ON COLUMN rpl.FIR_NAME IS E'Fir name';
COMMENT ON COLUMN rpl.TRTIME IS E'Time when this record created';
COMMENT ON COLUMN rpl.EQUIPMENT IS E'Equipment';
COMMENT ON COLUMN rpl.ADES IS E'Destination aerodrome';
COMMENT ON COLUMN rpl.OTHER IS E'Other information';
COMMENT ON COLUMN rpl.AIRCRAFT_ID IS E'Aircraft identifier';
COMMENT ON COLUMN rpl.TIME IS E'The date part is the start time while rpl is valid.
The time part is the TIME schedule for FPL.';
COMMENT ON COLUMN rpl.TAIRCRAFT IS E'Aircraft type';
COMMENT ON COLUMN rpl.FLEVEL IS E'Flight level';
COMMENT ON COLUMN rpl.DAYS IS E'Mask for days of week. 1000000 means RPL is active every monday.';
COMMENT ON COLUMN rpl.WTC IS E'Turbulence';
COMMENT ON COLUMN rpl.ALT2 IS E'Second alternative destination aerodrome';
COMMENT ON COLUMN rpl.EET IS E'The date part is the time while rpl is valid. The time part is the EET schedule for FPL';
COMMENT ON COLUMN rpl.ALT1 IS E'First alternative destination aerodrome';
COMMENT ON COLUMN rpl.TFLIGHT IS E'Filght type';
COMMENT ON COLUMN rpl.ROUTE IS E'Route';

CREATE TABLE aftn_abonent_group (
	id bigint NOT NULL,
	group_id bigint NOT NULL,
	abonent_id bigint NOT NULL
);

CREATE TABLE template_arr (
	id bigint NOT NULL,
	name varchar(40) NOT NULL,
	aircraft varchar(7),
	adep varchar(4),
	ades varchar(4),
	arrival_airport varchar(4),
	arrival_time timestamp,
	arrival_airport_name varchar(100),
	other varchar(4000),
	receivers varchar(4000)
);

CREATE TABLE exercise_stand (
	id bigint NOT NULL,
	stand_id bigint NOT NULL,
	exercise_id bigint NOT NULL,
	fpl_id bigint,
	state_id bigint DEFAULT 0
);

CREATE TABLE sys_tables_info (
	tablename varchar(100) NOT NULL,
	lasttouch timestamp NOT NULL DEFAULT (now() AT TIME ZONE 'UTC'),
	replicate char(1) NOT NULL DEFAULT 1,
	sequence varchar(50)
);
COMMENT ON COLUMN sys_tables_info.LASTTOUCH IS E'Last touch timestamp';
COMMENT ON COLUMN sys_tables_info.TABLENAME IS E'Table name';

CREATE TABLE speed_types (
	name varchar(1) NOT NULL
);

CREATE TABLE airport (
	id bigint NOT NULL,
	icao varchar(5) NOT NULL,
	name varchar(5) NOT NULL,
	latitude double precision NOT NULL,
	longitude double precision NOT NULL,
	altitude double precision NOT NULL DEFAULT NULL,
	declination varchar(5)
);
COMMENT ON TABLE airport IS E'This is airport table';
COMMENT ON COLUMN airport.ID IS E'Primary key';
COMMENT ON COLUMN airport.LONGITUDE IS E'the longitude part of airport coordinates';
COMMENT ON COLUMN airport.ICAO IS E'Geographical zone code IATA';
COMMENT ON COLUMN airport.NAME IS E'ICAO name';
COMMENT ON COLUMN airport.ALTITUDE IS E'the altitude part of airport coordinates';
COMMENT ON COLUMN airport.LATITUDE IS E'the latitude part of airport coordinates';

CREATE TABLE restriction_point_user (
	id bigint NOT NULL,
	sn bigint NOT NULL,
	type bigint NOT NULL,
	latitude double precision NOT NULL,
	longitude double precision NOT NULL,
	arc_latitude double precision NOT NULL,
	arc_longitude double precision NOT NULL,
	arc_distance double precision NOT NULL,
	restriction_id bigint NOT NULL
);

CREATE TABLE modification_types (
	type char(1) NOT NULL
);
COMMENT ON TABLE modification_types IS E'Type of row modification';
COMMENT ON COLUMN modification_types.TYPE IS E'Type of modification';
