connect sys/sys as sysdba;

DROP USER aero CASCADE;

CREATE USER aero IDENTIFIED BY aero DEFAULT TABLESPACE users TEMPORARY TABLESPACE temp ACCOUNT UNLOCK;
GRANT DBA,CONNECT,RESOURCE TO aero;
ALTER USER aero DEFAULT ROLE ALL;

exit

