
  CREATE TABLE "AERO"."POINT_M" 
   (	"ID" NUMBER(10,0) NOT NULL ENABLE, 
	"TYPE" NUMBER(10,0) NOT NULL ENABLE, 
	"NAME" VARCHAR2(10 CHAR) NOT NULL ENABLE, 
	"LATITUDE" FLOAT(126) NOT NULL ENABLE, 
	"LONGITUDE" FLOAT(126) NOT NULL ENABLE, 
	"ICAO" VARCHAR2(5 CHAR), 
	"AIRPORT" VARCHAR2(5 CHAR), 
	 CONSTRAINT "POINT_M_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FK_POINT_TYPE_M_ID" FOREIGN KEY ("TYPE")
	  REFERENCES "AERO"."POINT_TYPE_M" ("ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "AERO"."POINT_M"."ID" IS 'Primary key';
 
   COMMENT ON COLUMN "AERO"."POINT_M"."TYPE" IS 'Type of the point. For textual description see POINT_TYPE table';
 
   COMMENT ON COLUMN "AERO"."POINT_M"."NAME" IS 'The short name (as usual less then 7 letters) of the point.';
 
   COMMENT ON COLUMN "AERO"."POINT_M"."LATITUDE" IS 'The latitude part of the coordinates';
 
   COMMENT ON COLUMN "AERO"."POINT_M"."LONGITUDE" IS 'The longitude part of the coordinates';
 
   COMMENT ON COLUMN "AERO"."POINT_M"."ICAO" IS 'The ICAO index';
 
   COMMENT ON COLUMN "AERO"."POINT_M"."AIRPORT" IS 'I pretty dont know what is this =(';
 
   COMMENT ON TABLE "AERO"."POINT_M"  IS 'Monument point. It could belong to zone.';
 

  CREATE OR REPLACE TRIGGER "AERO"."POINT_M_AC2" 
  BEFORE INSERT OR UPDATE OR DELETE ON POINT_M FOR EACH ROW
DECLARE
  ac_flag NUMBER;
  rec_exist NUMBER;

BEGIN
  ac_flag := sys_context('CLIENTCONTEXT', 'ARINC_CHANGES_FLAG');
  IF ac_flag = 777 THEN
    --DELETE
    IF DELETING THEN
      null;
    --INSERT or UPDATE
    ELSE
      SELECT COUNT(*) INTO rec_exist FROM POINT_TYPE_M WHERE id = :new.type;
      IF rec_exist = 0 THEN
        INSERT INTO POINT_TYPE_M (SELECT * FROM POINT_TYPE WHERE id = :new.type);
      END IF;
    END IF;
  END IF;
END;
/
ALTER TRIGGER "AERO"."POINT_M_AC2" ENABLE;
 
