CREATE TABLE AIRPORT_M 
(
  ID NUMBER(10, 0) NOT NULL 
, ICAO VARCHAR2(5 CHAR) NOT NULL 
, NAME VARCHAR2(5 CHAR) NOT NULL 
, LATITUDE FLOAT(126) NOT NULL 
, LONGITUDE FLOAT(126) NOT NULL 
, ALTITUDE FLOAT(126) NOT NULL 
, CONSTRAINT TABLE1_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

COMMENT ON TABLE AIRPORT_M IS 'This is airport table';

COMMENT ON COLUMN AIRPORT_M.ID IS 'Primary key';

COMMENT ON COLUMN AIRPORT_M.ICAO IS 'Geographical zone code IATA';

COMMENT ON COLUMN AIRPORT_M.NAME IS 'ICAO name';

COMMENT ON COLUMN AIRPORT_M.LATITUDE IS 'the latitude part of airport coordinates';

COMMENT ON COLUMN AIRPORT_M.LONGITUDE IS 'the longitude part of airport coordinates';

COMMENT ON COLUMN AIRPORT_M.ALTITUDE IS 'the altitude part of airport coordinates';
