
  CREATE TABLE "OLDI_SFPL" 
   (	"AIRCRAFT_ID" VARCHAR2(7 CHAR) NOT NULL ENABLE, 
	"ADEP" VARCHAR2(4 CHAR) NOT NULL ENABLE, 
	"ADES" VARCHAR2(4 CHAR) NOT NULL ENABLE, 
	"RECIEVER" VARCHAR2(100 CHAR) NOT NULL ENABLE, 
	 CONSTRAINT "SENDED_SFPL_PK" PRIMARY KEY ("AIRCRAFT_ID", "ADEP", "ADES", "RECIEVER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "OLDI_SFPL"."AIRCRAFT_ID" IS 'Aircraft identificator';
 
   COMMENT ON COLUMN "OLDI_SFPL"."ADEP" IS 'Departure aerodrome';
 
   COMMENT ON COLUMN "OLDI_SFPL"."ADES" IS 'Destination aerodrome';
 
