get_filename_component(groundscene_CURRENTDIR ${CMAKE_CURRENT_LIST_FILE} PATH)

include_directories("${groundscene_CURRENTDIR}/src")

list(APPEND SOURCES "${groundscene_CURRENTDIR}/src/back/ground/GroundSceneLogic.cpp"
    "${groundscene_CURRENTDIR}/src/back/ground/GroundScene.cpp"
    "${groundscene_CURRENTDIR}/src/front/ground/GUIGroundTrace.cpp"
    "${groundscene_CURRENTDIR}/src/front/ground/GUIGroundTower.cpp"
    "${groundscene_CURRENTDIR}/src/front/ground/GUIGroundStart.cpp"
    "${groundscene_CURRENTDIR}/src/front/ground/GUIGroundSign.cpp"
    "${groundscene_CURRENTDIR}/src/front/ground/GUIGroundScene.cpp"
    "${groundscene_CURRENTDIR}/src/front/ground/GUIGroundRunway.cpp"
    "${groundscene_CURRENTDIR}/src/front/ground/GUIGroundPoint.cpp"
    "${groundscene_CURRENTDIR}/src/front/ground/GUIGroundPath.cpp"
    "${groundscene_CURRENTDIR}/src/front/ground/GUIGroundParking.cpp"
    "${groundscene_CURRENTDIR}/src/front/ground/GUIGroundCrossrads.cpp"
    "${groundscene_CURRENTDIR}/src/front/ground/GUIGroundBuilding.cpp"
    "${groundscene_CURRENTDIR}/src/front/ground/GUIGroundApron.cpp"
    "${groundscene_CURRENTDIR}/src/front/ground/GUIGroundRadioRestriction.cpp"
    "${groundscene_CURRENTDIR}/src/back/ground/GroundVehicle.cpp"
    "${groundscene_CURRENTDIR}/src/front/ground/GUIGroundVehicle.cpp"
    "${groundscene_CURRENTDIR}/src/front/ground/GUIGroundVehiclePoint.cpp"
    "${groundscene_CURRENTDIR}/src/front/ground/GUIGroundVehicleLabel.cpp"
    "${groundscene_CURRENTDIR}/src/front/ground/GUIGroundWaypointMarker.cpp"
    "${groundscene_CURRENTDIR}/src/back/ground/WaypointManager.cpp"
    "${groundscene_CURRENTDIR}/src/front/ground/GUIWaypointManager.cpp"
)

list(APPEND HEADERS "${groundscene_CURRENTDIR}/src/back/ground/GroundTrace.h"
    "${groundscene_CURRENTDIR}/src/back/ground/GroundTower.h"
    "${groundscene_CURRENTDIR}/src/back/ground/GroundStart.h"
    "${groundscene_CURRENTDIR}/src/back/ground/GroundSign.h"
    "${groundscene_CURRENTDIR}/src/back/ground/GroundSceneLogic.h"    
    "${groundscene_CURRENTDIR}/src/back/ground/GroundRunway.h"
    "${groundscene_CURRENTDIR}/src/back/ground/GroundPoint.h"
    "${groundscene_CURRENTDIR}/src/back/ground/GroundPath.h"
    "${groundscene_CURRENTDIR}/src/back/ground/GroundParking.h"
    "${groundscene_CURRENTDIR}/src/back/ground/GroundCrossroads.h"
    "${groundscene_CURRENTDIR}/src/back/ground/GroundBuilding.h"
    "${groundscene_CURRENTDIR}/src/back/ground/GroundApron.h"    
    "${groundscene_CURRENTDIR}/src/back/ground/GroundCoordinate.h"
    "${groundscene_CURRENTDIR}/src/back/ground/GroundMain.h"
    "${groundscene_CURRENTDIR}/src/back/ground/GroundTVATimer.h"
    "${groundscene_CURRENTDIR}/src/back/ground/GroundCoordsDigitizer.h"
    "${groundscene_CURRENTDIR}/src/back/ground/GroundStand.h"
    "${groundscene_CURRENTDIR}/src/back/ground/GroundRadioRestriction.h"
    "${groundscene_CURRENTDIR}/src/front/ground/GUIGroundTrace.h"
    "${groundscene_CURRENTDIR}/src/front/ground/GUIGroundTower.h"
    "${groundscene_CURRENTDIR}/src/front/ground/GUIGroundStart.h"
    "${groundscene_CURRENTDIR}/src/front/ground/GUIGroundSign.h"
    "${groundscene_CURRENTDIR}/src/front/ground/GUIGroundRunway.h"
    "${groundscene_CURRENTDIR}/src/front/ground/GUIGroundPath.h"
    "${groundscene_CURRENTDIR}/src/front/ground/GUIGroundCrossrads.h"
    "${groundscene_CURRENTDIR}/src/front/ground/GUIGroundBuilding.h"
    "${groundscene_CURRENTDIR}/src/front/ground/GUIGroundApron.h"
    "${groundscene_CURRENTDIR}/src/front/ground/GUIGroundRadioRestriction.h"
    "${groundscene_CURRENTDIR}/src/front/ground/GUIGroundVehiclePoint.h"
    "${groundscene_CURRENTDIR}/src/back/ground/GroundWaypointMarker.h"
    "${groundscene_CURRENTDIR}/src/back/ground/WaypointManager.h"
)

list(APPEND Q_HEADERS "${groundscene_CURRENTDIR}/src/back/ground/GroundScene.h"
    "${groundscene_CURRENTDIR}/src/front/ground/GUIGroundScene.h"
    "${groundscene_CURRENTDIR}/src/front/ground/GUIGroundParking.h"
    "${groundscene_CURRENTDIR}/src/front/ground/GUIGroundPoint.h"
    "${groundscene_CURRENTDIR}/src/back/ground/GroundVehicle.h"
    "${groundscene_CURRENTDIR}/src/front/ground/GUIGroundVehicle.h"
    "${groundscene_CURRENTDIR}/src/front/ground/GUIGroundVehicleLabel.h"
    "${groundscene_CURRENTDIR}/src/front/ground/GUIGroundWaypointMarker.h"
    "${groundscene_CURRENTDIR}/src/front/ground/GUIWaypointManager.h"
)
