
  CREATE TABLE "OUTPUTTELEGRAMS" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"CREATED" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL ENABLE, 
	"TEXT" VARCHAR2(4000 BYTE) NOT NULL ENABLE, 
	"HEADER" VARCHAR2(4000 BYTE), 
	"MESSAGE" VARCHAR2(4000 BYTE), 
	 CONSTRAINT "OUTPUTTELEGRAMS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "OUTPUTTELEGRAMS"."ID" IS 'identifier';
 
   COMMENT ON COLUMN "OUTPUTTELEGRAMS"."CREATED" IS 'UTC timestamp of inserting message';
 
   COMMENT ON COLUMN "OUTPUTTELEGRAMS"."TEXT" IS 'AFTN message text';
 
   COMMENT ON COLUMN "OUTPUTTELEGRAMS"."HEADER" IS 'AFTN message header';
 
   COMMENT ON COLUMN "OUTPUTTELEGRAMS"."MESSAGE" IS 'AFTN message';
 
   COMMENT ON TABLE "OUTPUTTELEGRAMS"  IS 'AFTN messages(telegrams)';
 

  CREATE SEQUENCE  "OUTPUTTELEGRAMS_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
 

  CREATE OR REPLACE TRIGGER "OUTPUTTELEGRAMS_TRG" BEFORE INSERT ON OUTPUTTELEGRAMS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    SELECT OUTPUTTELEGRAMS_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "OUTPUTTELEGRAMS_TRG" ENABLE;
 
