-- Generated by Ora2Pg, the Oracle database Schema converter, version 13.0
-- Copyright 2000-2014 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.20.1.81;sid=XE

SET client_encoding TO 'UTF8';

SET search_path = aero, pg_catalog;\set ON_ERROR_STOP ON

SET search_path = aero, pg_catalog;
INSERT INTO activation (acid,code,first_point,start_time,echelon,sector) VALUES (E'ABANI33',E'1604',E'NABAT','2014-06-24 12:43:40',9144,NULL);
INSERT INTO activation (acid,code,first_point,start_time,echelon,sector) VALUES (E'ABANI11',E'1603',E'ABANI','2014-06-24 12:43:38',9144,NULL);
