-- Generated by Ora2Pg, the Oracle database Schema converter, version 13.0
-- Copyright 2000-2014 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.20.1.81;sid=XE

SET client_encoding TO 'UTF8';

SET search_path = aero, pg_catalog;\set ON_ERROR_STOP ON

SET search_path = aero, pg_catalog;
INSERT INTO aftn_group (id,name) VALUES (21,E'G3');
INSERT INTO aftn_group (id,name) VALUES (6,E'G2');
INSERT INTO aftn_group (id,name) VALUES (7,E'G1');
