-- Generated by Ora2Pg, the Oracle database Schema converter, version 13.0
-- Copyright 2000-2014 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.20.1.81;sid=XE

SET client_encoding TO 'UTF8';

SET search_path = aero, pg_catalog;\set ON_ERROR_STOP ON

SET search_path = aero, pg_catalog;
INSERT INTO aftn_abonent_group (id,group_id,abonent_id) VALUES (26,7,6);
INSERT INTO aftn_abonent_group (id,group_id,abonent_id) VALUES (34,7,7);
INSERT INTO aftn_abonent_group (id,group_id,abonent_id) VALUES (25,7,5);
INSERT INTO aftn_abonent_group (id,group_id,abonent_id) VALUES (31,21,5);
INSERT INTO aftn_abonent_group (id,group_id,abonent_id) VALUES (32,21,6);
INSERT INTO aftn_abonent_group (id,group_id,abonent_id) VALUES (33,21,7);
