-- Generated by Ora2Pg, the Oracle database Schema converter, version 13.0
-- Copyright 2000-2014 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.20.1.81;sid=XE

SET client_encoding TO 'UTF8';

SET search_path = aero, pg_catalog;\set ON_ERROR_STOP ON

SET search_path = aero, pg_catalog;
INSERT INTO airport (id,icao,name,latitude,longitude,altitude,declination) VALUES (304,E'UT',E'UTFA',40.7266666666667,72.2933333333333,475.1832,NULL);
INSERT INTO airport (id,icao,name,latitude,longitude,altitude,declination) VALUES (305,E'UT',E'UTFF',40.3583333333333,71.745,625.4496,NULL);
INSERT INTO airport (id,icao,name,latitude,longitude,altitude,declination) VALUES (306,E'UT',E'UTFN',40.985,71.5583333333333,519.0744,NULL);
INSERT INTO airport (id,icao,name,latitude,longitude,altitude,declination) VALUES (307,E'UT',E'UTTP',41.3116666666667,69.3916666666667,479.4504,NULL);
INSERT INTO airport (id,icao,name,latitude,longitude,altitude,declination) VALUES (308,E'UT',E'UTTT',41.2583333333333,69.2816666666667,431.5968,NULL);
INSERT INTO airport (id,icao,name,latitude,longitude,altitude,declination) VALUES (309,E'UM',E'UMBB',52.1082555555556,23.8962666666667,142.6464,NULL);
INSERT INTO airport (id,icao,name,latitude,longitude,altitude,declination) VALUES (310,E'UM',E'UMGG',52.5270388888889,31.0167027777778,143.5608,NULL);
INSERT INTO airport (id,icao,name,latitude,longitude,altitude,declination) VALUES (311,E'UM',E'UMII',55.1263055555556,30.3496638888889,207.8736,NULL);
INSERT INTO airport (id,icao,name,latitude,longitude,altitude,declination) VALUES (312,E'UM',E'UMMG',53.6019666666667,24.0537777777778,135.0264,NULL);
INSERT INTO airport (id,icao,name,latitude,longitude,altitude,declination) VALUES (313,E'UM',E'UMMM',53.8643972222222,27.539975,228.2952,NULL);
INSERT INTO airport (id,icao,name,latitude,longitude,altitude,declination) VALUES (314,E'UM',E'UMMS',53.8824638888889,28.0307222222222,204.216,NULL);
INSERT INTO airport (id,icao,name,latitude,longitude,altitude,declination) VALUES (315,E'UM',E'UMOO',53.9554055555556,30.0942916666667,193.8528,NULL);
INSERT INTO airport (id,icao,name,latitude,longitude,altitude,declination) VALUES (352,E'UA',E'UAOO',44.7061111111111,65.5916666666667,131.9784,NULL);
INSERT INTO airport (id,icao,name,latitude,longitude,altitude,declination) VALUES (324,E'UR',E'УРВА',46.2833333333333,48.0063888888889,-19.812,NULL);
INSERT INTO airport (id,icao,name,latitude,longitude,altitude,declination) VALUES (325,E'UR',E'УРВВ',48.7833333333333,44.345,146.9136,NULL);
INSERT INTO airport (id,icao,name,latitude,longitude,altitude,declination) VALUES (326,E'UR',E'УРВИ',46.3733333333333,44.3316666666667,152.7048,NULL);
INSERT INTO airport (id,icao,name,latitude,longitude,altitude,declination) VALUES (327,E'UR',E'УРКА',45.0016666666667,37.3483333333333,53.0352,NULL);
INSERT INTO airport (id,icao,name,latitude,longitude,altitude,declination) VALUES (328,E'UR',E'УРКГ',44.5816666666667,38.0133333333333,40.2336,NULL);
INSERT INTO airport (id,icao,name,latitude,longitude,altitude,declination) VALUES (329,E'UR',E'УРКЕ',46.6788888888889,38.2122222222222,20.1168,NULL);
INSERT INTO airport (id,icao,name,latitude,longitude,altitude,declination) VALUES (330,E'UR',E'УРКК',45.035,39.17,35.9664,NULL);
INSERT INTO airport (id,icao,name,latitude,longitude,altitude,declination) VALUES (331,E'UR',E'УРКН',44.5666666666667,38.0416666666667,0,NULL);
INSERT INTO airport (id,icao,name,latitude,longitude,altitude,declination) VALUES (332,E'UR',E'УРМГ',43.3883333333333,45.7,165.8112,NULL);
INSERT INTO airport (id,icao,name,latitude,longitude,altitude,declination) VALUES (333,E'UR',E'УРМЛ',42.8166666666667,47.6533333333333,4.572,NULL);
INSERT INTO airport (id,icao,name,latitude,longitude,altitude,declination) VALUES (334,E'UR',E'УРММ',44.225,43.0833333333333,321.2592,NULL);
INSERT INTO airport (id,icao,name,latitude,longitude,altitude,declination) VALUES (335,E'UR',E'УРМН',43.5133333333333,43.6366666666667,445.9224,NULL);
INSERT INTO airport (id,icao,name,latitude,longitude,altitude,declination) VALUES (336,E'UR',E'УРМО',43.205,44.6083333333333,509.9304,NULL);
INSERT INTO airport (id,icao,name,latitude,longitude,altitude,declination) VALUES (337,E'UR',E'УРМС',43.3233333333333,45.0133333333333,367.8936,NULL);
INSERT INTO airport (id,icao,name,latitude,longitude,altitude,declination) VALUES (338,E'UR',E'УРМТ',45.1083333333333,42.1133333333333,452.9328,NULL);
INSERT INTO airport (id,icao,name,latitude,longitude,altitude,declination) VALUES (339,E'UR',E'УРРР',47.2583333333333,39.8180555555556,85.344,NULL);
INSERT INTO airport (id,icao,name,latitude,longitude,altitude,declination) VALUES (340,E'UR',E'УРРТ',47.1983333333333,38.8491666666667,27.1272,NULL);
INSERT INTO airport (id,icao,name,latitude,longitude,altitude,declination) VALUES (341,E'UR',E'УРСС',43.445,39.9483333333333,27.1272,NULL);
INSERT INTO airport (id,icao,name,latitude,longitude,altitude,declination) VALUES (351,E'UA',E'UAII',42.365,69.4761111111111,422.148,NULL);
INSERT INTO airport (id,icao,name,latitude,longitude,altitude,declination) VALUES (355,E'UA',E'UAFO',40.6083333333333,72.7933333333333,892.4544,NULL);
INSERT INTO airport (id,icao,name,latitude,longitude,altitude,declination) VALUES (354,E'UT',E'UTNU',41.5833333333333,60.645,97.536,NULL);
INSERT INTO airport (id,icao,name,latitude,longitude,altitude,declination) VALUES (356,E'UT',E'UTDD',38.5433333333333,68.825,784.5552,E'E0070');
INSERT INTO airport (id,icao,name,latitude,longitude,altitude,declination) VALUES (357,E'UT',E'UTDK',37.9880555555556,69.8063888888889,699.516,E'E0055');
INSERT INTO airport (id,icao,name,latitude,longitude,altitude,declination) VALUES (358,E'UT',E'UTDT',37.8666666666667,68.865,448.6656,E'E0058');
INSERT INTO airport (id,icao,name,latitude,longitude,altitude,declination) VALUES (344,E'UT',E'UTDP',37.62,67.5183333333333,379.476,NULL);
INSERT INTO airport (id,icao,name,latitude,longitude,altitude,declination) VALUES (345,E'UT',E'UTSA',40.1166666666667,65.1716666666667,347.472,NULL);
INSERT INTO airport (id,icao,name,latitude,longitude,altitude,declination) VALUES (346,E'UT',E'UTSB',39.775,64.4833333333333,228.9048,NULL);
INSERT INTO airport (id,icao,name,latitude,longitude,altitude,declination) VALUES (347,E'UT',E'UTSK',38.8033333333333,65.7733333333333,374.5992,NULL);
INSERT INTO airport (id,icao,name,latitude,longitude,altitude,declination) VALUES (348,E'UT',E'UTSL',38.8333333333333,65.9216666666667,398.0688,NULL);
INSERT INTO airport (id,icao,name,latitude,longitude,altitude,declination) VALUES (349,E'UT',E'UTSS',39.7,66.985,678.18,NULL);
INSERT INTO airport (id,icao,name,latitude,longitude,altitude,declination) VALUES (350,E'UT',E'UTST',37.2866666666667,67.31,313.6392,NULL);
INSERT INTO airport (id,icao,name,latitude,longitude,altitude,declination) VALUES (353,E'UT',E'UTNN',42.4883333333333,59.6233333333333,75.8952,NULL);
INSERT INTO airport (id,icao,name,latitude,longitude,altitude,declination) VALUES (424,E'UM',E'QQQQ',1.18333333333333,1.16666666666667,1,NULL);
INSERT INTO airport (id,icao,name,latitude,longitude,altitude,declination) VALUES (444,E'UT',E'UTDL',40.215,69.6966666666667,441.96,E'E0067');
