-- Generated by Ora2Pg, the Oracle database Schema converter, version 13.0
-- Copyright 2000-2014 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.20.1.81;sid=XE

SET client_encoding TO 'UTF8';

SET search_path = aero, pg_catalog;\set ON_ERROR_STOP ON

SET search_path = aero, pg_catalog;
INSERT INTO airplane_speed (id,flevel,v_climb,v_climb_max,v_descend,v_descend_max,ias,ias_min,ias_max,airplane_id) VALUES (1021,1,1,1,1,1,1,1,1,E'A111');
INSERT INTO airplane_speed (id,flevel,v_climb,v_climb_max,v_descend,v_descend_max,ias,ias_min,ias_max,airplane_id) VALUES (1022,2,2,2,2,2,2,2,2,E'A111');
INSERT INTO airplane_speed (id,flevel,v_climb,v_climb_max,v_descend,v_descend_max,ias,ias_min,ias_max,airplane_id) VALUES (918,1640.5,34,40,10,25,100,80,120,E'A320');
INSERT INTO airplane_speed (id,flevel,v_climb,v_climb_max,v_descend,v_descend_max,ias,ias_min,ias_max,airplane_id) VALUES (919,4921.5,23,35,20,30,110,100,130,E'A320');
INSERT INTO airplane_speed (id,flevel,v_climb,v_climb_max,v_descend,v_descend_max,ias,ias_min,ias_max,airplane_id) VALUES (920,15000,10,20,20,30,130,80,150,E'A320');
INSERT INTO airplane_speed (id,flevel,v_climb,v_climb_max,v_descend,v_descend_max,ias,ias_min,ias_max,airplane_id) VALUES (921,1500,10,41,11,31,90,70,110,E'T154');
INSERT INTO airplane_speed (id,flevel,v_climb,v_climb_max,v_descend,v_descend_max,ias,ias_min,ias_max,airplane_id) VALUES (922,5000,20,36,21,31,100,90,120,E'T154');
INSERT INTO airplane_speed (id,flevel,v_climb,v_climb_max,v_descend,v_descend_max,ias,ias_min,ias_max,airplane_id) VALUES (923,15000,25,45,26,44,120,70,140,E'T154');
INSERT INTO airplane_speed (id,flevel,v_climb,v_climb_max,v_descend,v_descend_max,ias,ias_min,ias_max,airplane_id) VALUES (1014,4575,8,10,15,21,125,100,140,E'IL76');
INSERT INTO airplane_speed (id,flevel,v_climb,v_climb_max,v_descend,v_descend_max,ias,ias_min,ias_max,airplane_id) VALUES (1015,7620,5,10,15,20,125,100,140,E'IL76');
INSERT INTO airplane_speed (id,flevel,v_climb,v_climb_max,v_descend,v_descend_max,ias,ias_min,ias_max,airplane_id) VALUES (1016,12000,5,10,8,10,120,110,130,E'IL76');
INSERT INTO airplane_speed (id,flevel,v_climb,v_climb_max,v_descend,v_descend_max,ias,ias_min,ias_max,airplane_id) VALUES (935,7500,15,35,20,30,130,80,150,E'A320');
INSERT INTO airplane_speed (id,flevel,v_climb,v_climb_max,v_descend,v_descend_max,ias,ias_min,ias_max,airplane_id) VALUES (936,7500,15,36,16,31,120,70,140,E'T154');
INSERT INTO airplane_speed (id,flevel,v_climb,v_climb_max,v_descend,v_descend_max,ias,ias_min,ias_max,airplane_id) VALUES (1017,1525,30,35,15,20,85,80,120,E'B737');
INSERT INTO airplane_speed (id,flevel,v_climb,v_climb_max,v_descend,v_descend_max,ias,ias_min,ias_max,airplane_id) VALUES (939,1640.5,10,20,10,20,75,50,110,E'AN24');
INSERT INTO airplane_speed (id,flevel,v_climb,v_climb_max,v_descend,v_descend_max,ias,ias_min,ias_max,airplane_id) VALUES (940,4921.5,5,20,5,20,100,50,120,E'AN24');
INSERT INTO airplane_speed (id,flevel,v_climb,v_climb_max,v_descend,v_descend_max,ias,ias_min,ias_max,airplane_id) VALUES (941,7500,10,20,10,20,100,50,120,E'AN24');
INSERT INTO airplane_speed (id,flevel,v_climb,v_climb_max,v_descend,v_descend_max,ias,ias_min,ias_max,airplane_id) VALUES (942,1640.5,15,30,20,30,100,80,150,E'CRJ2');
INSERT INTO airplane_speed (id,flevel,v_climb,v_climb_max,v_descend,v_descend_max,ias,ias_min,ias_max,airplane_id) VALUES (943,4921.5,10,25,15,25,125,80,150,E'CRJ2');
INSERT INTO airplane_speed (id,flevel,v_climb,v_climb_max,v_descend,v_descend_max,ias,ias_min,ias_max,airplane_id) VALUES (944,7500,7,15,15,25,120,80,150,E'CRJ2');
INSERT INTO airplane_speed (id,flevel,v_climb,v_climb_max,v_descend,v_descend_max,ias,ias_min,ias_max,airplane_id) VALUES (945,15000,7,15,15,25,120,80,150,E'CRJ2');
INSERT INTO airplane_speed (id,flevel,v_climb,v_climb_max,v_descend,v_descend_max,ias,ias_min,ias_max,airplane_id) VALUES (1013,1525,10,15,15,20,75,70,100,E'IL76');
INSERT INTO airplane_speed (id,flevel,v_climb,v_climb_max,v_descend,v_descend_max,ias,ias_min,ias_max,airplane_id) VALUES (1018,4575,20,25,35,40,145,105,160,E'B737');
INSERT INTO airplane_speed (id,flevel,v_climb,v_climb_max,v_descend,v_descend_max,ias,ias_min,ias_max,airplane_id) VALUES (1019,7620,20,25,35,40,145,105,160,E'B737');
INSERT INTO airplane_speed (id,flevel,v_climb,v_climb_max,v_descend,v_descend_max,ias,ias_min,ias_max,airplane_id) VALUES (1020,12500,15,20,8,10,120,115,125,E'B737');
INSERT INTO airplane_speed (id,flevel,v_climb,v_climb_max,v_descend,v_descend_max,ias,ias_min,ias_max,airplane_id) VALUES (953,1500,10,20,11,22,100,80,130,E'T134');
INSERT INTO airplane_speed (id,flevel,v_climb,v_climb_max,v_descend,v_descend_max,ias,ias_min,ias_max,airplane_id) VALUES (954,5000,14,25,12,23,100,80,100,E'T134');
INSERT INTO airplane_speed (id,flevel,v_climb,v_climb_max,v_descend,v_descend_max,ias,ias_min,ias_max,airplane_id) VALUES (955,7500,15,22,13,24,100,80,130,E'T134');
INSERT INTO airplane_speed (id,flevel,v_climb,v_climb_max,v_descend,v_descend_max,ias,ias_min,ias_max,airplane_id) VALUES (956,15000,16,23,14,24,100,80,140,E'T134');
INSERT INTO airplane_speed (id,flevel,v_climb,v_climb_max,v_descend,v_descend_max,ias,ias_min,ias_max,airplane_id) VALUES (974,3,3,3,3,4,3,2,2,E'T154');
