-- Generated by Ora2Pg, the Oracle database Schema converter, version 13.0
-- Copyright 2000-2014 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.20.1.81;sid=XE

SET client_encoding TO 'UTF8';

SET search_path = aero, pg_catalog;\set ON_ERROR_STOP ON

SET search_path = aero, pg_catalog;
INSERT INTO bearing_point (id,name,fir_name,rdf_latitude,rdf_longitude,sac,sic,channel) VALUES (41,NULL,E'UTDD',30,50,1,1,NULL);
INSERT INTO bearing_point (id,name,fir_name,rdf_latitude,rdf_longitude,sac,sic,channel) VALUES (42,NULL,E'UMMV',53,28,2,2,NULL);
INSERT INTO bearing_point (id,name,fir_name,rdf_latitude,rdf_longitude,sac,sic,channel) VALUES (43,E'Ташкент',E'UTTR',41.26,69.2916666666667,3,3,NULL);
