-- Generated by Ora2Pg, the Oracle database Schema converter, version 13.0
-- Copyright 2000-2014 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.20.1.81;sid=XE

SET client_encoding TO 'UTF8';

SET search_path = aero, pg_catalog;\set ON_ERROR_STOP ON

SET search_path = aero, pg_catalog;
INSERT INTO boundary_point_type (id,name) VALUES (71,E'Line');
INSERT INTO boundary_point_type (id,name) VALUES (67,E'Circle');
INSERT INTO boundary_point_type (id,name) VALUES (76,E'LeftArc');
INSERT INTO boundary_point_type (id,name) VALUES (82,E'RightArc');
