-- Generated by Ora2Pg, the Oracle database Schema converter, version 13.0
-- Copyright 2000-2014 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.20.1.81;sid=XE

SET client_encoding TO 'UTF8';

SET search_path = aero, pg_catalog;\set ON_ERROR_STOP ON

SET search_path = aero, pg_catalog;
INSERT INTO client (id,name,password,role_id,full_name) VALUES (64,E'User2',NULL,61,E'USER 2');
INSERT INTO client (id,name,password,role_id,full_name) VALUES (65,E'XMaster',NULL,1,E'ADMIN');
