-- Generated by Ora2Pg, the Oracle database Schema converter, version 13.0
-- Copyright 2000-2014 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.20.1.81;sid=XE

SET client_encoding TO 'UTF8';

SET search_path = aero, pg_catalog;\set ON_ERROR_STOP ON

SET search_path = aero, pg_catalog;
INSERT INTO client_sectoring (id,client_role_id,sectoring_id) VALUES (451,1,302);
INSERT INTO client_sectoring (id,client_role_id,sectoring_id) VALUES (452,1,283);
INSERT INTO client_sectoring (id,client_role_id,sectoring_id) VALUES (453,1,284);
