-- Generated by Ora2Pg, the Oracle database Schema converter, version 13.0
-- Copyright 2000-2014 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.20.1.81;sid=XE

SET client_encoding TO 'UTF8';

SET search_path = aero, pg_catalog;\set ON_ERROR_STOP ON

SET search_path = aero, pg_catalog;
INSERT INTO currentstatus (statusid,statusgiver,statustime,statuscode) VALUES (1246,E'FDP','2013-09-19 17:24:23.000000',5);
INSERT INTO currentstatus (statusid,statusgiver,statustime,statuscode) VALUES (1248,E'CWPA','2013-08-05 17:51:42.000000',0);
INSERT INTO currentstatus (statusid,statusgiver,statustime,statuscode) VALUES (1249,E'CWPB','2013-02-15 13:11:25.000000',-1);
INSERT INTO currentstatus (statusid,statusgiver,statustime,statuscode) VALUES (1247,E'CWPD','2011-07-19 17:30:56.705400',0);
INSERT INTO currentstatus (statusid,statusgiver,statustime,statuscode) VALUES (1250,E'CWPC','2011-11-04 18:06:42.138800',5);
INSERT INTO currentstatus (statusid,statusgiver,statustime,statuscode) VALUES (1251,E'E','2011-10-21 17:59:14.530790',-1);
INSERT INTO currentstatus (statusid,statusgiver,statustime,statuscode) VALUES (1252,E'FDPR','2011-08-17 13:35:18.980375',-1);
INSERT INTO currentstatus (statusid,statusgiver,statustime,statuscode) VALUES (1253,E'PSA','2013-07-19 15:36:08.000000',0);
INSERT INTO currentstatus (statusid,statusgiver,statustime,statuscode) VALUES (1254,E'DHB','2013-04-04 13:02:33.000000',5);
