-- Generated by Ora2Pg, the Oracle database Schema converter, version 13.0
-- Copyright 2000-2014 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.20.1.81;sid=XE

SET client_encoding TO 'UTF8';

SET search_path = aero, pg_catalog;\set ON_ERROR_STOP ON

SET search_path = aero, pg_catalog;
INSERT INTO currentstatistics (statsid,statsgiver,statstime,statsmsgtype,statsoutmsgcount,statsinmsgcount) VALUES (99,E'PSA','2013-07-19 15:36:07.000000',E'MSG',0,0);
INSERT INTO currentstatistics (statsid,statsgiver,statstime,statsmsgtype,statsoutmsgcount,statsinmsgcount) VALUES (97,E'FDP','2013-09-19 00:00:00.000000',E'COD',0,0);
INSERT INTO currentstatistics (statsid,statsgiver,statstime,statsmsgtype,statsoutmsgcount,statsinmsgcount) VALUES (58,E'FDP','2013-09-19 00:00:00.000000',E'STS',12,12);
INSERT INTO currentstatistics (statsid,statsgiver,statstime,statsmsgtype,statsoutmsgcount,statsinmsgcount) VALUES (59,E'FDP','2013-09-19 00:00:00.000000',E'LAM',45,18);
INSERT INTO currentstatistics (statsid,statsgiver,statstime,statsmsgtype,statsoutmsgcount,statsinmsgcount) VALUES (66,E'CWPC','2011-11-02 10:04:00.000000',E'ERR',0,0);
INSERT INTO currentstatistics (statsid,statsgiver,statstime,statsmsgtype,statsoutmsgcount,statsinmsgcount) VALUES (69,E'CWPC','2011-11-02 10:04:00.000000',E'INF',7,6);
INSERT INTO currentstatistics (statsid,statsgiver,statstime,statsmsgtype,statsoutmsgcount,statsinmsgcount) VALUES (71,E'CWPA','2011-11-02 10:04:02.000000',E'COD',0,0);
INSERT INTO currentstatistics (statsid,statsgiver,statstime,statsmsgtype,statsoutmsgcount,statsinmsgcount) VALUES (60,E'CWPA','2011-11-02 10:04:02.000000',E'STS',370,377);
INSERT INTO currentstatistics (statsid,statsgiver,statstime,statsmsgtype,statsoutmsgcount,statsinmsgcount) VALUES (75,E'CWPC','2011-11-02 10:04:00.000000',E'FPL',0,9);
INSERT INTO currentstatistics (statsid,statsgiver,statstime,statsmsgtype,statsoutmsgcount,statsinmsgcount) VALUES (63,E'CWPD','2011-05-26 19:13:53.000000',E'STS',188,39);
INSERT INTO currentstatistics (statsid,statsgiver,statstime,statsmsgtype,statsoutmsgcount,statsinmsgcount) VALUES (76,E'CWPA','2011-11-02 10:04:02.000000',E'FPL',232,5);
INSERT INTO currentstatistics (statsid,statsgiver,statstime,statsmsgtype,statsoutmsgcount,statsinmsgcount) VALUES (61,E'CWPC','2011-11-02 10:04:00.000000',E'STS',0,0);
INSERT INTO currentstatistics (statsid,statsgiver,statstime,statsmsgtype,statsoutmsgcount,statsinmsgcount) VALUES (62,E'CWPC','2011-11-02 10:04:00.000000',E'LAM',19,7);
INSERT INTO currentstatistics (statsid,statsgiver,statstime,statsmsgtype,statsoutmsgcount,statsinmsgcount) VALUES (64,E'CWPA','2011-11-02 10:04:02.000000',E'LAM',491,591);
INSERT INTO currentstatistics (statsid,statsgiver,statstime,statsmsgtype,statsoutmsgcount,statsinmsgcount) VALUES (65,E'CWPA','2011-11-02 10:04:02.000000',E'ERR',0,0);
INSERT INTO currentstatistics (statsid,statsgiver,statstime,statsmsgtype,statsoutmsgcount,statsinmsgcount) VALUES (67,E'CWPA','2011-11-02 10:04:02.000000',E'INF',2,112);
INSERT INTO currentstatistics (statsid,statsgiver,statstime,statsmsgtype,statsoutmsgcount,statsinmsgcount) VALUES (68,E'CWPA','2011-11-02 10:04:02.000000',E'ACT',0,5);
INSERT INTO currentstatistics (statsid,statsgiver,statstime,statsmsgtype,statsoutmsgcount,statsinmsgcount) VALUES (70,E'CWPC','2011-11-02 10:04:00.000000',E'ACT',0,9);
INSERT INTO currentstatistics (statsid,statsgiver,statstime,statsmsgtype,statsoutmsgcount,statsinmsgcount) VALUES (72,E'CWPD','2011-06-03 13:34:43.000000',E'LAM',29,184);
INSERT INTO currentstatistics (statsid,statsgiver,statstime,statsmsgtype,statsoutmsgcount,statsinmsgcount) VALUES (73,E'CWPD','2011-06-03 13:39:11.000000',E'ERR',8,0);
INSERT INTO currentstatistics (statsid,statsgiver,statstime,statsmsgtype,statsoutmsgcount,statsinmsgcount) VALUES (74,E'CWPD','2011-06-03 13:57:04.000000',E'INF',0,12);
INSERT INTO currentstatistics (statsid,statsgiver,statstime,statsmsgtype,statsoutmsgcount,statsinmsgcount) VALUES (77,E'CWPC','2011-11-02 10:04:00.000000',E'COD',0,0);
INSERT INTO currentstatistics (statsid,statsgiver,statstime,statsmsgtype,statsoutmsgcount,statsinmsgcount) VALUES (78,E'CWPC','2011-11-02 10:04:00.000000',E'ABI',0,0);
INSERT INTO currentstatistics (statsid,statsgiver,statstime,statsmsgtype,statsoutmsgcount,statsinmsgcount) VALUES (79,E'CWPA','2011-11-02 10:04:02.000000',E'ABI',101,0);
INSERT INTO currentstatistics (statsid,statsgiver,statstime,statsmsgtype,statsoutmsgcount,statsinmsgcount) VALUES (81,E'FDP','2013-09-19 00:00:00.000000',E'INF',6,0);
INSERT INTO currentstatistics (statsid,statsgiver,statstime,statsmsgtype,statsoutmsgcount,statsinmsgcount) VALUES (80,E'FDPR','2011-08-17 13:33:40.000000',E'STS',0,1);
INSERT INTO currentstatistics (statsid,statsgiver,statstime,statsmsgtype,statsoutmsgcount,statsinmsgcount) VALUES (95,E'CWPB','2012-11-01 12:19:06.000000',E'STS',1,26);
INSERT INTO currentstatistics (statsid,statsgiver,statstime,statsmsgtype,statsoutmsgcount,statsinmsgcount) VALUES (86,E'FDP','2013-09-19 00:00:00.000000',E'ABI',0,20);
INSERT INTO currentstatistics (statsid,statsgiver,statstime,statsmsgtype,statsoutmsgcount,statsinmsgcount) VALUES (96,E'CWPB','2012-11-06 11:53:53.000000',E'COD',4,2);
INSERT INTO currentstatistics (statsid,statsgiver,statstime,statsmsgtype,statsoutmsgcount,statsinmsgcount) VALUES (82,E'FDP','2013-09-19 00:00:00.000000',E'FPL',0,15);
INSERT INTO currentstatistics (statsid,statsgiver,statstime,statsmsgtype,statsoutmsgcount,statsinmsgcount) VALUES (83,E'FDP','2013-09-19 00:00:00.000000',E'ERR',0,0);
INSERT INTO currentstatistics (statsid,statsgiver,statstime,statsmsgtype,statsoutmsgcount,statsinmsgcount) VALUES (84,E'FDP','2013-09-19 00:00:00.000000',E'ACT',0,0);
INSERT INTO currentstatistics (statsid,statsgiver,statstime,statsmsgtype,statsoutmsgcount,statsinmsgcount) VALUES (85,E'FDP','2013-09-19 00:00:00.000000',E'URZ',0,0);
INSERT INTO currentstatistics (statsid,statsgiver,statstime,statsmsgtype,statsoutmsgcount,statsinmsgcount) VALUES (87,E'CWPB','2012-08-30 13:47:04.000000',E'INF',428,381);
INSERT INTO currentstatistics (statsid,statsgiver,statstime,statsmsgtype,statsoutmsgcount,statsinmsgcount) VALUES (88,E'CWPB','2012-08-30 13:47:05.000000',E'LAM',648,809);
INSERT INTO currentstatistics (statsid,statsgiver,statstime,statsmsgtype,statsoutmsgcount,statsinmsgcount) VALUES (89,E'CWPB','2012-08-30 13:47:35.000000',E'ACT',250,97);
INSERT INTO currentstatistics (statsid,statsgiver,statstime,statsmsgtype,statsoutmsgcount,statsinmsgcount) VALUES (90,E'CWPB','2012-08-30 13:53:44.000000',E'COF',65,45);
INSERT INTO currentstatistics (statsid,statsgiver,statstime,statsmsgtype,statsoutmsgcount,statsinmsgcount) VALUES (91,E'CWPB','2012-08-30 13:53:55.000000',E'MAS',47,72);
INSERT INTO currentstatistics (statsid,statsgiver,statstime,statsmsgtype,statsoutmsgcount,statsinmsgcount) VALUES (92,E'CWPB','2012-08-30 13:59:09.000000',E'HOP',94,56);
INSERT INTO currentstatistics (statsid,statsgiver,statstime,statsmsgtype,statsoutmsgcount,statsinmsgcount) VALUES (93,E'CWPB','2012-08-30 13:59:14.000000',E'ROF',53,87);
INSERT INTO currentstatistics (statsid,statsgiver,statstime,statsmsgtype,statsoutmsgcount,statsinmsgcount) VALUES (94,E'CWPB','2012-08-31 15:14:18.000000',E'FPL',6,5);
INSERT INTO currentstatistics (statsid,statsgiver,statstime,statsmsgtype,statsoutmsgcount,statsinmsgcount) VALUES (98,E'DHB','2013-04-02 10:36:57.000000',E'MSG',3810,0);
INSERT INTO currentstatistics (statsid,statsgiver,statstime,statsmsgtype,statsoutmsgcount,statsinmsgcount) VALUES (100,E'CWPA','2013-05-15 16:51:14.000000',E'URZ',29,1);
