-- Generated by Ora2Pg, the Oracle database Schema converter, version 13.0
-- Copyright 2000-2014 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.20.1.81;sid=XE

SET client_encoding TO 'UTF8';

SET search_path = aero, pg_catalog;\set ON_ERROR_STOP ON

SET search_path = aero, pg_catalog;
INSERT INTO echelons (id,echelon,meters,feet,azimuth,vfr_ifr) VALUES (10,10,300,1000,359,1);
INSERT INTO echelons (id,echelon,meters,feet,azimuth,vfr_ifr) VALUES (20,20,600,2000,179,1);
INSERT INTO echelons (id,echelon,meters,feet,azimuth,vfr_ifr) VALUES (30,30,900,3000,359,1);
INSERT INTO echelons (id,echelon,meters,feet,azimuth,vfr_ifr) VALUES (40,40,1200,4000,179,1);
INSERT INTO echelons (id,echelon,meters,feet,azimuth,vfr_ifr) VALUES (50,50,1500,5000,359,1);
INSERT INTO echelons (id,echelon,meters,feet,azimuth,vfr_ifr) VALUES (60,60,1850,6000,179,1);
INSERT INTO echelons (id,echelon,meters,feet,azimuth,vfr_ifr) VALUES (70,70,2150,7000,359,1);
INSERT INTO echelons (id,echelon,meters,feet,azimuth,vfr_ifr) VALUES (80,80,2450,8000,179,1);
INSERT INTO echelons (id,echelon,meters,feet,azimuth,vfr_ifr) VALUES (90,90,2750,9000,359,1);
INSERT INTO echelons (id,echelon,meters,feet,azimuth,vfr_ifr) VALUES (100,100,3050,10000,179,1);
INSERT INTO echelons (id,echelon,meters,feet,azimuth,vfr_ifr) VALUES (110,110,3350,11000,359,1);
INSERT INTO echelons (id,echelon,meters,feet,azimuth,vfr_ifr) VALUES (120,120,3650,12000,179,1);
INSERT INTO echelons (id,echelon,meters,feet,azimuth,vfr_ifr) VALUES (130,130,3950,13000,359,1);
INSERT INTO echelons (id,echelon,meters,feet,azimuth,vfr_ifr) VALUES (140,140,4250,14000,179,1);
INSERT INTO echelons (id,echelon,meters,feet,azimuth,vfr_ifr) VALUES (150,150,4550,15000,359,1);
INSERT INTO echelons (id,echelon,meters,feet,azimuth,vfr_ifr) VALUES (160,160,4900,16000,179,1);
INSERT INTO echelons (id,echelon,meters,feet,azimuth,vfr_ifr) VALUES (170,170,5200,17000,359,1);
INSERT INTO echelons (id,echelon,meters,feet,azimuth,vfr_ifr) VALUES (180,180,5500,18000,179,1);
INSERT INTO echelons (id,echelon,meters,feet,azimuth,vfr_ifr) VALUES (190,190,5800,19000,359,1);
INSERT INTO echelons (id,echelon,meters,feet,azimuth,vfr_ifr) VALUES (200,200,6100,20000,179,1);
INSERT INTO echelons (id,echelon,meters,feet,azimuth,vfr_ifr) VALUES (210,210,6400,21000,359,1);
INSERT INTO echelons (id,echelon,meters,feet,azimuth,vfr_ifr) VALUES (220,220,6700,22000,179,1);
INSERT INTO echelons (id,echelon,meters,feet,azimuth,vfr_ifr) VALUES (230,230,7000,23000,359,1);
INSERT INTO echelons (id,echelon,meters,feet,azimuth,vfr_ifr) VALUES (240,240,7300,24000,179,1);
INSERT INTO echelons (id,echelon,meters,feet,azimuth,vfr_ifr) VALUES (250,250,7600,25000,359,1);
INSERT INTO echelons (id,echelon,meters,feet,azimuth,vfr_ifr) VALUES (260,260,7900,26000,179,1);
INSERT INTO echelons (id,echelon,meters,feet,azimuth,vfr_ifr) VALUES (270,270,8250,27000,359,1);
INSERT INTO echelons (id,echelon,meters,feet,azimuth,vfr_ifr) VALUES (280,280,8550,28000,179,1);
INSERT INTO echelons (id,echelon,meters,feet,azimuth,vfr_ifr) VALUES (290,290,8850,28000,359,1);
INSERT INTO echelons (id,echelon,meters,feet,azimuth,vfr_ifr) VALUES (300,300,9150,30000,179,1);
INSERT INTO echelons (id,echelon,meters,feet,azimuth,vfr_ifr) VALUES (310,310,9450,31000,359,1);
INSERT INTO echelons (id,echelon,meters,feet,azimuth,vfr_ifr) VALUES (320,320,9750,32000,179,1);
INSERT INTO echelons (id,echelon,meters,feet,azimuth,vfr_ifr) VALUES (330,330,10050,33000,359,1);
INSERT INTO echelons (id,echelon,meters,feet,azimuth,vfr_ifr) VALUES (340,340,10350,34000,179,1);
INSERT INTO echelons (id,echelon,meters,feet,azimuth,vfr_ifr) VALUES (350,350,10650,35000,359,1);
INSERT INTO echelons (id,echelon,meters,feet,azimuth,vfr_ifr) VALUES (360,360,10950,36000,179,1);
INSERT INTO echelons (id,echelon,meters,feet,azimuth,vfr_ifr) VALUES (370,370,11300,37000,359,1);
INSERT INTO echelons (id,echelon,meters,feet,azimuth,vfr_ifr) VALUES (380,380,11600,38000,179,1);
INSERT INTO echelons (id,echelon,meters,feet,azimuth,vfr_ifr) VALUES (390,390,11900,39000,359,1);
INSERT INTO echelons (id,echelon,meters,feet,azimuth,vfr_ifr) VALUES (400,400,12200,40000,179,1);
INSERT INTO echelons (id,echelon,meters,feet,azimuth,vfr_ifr) VALUES (410,410,12500,41000,359,1);
INSERT INTO echelons (id,echelon,meters,feet,azimuth,vfr_ifr) VALUES (430,430,13100,43000,179,1);
INSERT INTO echelons (id,echelon,meters,feet,azimuth,vfr_ifr) VALUES (450,450,13700,45000,359,1);
INSERT INTO echelons (id,echelon,meters,feet,azimuth,vfr_ifr) VALUES (470,470,14350,47000,179,1);
INSERT INTO echelons (id,echelon,meters,feet,azimuth,vfr_ifr) VALUES (490,490,13700,49000,359,1);
INSERT INTO echelons (id,echelon,meters,feet,azimuth,vfr_ifr) VALUES (510,510,15500,51000,179,1);
