-- Generated by Ora2Pg, the Oracle database Schema converter, version 13.0
-- Copyright 2000-2014 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.20.1.81;sid=XE

SET client_encoding TO 'UTF8';

SET search_path = aero, pg_catalog;\set ON_ERROR_STOP ON

SET search_path = aero, pg_catalog;
INSERT INTO exercise (id_exercise,name) VALUES (443,E'1234567');
INSERT INTO exercise (id_exercise,name) VALUES (444,E'7654321');
INSERT INTO exercise (id_exercise,name) VALUES (343,E'MM');
INSERT INTO exercise (id_exercise,name) VALUES (323,E'T2T');
INSERT INTO exercise (id_exercise,name) VALUES (363,E'ABAN');
INSERT INTO exercise (id_exercise,name) VALUES (383,E'DUSHANBE');
INSERT INTO exercise (id_exercise,name) VALUES (403,E'ABAN2');
INSERT INTO exercise (id_exercise,name) VALUES (423,E'ABAN3');
INSERT INTO exercise (id_exercise,name) VALUES (463,E'1111111');
