-- Generated by Ora2Pg, the Oracle database Schema converter, version 13.0
-- Copyright 2000-2014 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.20.1.81;sid=XE

SET client_encoding TO 'UTF8';

SET search_path = aero, pg_catalog;\set ON_ERROR_STOP ON

SET search_path = aero, pg_catalog;
INSERT INTO exercise_plane (id_exercise,id_plane,start_time,id_parentfpl,op,sector,circle) VALUES (423,293588,0,NULL,NULL,NULL,0);
INSERT INTO exercise_plane (id_exercise,id_plane,start_time,id_parentfpl,op,sector,circle) VALUES (423,293589,10,NULL,NULL,NULL,0);
INSERT INTO exercise_plane (id_exercise,id_plane,start_time,id_parentfpl,op,sector,circle) VALUES (383,293348,0,NULL,NULL,NULL,0);
INSERT INTO exercise_plane (id_exercise,id_plane,start_time,id_parentfpl,op,sector,circle) VALUES (383,293369,0,NULL,NULL,NULL,0);
INSERT INTO exercise_plane (id_exercise,id_plane,start_time,id_parentfpl,op,sector,circle) VALUES (383,293688,0,NULL,NULL,NULL,0);
INSERT INTO exercise_plane (id_exercise,id_plane,start_time,id_parentfpl,op,sector,circle) VALUES (443,1608,0,NULL,NULL,NULL,0);
INSERT INTO exercise_plane (id_exercise,id_plane,start_time,id_parentfpl,op,sector,circle) VALUES (444,1608,0,NULL,NULL,NULL,0);
INSERT INTO exercise_plane (id_exercise,id_plane,start_time,id_parentfpl,op,sector,circle) VALUES (463,1609,0,NULL,NULL,NULL,0);
INSERT INTO exercise_plane (id_exercise,id_plane,start_time,id_parentfpl,op,sector,circle) VALUES (403,293508,0,NULL,NULL,NULL,0);
INSERT INTO exercise_plane (id_exercise,id_plane,start_time,id_parentfpl,op,sector,circle) VALUES (403,293509,0,NULL,NULL,NULL,0);
INSERT INTO exercise_plane (id_exercise,id_plane,start_time,id_parentfpl,op,sector,circle) VALUES (403,293510,0,NULL,NULL,NULL,0);
INSERT INTO exercise_plane (id_exercise,id_plane,start_time,id_parentfpl,op,sector,circle) VALUES (403,293511,0,NULL,NULL,NULL,0);
INSERT INTO exercise_plane (id_exercise,id_plane,start_time,id_parentfpl,op,sector,circle) VALUES (363,1608,0,NULL,NULL,NULL,1);
INSERT INTO exercise_plane (id_exercise,id_plane,start_time,id_parentfpl,op,sector,circle) VALUES (363,1609,0,NULL,NULL,NULL,1);
INSERT INTO exercise_plane (id_exercise,id_plane,start_time,id_parentfpl,op,sector,circle) VALUES (363,1610,0,NULL,NULL,NULL,1);
