-- Generated by Ora2Pg, the Oracle database Schema converter, version 13.0
-- Copyright 2000-2014 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.20.1.81;sid=XE

SET client_encoding TO 'UTF8';

SET search_path = aero, pg_catalog;\set ON_ERROR_STOP ON

SET search_path = aero, pg_catalog;
INSERT INTO flight_types (name) VALUES (E'G');
INSERT INTO flight_types (name) VALUES (E'M');
INSERT INTO flight_types (name) VALUES (E'N');
INSERT INTO flight_types (name) VALUES (E'S');
INSERT INTO flight_types (name) VALUES (E'X');
