-- Generated by Ora2Pg, the Oracle database Schema converter, version 13.0
-- Copyright 2000-2014 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.20.1.81;sid=XE

SET client_encoding TO 'UTF8';

SET search_path = aero, pg_catalog;\set ON_ERROR_STOP ON

SET search_path = aero, pg_catalog;
INSERT INTO fpl_additional (fpl_id_ref,additional_info) VALUES (293648,NULL);
INSERT INTO fpl_additional (fpl_id_ref,additional_info) VALUES (293649,NULL);
INSERT INTO fpl_additional (fpl_id_ref,additional_info) VALUES (293628,NULL);
INSERT INTO fpl_additional (fpl_id_ref,additional_info) VALUES (1575,NULL);
INSERT INTO fpl_additional (fpl_id_ref,additional_info) VALUES (1576,NULL);
INSERT INTO fpl_additional (fpl_id_ref,additional_info) VALUES (1577,NULL);
INSERT INTO fpl_additional (fpl_id_ref,additional_info) VALUES (1579,NULL);
INSERT INTO fpl_additional (fpl_id_ref,additional_info) VALUES (1595,NULL);
INSERT INTO fpl_additional (fpl_id_ref,additional_info) VALUES (1596,NULL);
INSERT INTO fpl_additional (fpl_id_ref,additional_info) VALUES (1604,NULL);
INSERT INTO fpl_additional (fpl_id_ref,additional_info) VALUES (1608,NULL);
INSERT INTO fpl_additional (fpl_id_ref,additional_info) VALUES (1609,NULL);
INSERT INTO fpl_additional (fpl_id_ref,additional_info) VALUES (1610,NULL);
INSERT INTO fpl_additional (fpl_id_ref,additional_info) VALUES (1615,NULL);
INSERT INTO fpl_additional (fpl_id_ref,additional_info) VALUES (1616,NULL);
INSERT INTO fpl_additional (fpl_id_ref,additional_info) VALUES (293348,NULL);
INSERT INTO fpl_additional (fpl_id_ref,additional_info) VALUES (293368,NULL);
INSERT INTO fpl_additional (fpl_id_ref,additional_info) VALUES (293369,NULL);
INSERT INTO fpl_additional (fpl_id_ref,additional_info) VALUES (293388,NULL);
INSERT INTO fpl_additional (fpl_id_ref,additional_info) VALUES (293408,NULL);
INSERT INTO fpl_additional (fpl_id_ref,additional_info) VALUES (293428,NULL);
INSERT INTO fpl_additional (fpl_id_ref,additional_info) VALUES (293468,NULL);
INSERT INTO fpl_additional (fpl_id_ref,additional_info) VALUES (293489,NULL);
INSERT INTO fpl_additional (fpl_id_ref,additional_info) VALUES (293508,NULL);
INSERT INTO fpl_additional (fpl_id_ref,additional_info) VALUES (293509,NULL);
INSERT INTO fpl_additional (fpl_id_ref,additional_info) VALUES (293510,NULL);
INSERT INTO fpl_additional (fpl_id_ref,additional_info) VALUES (293511,NULL);
INSERT INTO fpl_additional (fpl_id_ref,additional_info) VALUES (293528,NULL);
INSERT INTO fpl_additional (fpl_id_ref,additional_info) VALUES (293529,NULL);
INSERT INTO fpl_additional (fpl_id_ref,additional_info) VALUES (293548,NULL);
INSERT INTO fpl_additional (fpl_id_ref,additional_info) VALUES (293549,NULL);
INSERT INTO fpl_additional (fpl_id_ref,additional_info) VALUES (293550,NULL);
INSERT INTO fpl_additional (fpl_id_ref,additional_info) VALUES (293551,NULL);
INSERT INTO fpl_additional (fpl_id_ref,additional_info) VALUES (293552,NULL);
INSERT INTO fpl_additional (fpl_id_ref,additional_info) VALUES (293553,NULL);
INSERT INTO fpl_additional (fpl_id_ref,additional_info) VALUES (293563,NULL);
INSERT INTO fpl_additional (fpl_id_ref,additional_info) VALUES (293564,NULL);
INSERT INTO fpl_additional (fpl_id_ref,additional_info) VALUES (293568,NULL);
INSERT INTO fpl_additional (fpl_id_ref,additional_info) VALUES (293588,NULL);
INSERT INTO fpl_additional (fpl_id_ref,additional_info) VALUES (293589,NULL);
INSERT INTO fpl_additional (fpl_id_ref,additional_info) VALUES (293668,NULL);
INSERT INTO fpl_additional (fpl_id_ref,additional_info) VALUES (293688,NULL);
