-- Generated by Ora2Pg, the Oracle database Schema converter, version 13.0
-- Copyright 2000-2014 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.20.1.81;sid=XE

SET client_encoding TO 'UTF8';

SET search_path = aero, pg_catalog;\set ON_ERROR_STOP ON

SET search_path = aero, pg_catalog;
INSERT INTO hist_fpl (id,fir_name,aircraft_id,taircraft,frules,tflight,num,wtc,equipment,adep,time,speed,flevel,route,ades,eet,alt1,alt2,other,trtime,exfpl,visibility,hist_id,modified_by,modified_at,modification_type,actual,message_id,entry_fir_eet) VALUES (293648,E'UTDD',E'ETJ734',E'A320',E'I',E'S',1,E'M',E'SFDRWY/S',E'UUDD','2013-10-28 19:50:00.000000',E'N0452',E'F350',E'ODIVA TAHIR TMD MAMAL ATPOT EKMIB NULRI IBKIT GETLI PR DCT LIVDI',E'UTDT',E'03:54',E'UTDD',NULL,E'PBN/B3B4O3T1C3D3 DOF/131028 REG/EY623 EET/UWWW0035 UATT0118 UAII0228 UTTR0259 UTSD0313 UTDD0333 OPR/EAST AIR RMK/TCAS EQUIPPED 
-PERM/KAZ
-TR
-112
-86/131023 UZB
-10/13/362 TJK
-1584/10 CAA
-KTB','2013-10-28 13:44:47.099000',NULL,NULL,1924,0,'2013-10-28 13:44:47.365000',E'I',E'1',NULL,E'03:33');
INSERT INTO hist_fpl (id,fir_name,aircraft_id,taircraft,frules,tflight,num,wtc,equipment,adep,time,speed,flevel,route,ades,eet,alt1,alt2,other,trtime,exfpl,visibility,hist_id,modified_by,modified_at,modification_type,actual,message_id,entry_fir_eet) VALUES (293649,E'UTDD',E'UTA802',E'A321',E'I',E'S',1,E'M',E'SDIE2E3FHJ4RWGY/LB1U1',E'UTDD','2013-10-28 11:30:00.000000',E'K0820',E'F360',E'GETLI IBKIT NULRI EKMIB ATPOT MAMAL TMD TAHIR ODIVA',E'UUWW',E'04:14',E'UUDD',E'UWGG',E'PBN/B1D1O1 DOF/131028 REG/VPBPS EET/UTSD0012 UTDD0016 UTSD0017 UTDD0019 UTSD0021 UTTR0042 UAII0056 UATT0126 UWWW0243 UUWV0328','2013-10-28 13:45:22.074000',NULL,NULL,1925,0,'2013-10-28 13:45:22.075000',E'I',E'1',NULL,E'00:19');
INSERT INTO hist_fpl (id,fir_name,aircraft_id,taircraft,frules,tflight,num,wtc,equipment,adep,time,speed,flevel,route,ades,eet,alt1,alt2,other,trtime,exfpl,visibility,hist_id,modified_by,modified_at,modification_type,actual,message_id,entry_fir_eet) VALUES (293608,E'UTDD',E'RCH712',E'C17',E'I',E'M',1,E'H',E'SDE1E2FGHIJ5RTUWXYZ/HD1',E'UCFM','2013-07-01 12:15:00.000000',E'N0434',E'F360',E'PINAX/N0447F290',E'OAKB',E'01:35',NULL,NULL,E'PBN/A1B1C1D1L1O1S1 EUR/PROTECTED NAV/RNVD1E2A1 DOF/130701 REG/66157A EET/UCFO0015 UTDD0045 OAKX0110 SEL/CHFR CODE/AE145B OPR/DOD PER/D RMK/PTP TCAS AGCS MDCN UA 15 2803 GCK R UT BKX 290 06 12 12 OAKB PPR AL 1826 13149','2013-07-01 15:29:08.627000',NULL,0,1904,1,'2013-07-01 15:29:10.260000',E'I',E'0',NULL,E'00:45');
INSERT INTO hist_fpl (id,fir_name,aircraft_id,taircraft,frules,tflight,num,wtc,equipment,adep,time,speed,flevel,route,ades,eet,alt1,alt2,other,trtime,exfpl,visibility,hist_id,modified_by,modified_at,modification_type,actual,message_id,entry_fir_eet) VALUES (293608,E'UTDD',E'RCH712',E'C17',E'I',E'M',1,E'H',E'SDE1E2FGHIJ5RTUWXYZ/HD1',E'UCFM','2013-07-01 12:15:00.000000',E'N0434',E'F360',E'PINAX/N0447F290 VADER',E'OAKB',E'01:35',NULL,NULL,E'PBN/A1B1C1D1L1O1S1 EUR/PROTECTED NAV/RNVD1E2A1 DOF/130701 REG/66157A EET/UCFO0015 UTDD0045 OAKX0110 SEL/CHFR CODE/AE145B OPR/DOD PER/D RMK/PTP TCAS AGCS MDCN UA 15 2803 GCK R UT BKX 290 06 12 12 OAKB PPR AL 1826 13149','2013-07-01 15:29:08.627000',NULL,0,1905,1,'2013-07-01 15:29:38.516000',E'U',E'0',NULL,E'00:45');
INSERT INTO hist_fpl (id,fir_name,aircraft_id,taircraft,frules,tflight,num,wtc,equipment,adep,time,speed,flevel,route,ades,eet,alt1,alt2,other,trtime,exfpl,visibility,hist_id,modified_by,modified_at,modification_type,actual,message_id,entry_fir_eet) VALUES (293608,E'UTDD',E'RCH712',E'C17',E'I',E'M',1,E'H',E'SDE1E2FGHIJ5RTUWXYZ/HD1',E'UCFM','2013-07-01 12:15:00.000000',E'N0434',E'F360',E'PINAX/N0447F290 VADER',E'OAKB',E'01:35',NULL,NULL,E'PBN/A1B1C1D1L1O1S1 EUR/PROTECTED NAV/RNVD1E2A1 DOF/130701 REG/66157A EET/UCFO0015 UTDD0045 OAKX0110 SEL/CHFR CODE/AE145B OPR/DOD PER/D RMK/PTP TCAS AGCS MDCN UA 15 2803 GCK R UT BKX 290 06 12 12 OAKB PPR AL 1826 13149','2013-07-01 15:29:08.627000',NULL,0,1906,1,'2013-07-01 15:30:01.122000',E'D',E'1',NULL,E'00:45');
INSERT INTO hist_fpl (id,fir_name,aircraft_id,taircraft,frules,tflight,num,wtc,equipment,adep,time,speed,flevel,route,ades,eet,alt1,alt2,other,trtime,exfpl,visibility,hist_id,modified_by,modified_at,modification_type,actual,message_id,entry_fir_eet) VALUES (293668,E'UTDD',E'ETJ704',E'A320',E'I',E'S',1,E'M',E'SDFGRWY/S',E'UUDD','2013-10-29 21:00:00.000000',E'N0456',E'F330',E'ODIVA TAHIR TMD MAMAL ATPOT EKMIB NULRI IBKIT GETLI PR DNB HU HU1A',E'UTDK',E'03:57',E'UTDD',NULL,E'PBN/B2B4O2T1C2D2 DOF/131029 REG/EY622 EET/UWWW0034 UATT0117 UAII0227 UTTR0258 UTSD0312 UTDD0331 OPR/EAST AIR RMK/TCAS EQUIPPED 
-PERM/KAZ
-112CCA4640/1028 UZB
-10/13/433 TJK
-1586/10 CAA
-KLB','2013-10-30 14:52:19.616000',NULL,NULL,1944,0,'2013-10-30 14:52:20.540000',E'I',E'1',NULL,E'03:31');
