-- Generated by Ora2Pg, the Oracle database Schema converter, version 13.0
-- Copyright 2000-2014 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.20.1.81;sid=XE

SET client_encoding TO 'UTF8';

SET search_path = aero, pg_catalog;\set ON_ERROR_STOP ON

SET search_path = aero, pg_catalog;
INSERT INTO holding_type (id,name) VALUES (48,E'Undef');
INSERT INTO holding_type (id,name) VALUES (49,E'HighAlt');
INSERT INTO holding_type (id,name) VALUES (50,E'LowAlt');
INSERT INTO holding_type (id,name) VALUES (51,E'SID');
INSERT INTO holding_type (id,name) VALUES (52,E'STAR');
INSERT INTO holding_type (id,name) VALUES (53,E'Appr');
INSERT INTO holding_type (id,name) VALUES (54,E'MisAppr');
INSERT INTO holding_type (id,name) VALUES (55,E'Undef2');
