-- Generated by Ora2Pg, the Oracle database Schema converter, version 13.0
-- Copyright 2000-2014 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.20.1.81;sid=XE

SET client_encoding TO 'UTF8';

SET search_path = aero, pg_catalog;\set ON_ERROR_STOP ON

SET search_path = aero, pg_catalog;
INSERT INTO login_log (user_id,user_name,logged_time,logged_type) VALUES (1,E'admin','2013-07-08 08:14:17.217000',E'1');
INSERT INTO login_log (user_id,user_name,logged_time,logged_type) VALUES (1,E'admin','2013-07-08 08:14:38.667000',E'0');
INSERT INTO login_log (user_id,user_name,logged_time,logged_type) VALUES (0,E'fdpservice','2013-07-08 14:36:23.090000',E'1');
INSERT INTO login_log (user_id,user_name,logged_time,logged_type) VALUES (0,E'fdpservice','2013-07-15 07:58:18.810000',E'1');
INSERT INTO login_log (user_id,user_name,logged_time,logged_type) VALUES (0,E'fdpservice','2013-07-15 07:58:18.857000',E'1');
INSERT INTO login_log (user_id,user_name,logged_time,logged_type) VALUES (1,E'admin','2013-07-05 12:01:53.740000',E'1');
INSERT INTO login_log (user_id,user_name,logged_time,logged_type) VALUES (1,E'admin','2013-07-05 12:03:02.111000',E'1');
INSERT INTO login_log (user_id,user_name,logged_time,logged_type) VALUES (1,E'admin','2013-07-05 12:09:54.237000',E'0');
INSERT INTO login_log (user_id,user_name,logged_time,logged_type) VALUES (1,E'admin','2013-07-05 12:48:47.617000',E'1');
INSERT INTO login_log (user_id,user_name,logged_time,logged_type) VALUES (1,E'admin','2013-07-05 12:50:55.169000',E'0');
INSERT INTO login_log (user_id,user_name,logged_time,logged_type) VALUES (0,E'fdpservice','2013-07-08 14:36:23.103000',E'1');
INSERT INTO login_log (user_id,user_name,logged_time,logged_type) VALUES (1,E'admin','2013-07-15 07:58:18.928000',E'0');
INSERT INTO login_log (user_id,user_name,logged_time,logged_type) VALUES (1,E'admin','2013-07-15 07:58:19.025000',E'1');
INSERT INTO login_log (user_id,user_name,logged_time,logged_type) VALUES (1,E'admin','2013-07-05 10:26:46.698000',E'1');
INSERT INTO login_log (user_id,user_name,logged_time,logged_type) VALUES (1,E'admin','2013-07-05 10:27:33.157000',E'0');
INSERT INTO login_log (user_id,user_name,logged_time,logged_type) VALUES (1,E'admin','2013-07-05 12:22:07.510000',E'1');
INSERT INTO login_log (user_id,user_name,logged_time,logged_type) VALUES (1,E'admin','2013-07-05 12:30:13.310000',E'0');
INSERT INTO login_log (user_id,user_name,logged_time,logged_type) VALUES (1,E'admin','2013-07-05 12:51:44.210000',E'1');
INSERT INTO login_log (user_id,user_name,logged_time,logged_type) VALUES (1,E'admin','2013-07-05 12:52:00.261000',E'0');
INSERT INTO login_log (user_id,user_name,logged_time,logged_type) VALUES (1,E'admin','2013-07-05 12:54:09.417000',E'1');
INSERT INTO login_log (user_id,user_name,logged_time,logged_type) VALUES (1,E'admin','2013-07-05 12:55:22.871000',E'0');
INSERT INTO login_log (user_id,user_name,logged_time,logged_type) VALUES (1,E'admin','2013-07-05 12:56:47.831000',E'1');
INSERT INTO login_log (user_id,user_name,logged_time,logged_type) VALUES (1,E'admin','2013-07-05 13:02:02.090000',E'0');
INSERT INTO login_log (user_id,user_name,logged_time,logged_type) VALUES (1,E'admin','2013-07-05 13:32:20.708000',E'1');
INSERT INTO login_log (user_id,user_name,logged_time,logged_type) VALUES (1,E'admin','2013-07-05 13:32:57.313000',E'0');
INSERT INTO login_log (user_id,user_name,logged_time,logged_type) VALUES (1,E'admin','2013-07-05 13:34:56.874000',E'1');
INSERT INTO login_log (user_id,user_name,logged_time,logged_type) VALUES (1,E'admin','2013-07-05 13:35:24.396000',E'0');
INSERT INTO login_log (user_id,user_name,logged_time,logged_type) VALUES (1,E'admin','2013-07-05 13:54:58.170000',E'1');
INSERT INTO login_log (user_id,user_name,logged_time,logged_type) VALUES (1,E'admin','2013-07-05 13:56:14.995000',E'0');
INSERT INTO login_log (user_id,user_name,logged_time,logged_type) VALUES (1,E'admin','2013-07-05 13:57:03.390000',E'1');
INSERT INTO login_log (user_id,user_name,logged_time,logged_type) VALUES (1,E'admin','2013-07-05 13:59:26.978000',E'0');
INSERT INTO login_log (user_id,user_name,logged_time,logged_type) VALUES (1,E'admin','2013-07-05 13:59:51.930000',E'1');
INSERT INTO login_log (user_id,user_name,logged_time,logged_type) VALUES (1,E'admin','2013-07-05 14:01:38.195000',E'0');
INSERT INTO login_log (user_id,user_name,logged_time,logged_type) VALUES (1,E'admin','2013-07-05 14:26:50.672000',E'1');
INSERT INTO login_log (user_id,user_name,logged_time,logged_type) VALUES (1,E'admin','2013-07-05 14:27:46.522000',E'1');
INSERT INTO login_log (user_id,user_name,logged_time,logged_type) VALUES (1,E'admin','2013-07-05 14:43:33.615000',E'1');
INSERT INTO login_log (user_id,user_name,logged_time,logged_type) VALUES (1,E'admin','2013-07-05 14:50:03.539000',E'0');
INSERT INTO login_log (user_id,user_name,logged_time,logged_type) VALUES (0,E'fdpservice','2013-07-08 14:36:23.102000',E'1');
INSERT INTO login_log (user_id,user_name,logged_time,logged_type) VALUES (0,E'fdpservice','2013-07-15 07:58:18.905000',E'1');
INSERT INTO login_log (user_id,user_name,logged_time,logged_type) VALUES (1,E'admin','2013-07-15 07:58:18.887000',E'0');
INSERT INTO login_log (user_id,user_name,logged_time,logged_type) VALUES (1,E'admin','2013-07-15 07:58:19.633000',E'1');
INSERT INTO login_log (user_id,user_name,logged_time,logged_type) VALUES (1,E'admin','2013-07-15 07:58:55.815000',E'0');
INSERT INTO login_log (user_id,user_name,logged_time,logged_type) VALUES (1,E'admin','2013-07-08 12:49:42.663000',E'1');
INSERT INTO login_log (user_id,user_name,logged_time,logged_type) VALUES (1,E'admin','2013-07-08 12:50:03.039000',E'0');
INSERT INTO login_log (user_id,user_name,logged_time,logged_type) VALUES (0,E'fdpservice','2013-07-08 14:36:23.103000',E'1');
INSERT INTO login_log (user_id,user_name,logged_time,logged_type) VALUES (0,E'fdpservice','2013-07-15 07:58:18.887000',E'1');
