-- Generated by Ora2Pg, the Oracle database Schema converter, version 13.0
-- Copyright 2000-2014 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.20.1.81;sid=XE

SET client_encoding TO 'UTF8';

SET search_path = aero, pg_catalog;\set ON_ERROR_STOP ON

SET search_path = aero, pg_catalog;
INSERT INTO meteo (id,zone_id,name,type,utc_time,sic,sac,course,speed,h) VALUES (187,1094,E'2',3,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO meteo (id,zone_id,name,type,utc_time,sic,sac,course,speed,h) VALUES (141,1076,E'<unassigned>',2,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO meteo (id,zone_id,name,type,utc_time,sic,sac,course,speed,h) VALUES (182,1094,E'1',2,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO meteo (id,zone_id,name,type,utc_time,sic,sac,course,speed,h) VALUES (303,978,E'2',5,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO meteo (id,zone_id,name,type,utc_time,sic,sac,course,speed,h) VALUES (302,978,E'1',1,NULL,NULL,NULL,NULL,NULL,NULL);
