-- Generated by Ora2Pg, the Oracle database Schema converter, version 13.0
-- Copyright 2000-2014 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.20.1.81;sid=XE

SET client_encoding TO 'UTF8';

SET search_path = aero, pg_catalog;\set ON_ERROR_STOP ON

SET search_path = aero, pg_catalog;
INSERT INTO meteo_runway (runway_id,control_time,magnetic_wind,average_speed,max_speed,side_wind,longitudial_wind,sight_dist,sdist_start_ovi,sdist_middle_ovi,sdist_end_ovi,cloud_lower,pressure_threshould,pressure_sea,temperature,condensation_point) VALUES (1347,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
