-- Generated by Ora2Pg, the Oracle database Schema converter, version 13.0
-- Copyright 2000-2014 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.20.1.81;sid=XE

SET client_encoding TO 'UTF8';

SET search_path = aero, pg_catalog;\set ON_ERROR_STOP ON

SET search_path = aero, pg_catalog;
INSERT INTO meteo_point (id,meteo_id,latitude,longitude,sn) VALUES (173,187,39.46976424,68.53533205,30);
INSERT INTO meteo_point (id,meteo_id,latitude,longitude,sn) VALUES (174,187,39.39243192,69.37764497,20);
INSERT INTO meteo_point (id,meteo_id,latitude,longitude,sn) VALUES (175,187,39.1465814,68.68586007,10);
INSERT INTO meteo_point (id,meteo_id,latitude,longitude,sn) VALUES (166,182,38.84315826,72.29464458,10);
INSERT INTO meteo_point (id,meteo_id,latitude,longitude,sn) VALUES (328,303,43.17421857,68.0066348,20);
INSERT INTO meteo_point (id,meteo_id,latitude,longitude,sn) VALUES (329,303,42.64602821,68.73385697,10);
INSERT INTO meteo_point (id,meteo_id,latitude,longitude,sn) VALUES (164,182,39.46092064,71.45039786,30);
INSERT INTO meteo_point (id,meteo_id,latitude,longitude,sn) VALUES (165,182,39.37581557,72.79086331,20);
INSERT INTO meteo_point (id,meteo_id,latitude,longitude,sn) VALUES (327,303,42.7284,67.31025261,30);
INSERT INTO meteo_point (id,meteo_id,latitude,longitude,sn) VALUES (326,302,42.00937596,68.08029369,10);
INSERT INTO meteo_point (id,meteo_id,latitude,longitude,sn) VALUES (324,302,42.54566623,67.28620614,30);
INSERT INTO meteo_point (id,meteo_id,latitude,longitude,sn) VALUES (325,302,42.47381685,68.9416997,20);
