-- Generated by Ora2Pg, the Oracle database Schema converter, version 13.0
-- Copyright 2000-2014 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.20.1.81;sid=XE

SET client_encoding TO 'UTF8';

SET search_path = aero, pg_catalog;\set ON_ERROR_STOP ON

SET search_path = aero, pg_catalog;
INSERT INTO msg_from_tan (id,fir_name,aircraft_id,taircraft,frules,tflight,num,wtc,equipment,adep,time,speed,flevel,route,ades,eet,alt1,alt2,other,trtime,exfpl,visibility,entry_fir_eet,oper,oper_time,message_text) VALUES (111,E'UTDD',E'1',E'1',E'1',E'1',0,E'1',E'1',E'1','2013-05-06 13:48:54.000000',E'1',E'1',E'1',E'1',E'1',NULL,NULL,NULL,NULL,NULL,0,NULL,E'I','2013-05-06 13:48:54.000000',NULL);
INSERT INTO msg_from_tan (id,fir_name,aircraft_id,taircraft,frules,tflight,num,wtc,equipment,adep,time,speed,flevel,route,ades,eet,alt1,alt2,other,trtime,exfpl,visibility,entry_fir_eet,oper,oper_time,message_text) VALUES (111,E'UTDD',E'1',E'1',E'1',E'1',0,E'1',E'1',E'1','2013-05-06 12:52:48.000000',E'1',E'1',E'1',E'1',E'1',NULL,NULL,NULL,NULL,NULL,0,NULL,E'1','2013-05-06 12:52:48.000000',NULL);
INSERT INTO msg_from_tan (id,fir_name,aircraft_id,taircraft,frules,tflight,num,wtc,equipment,adep,time,speed,flevel,route,ades,eet,alt1,alt2,other,trtime,exfpl,visibility,entry_fir_eet,oper,oper_time,message_text) VALUES (111,E'UTDD',E'1',E'1',E'1',E'1',0,E'1',E'1',E'1','2013-05-06 12:47:12.000000',E'1',E'1',E'1',E'1',E'1',NULL,NULL,NULL,NULL,NULL,0,NULL,E'1','2013-05-06 12:47:12.000000',NULL);
INSERT INTO msg_from_tan (id,fir_name,aircraft_id,taircraft,frules,tflight,num,wtc,equipment,adep,time,speed,flevel,route,ades,eet,alt1,alt2,other,trtime,exfpl,visibility,entry_fir_eet,oper,oper_time,message_text) VALUES (111,E'UTDD',E'2',E'1',E'1',E'1',0,E'1',E'1',E'1','2013-05-06 12:47:51.000000',E'1',E'1',E'1',E'1',E'1',NULL,NULL,NULL,NULL,NULL,0,NULL,E'1','2013-05-06 12:47:51.000000',NULL);
INSERT INTO msg_from_tan (id,fir_name,aircraft_id,taircraft,frules,tflight,num,wtc,equipment,adep,time,speed,flevel,route,ades,eet,alt1,alt2,other,trtime,exfpl,visibility,entry_fir_eet,oper,oper_time,message_text) VALUES (111,E'UTDD',E'1',E'1',E'1',E'1',0,E'1',E'1',E'1','2013-05-06 12:57:07.000000',E'1',E'1',E'1',E'1',E'1',NULL,NULL,NULL,NULL,NULL,0,NULL,E'I','2013-05-06 12:57:07.000000',NULL);
