-- Generated by Ora2Pg, the Oracle database Schema converter, version 13.0
-- Copyright 2000-2014 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.20.1.81;sid=XE

SET client_encoding TO 'UTF8';

SET search_path = aero, pg_catalog;\set ON_ERROR_STOP ON

SET search_path = aero, pg_catalog;
INSERT INTO notam (id,series,snumber,year,nature,replace_series,replace_snumber,replace_year,fir,subject,condition,traffic,scope,q_lower_limit,q_upper_limit,location,radius,aerodrome,valid_from,valid_until,valid_until_t,schedule,description,lower_limit,upper_limit,sequence_id,state,purpose) VALUES (12773,E'A',946,2010,E'N',NULL,NULL,NULL,E'RKRR',E'PI',E'XX',E'I',E'A',0,999,E'3643N12730E',5,E'RKTU','2010-07-13 02:25:00.000000',NULL,E'PERM',NULL,E'MDA OF RNAV(GNSS) RWY 06L, AIP PART AD : RKTU AD 2-16  MDA READ 620FT INSTEAD OF 650FT IN PROFILE VIEW',NULL,NULL,12773,NULL,E'NBO ');
INSERT INTO notam (id,series,snumber,year,nature,replace_series,replace_snumber,replace_year,fir,subject,condition,traffic,scope,q_lower_limit,q_upper_limit,location,radius,aerodrome,valid_from,valid_until,valid_until_t,schedule,description,lower_limit,upper_limit,sequence_id,state,purpose) VALUES (12774,E'A',947,2010,E'N',NULL,NULL,NULL,E'RKRR',E'PI',E'XX',E'I',E'A',0,999,E'3643N12730E',5,E'RKTU','2010-07-13 02:25:00.000000',NULL,E'PERM',NULL,E'DA OF ILS/DME Z RWY 24R, AIP PART AD : RKTU AD 2-18  DA READ 386FT INSTEAD OF 384FT IN AD OPR MNM.',NULL,NULL,12774,NULL,E'NBO ');
