-- Generated by Ora2Pg, the Oracle database Schema converter, version 13.0
-- Copyright 2000-2014 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.20.1.81;sid=XE

SET client_encoding TO 'UTF8';

SET search_path = aero, pg_catalog;\set ON_ERROR_STOP ON

SET search_path = aero, pg_catalog;
INSERT INTO outputtelegrams (id,created,text,header,message,addresses,processed,send_now,type,fill_time) VALUES (1742,'2013-12-09 08:27:37.565000',E'(FPL-AAAA111-IG
-B737/H-S/C
-XXXX0000
-K0300F300 A B C
-YYYY0000
-)',NULL,NULL,E'EBLGTAYO',0,0,NULL,NULL);
