-- Generated by Ora2Pg, the Oracle database Schema converter, version 13.0
-- Copyright 2000-2014 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.20.1.81;sid=XE

SET client_encoding TO 'UTF8';

SET search_path = aero, pg_catalog;\set ON_ERROR_STOP ON


SET search_path = aero, pg_catalog;
BEGIN;

\i ACTIVATION_output.sql
\i AFTN_ABONENT_output.sql
\i AFTN_ABONENT_AUTOTYPES_output.sql
\i AFTN_ABONENT_GROUP_output.sql
\i AFTN_GROUP_output.sql
\i AIRPLANE_SPEED_output.sql
\i AIRPLANE_TYPE_output.sql
\i AIRPORT_output.sql
\i ARCHIVECOMMANDS_output.sql
\i ARCHIVEINPUTMESSAGES_output.sql
\i ARCHIVEMESSAGES_output.sql
\i ARC_AFTN_output.sql
\i ARINC_CHANGES_output.sql
\i ASTERIX_output.sql
\i BEARING_output.sql
\i BEARING_POINT_output.sql
\i BORDER_TERMS_output.sql
\i BOUNDARY_POINT_TYPE_output.sql
\i CLIENT_output.sql
\i CLIENT_ROLE_output.sql
\i CLIENT_SECTORING_output.sql
\i COMMANDS_output.sql
\i CURRENTSTATISTICS_output.sql
\i CURRENTSTATUS_output.sql
\i ECHELONS_output.sql
\i EQUIPMENT_output.sql
\i EXERCISE_output.sql
\i EXERCISE_CIRCLE_TYPE_output.sql
\i EXERCISE_PLANE_output.sql
\i EXERCISE_STAND_output.sql
\i FFPL_output.sql
\i FLIGHT_RULES_output.sql
\i FLIGHT_TYPES_output.sql
\i FPL_output.sql
\i FPL_ADDITIONAL_output.sql
\i FPL_CFG_output.sql
\i FPL_CHANGES_MASTER_output.sql
\i FPL_MASTER_output.sql
\i FPL_ON_FUTURE_output.sql
\i FPL_STATUS_TYPES_output.sql
\i HIST_FPL_output.sql
\i HIST_MAN_AFTN_output.sql
\i HIST_OUTPUTTELEGRAMS_output.sql
\i HIST_REPORT_output.sql
\i HIST_RPL_output.sql
\i HOLDING_output.sql
\i HOLDING_POINT_MASTER_output.sql
\i HOLDING_TURN_output.sql
\i HOLDING_TYPE_output.sql
\i INPUTMESSAGES_output.sql
\i LEVEL_TYPES_output.sql
\i LOGIN_output.sql
\i LOGIN_LOG_output.sql
\i MAN_AFTN_output.sql
\i METEO_output.sql
\i METEO_AIRPORT_STG_output.sql
\i METEO_POINT_output.sql
\i METEO_RUNWAY_output.sql
\i METEO_TYPE_output.sql
\i MODIFICATION_TYPES_output.sql
\i MSG_FROM_FDP_output.sql
\i MSG_FROM_TAN_output.sql
\i NOTAM_output.sql
\i OLDI_CLIENTS_output.sql
\i OLDI_FPL_output.sql
\i OLDI_SFPL_output.sql
\i OUTPUTMESSAGES_output.sql
\i OUTPUTTELEGRAMS_output.sql
\i POINT_output.sql
\i POINT_TYPE_output.sql
\i RADIO_DEVICES_output.sql
\i RECEIVED_AFTN_output.sql
\i RESTRICTION_output.sql
\i RESTRICTION_POINT_output.sql
\i RESTRICTION_POINT_MASTER_output.sql
\i RESTRICTION_POINT_TYPE_output.sql
\i RESTRICTION_POINT_USER_output.sql
\i RESTRICTION_TYPE_output.sql
\i RESTRICTION_USER_output.sql
\i RESTRICTION_USER_SYNC_output.sql
\i RESTRICTION_USER_TYPE_output.sql
\i RLP_output.sql
\i ROUTE_output.sql
\i ROUTE_POINT_output.sql
\i RPL_output.sql
\i RUNWAY_output.sql
\i SECTORING_output.sql
\i SECTORING_TYPE_output.sql
\i SECTORING_ZONE_output.sql
\i SENT_AFTN_output.sql
\i SERVER_LIST_output.sql
\i SETTINGS_output.sql
\i SFPL_MASTER_TABLE_output.sql
\i SFPL_TABLE_output.sql
\i SPEED_TYPES_output.sql
\i SQUAWK_output.sql
\i SSA_output.sql
\i SSA_POINT_output.sql
\i SSA_POINT_TURN_output.sql
\i SSA_POINT_TYPE_output.sql
\i SSA_TYPE_output.sql
\i STAND_output.sql
\i STAND_STATE_output.sql
\i SYS_TABLES_INFO_output.sql
\i TEMPLATE_ARR_output.sql
\i TEMPLATE_CHG_output.sql
\i TEMPLATE_CNL_output.sql
\i TEMPLATE_DEP_output.sql
\i TEMPLATE_DLA_output.sql
\i TEMPLATE_FPL_output.sql
\i TEMPLATE_FREE_TEXT_output.sql
\i TRASHTELEGRAMS_output.sql
\i TURBULENCE_CATEGORY_output.sql
\i T_MIGRATION_output.sql
\i T_MIGRATION_ORDER_output.sql
\i USERS_output.sql
\i USER_RIGHTS_output.sql
\i VEHICLE_output.sql
\i VEHICLE_EXERCISE_output.sql
\i VEHICLE_PLAN_output.sql
\i VEHICLE_ROUTE_output.sql
\i VEHICLE_ROUTE_POINTS_output.sql
\i WIND_output.sql
\i ZONE_output.sql
\i ZONE_AIRPORT_output.sql
\i ZONE_BOUNDARY_output.sql
\i ZONE_MAP_NOTE_output.sql
\i ZONE_POINT_output.sql
\i ZONE_SCHEDULE_output.sql
\i ZONE_TYPE_output.sql

ALTER SEQUENCE IF EXISTS airport_id_seq RESTART WITH 465;
ALTER SEQUENCE IF EXISTS archivemessages_seq RESTART WITH 58208;
ALTER SEQUENCE IF EXISTS fpl_id_seq RESTART WITH 293709;
ALTER SEQUENCE IF EXISTS hist_man_notam_id_seq RESTART WITH 2;
ALTER SEQUENCE IF EXISTS outputtelegrams_seq RESTART WITH 1762;
ALTER SEQUENCE IF EXISTS restriction_point_id_seq RESTART WITH 6756;
ALTER SEQUENCE IF EXISTS ssa_point_id_seq RESTART WITH 42194;
ALTER SEQUENCE IF EXISTS zone_id_seq RESTART WITH 1297;
ALTER SEQUENCE IF EXISTS stand_seq RESTART WITH 222;
ALTER SEQUENCE IF EXISTS commands_seq RESTART WITH 247;
ALTER SEQUENCE IF EXISTS exercise_id_exercise_seq RESTART WITH 484;
ALTER SEQUENCE IF EXISTS fpl_chain_seq RESTART WITH 22;
ALTER SEQUENCE IF EXISTS hist_man_aftn_id_seq RESTART WITH 25060;
ALTER SEQUENCE IF EXISTS restriction_id_seq RESTART WITH 2089;
ALTER SEQUENCE IF EXISTS restriction_point_master_seq RESTART WITH 15955;
ALTER SEQUENCE IF EXISTS rpl_id_seq RESTART WITH 562;
ALTER SEQUENCE IF EXISTS sectoring_type_seq RESTART WITH 122;
ALTER SEQUENCE IF EXISTS wind_id_seq RESTART WITH 382;
ALTER SEQUENCE IF EXISTS aftn_abonent_autotypes_seq RESTART WITH 2;
ALTER SEQUENCE IF EXISTS template_chg_seq RESTART WITH 2;
ALTER SEQUENCE IF EXISTS template_cnl_seq RESTART WITH 2;
ALTER SEQUENCE IF EXISTS template_dep_seq RESTART WITH 2;
ALTER SEQUENCE IF EXISTS trashtelegrams_seq RESTART WITH 2;
ALTER SEQUENCE IF EXISTS ffpl_id_seq RESTART WITH 505;
ALTER SEQUENCE IF EXISTS route_point_id_seq RESTART WITH 16792;
ALTER SEQUENCE IF EXISTS zone_point_id_seq RESTART WITH 23360;
ALTER SEQUENCE IF EXISTS aftn_group_seq RESTART WITH 42;
ALTER SEQUENCE IF EXISTS aftn_abonent_seq RESTART WITH 342;
ALTER SEQUENCE IF EXISTS template_free_text_seq RESTART WITH 2;
ALTER SEQUENCE IF EXISTS sent_aftn_seq RESTART WITH 2;
ALTER SEQUENCE IF EXISTS arc_aftn_id_seq RESTART WITH 2366;
ALTER SEQUENCE IF EXISTS client_seq RESTART WITH 86;
ALTER SEQUENCE IF EXISTS fpl_master_id_seq RESTART WITH 1456;
ALTER SEQUENCE IF EXISTS hist_rpl_id_seq RESTART WITH 1362;
ALTER SEQUENCE IF EXISTS holding_id_seq RESTART WITH 2009;
ALTER SEQUENCE IF EXISTS meteo_point_id_seq RESTART WITH 342;
ALTER SEQUENCE IF EXISTS point_id_seq RESTART WITH 13680;
ALTER SEQUENCE IF EXISTS runway_id_seq RESTART WITH 1714;
ALTER SEQUENCE IF EXISTS squawk_seq RESTART WITH 5202;
ALTER SEQUENCE IF EXISTS ssa_id_seq RESTART WITH 11872;
ALTER SEQUENCE IF EXISTS aftn_abonent_group_seq RESTART WITH 62;
ALTER SEQUENCE IF EXISTS template_dla_seq RESTART WITH 2;
ALTER SEQUENCE IF EXISTS vehicle_seq RESTART WITH 2;
ALTER SEQUENCE IF EXISTS hist_report_seq RESTART WITH 262;
ALTER SEQUENCE IF EXISTS arc_fpl_id_seq RESTART WITH 2;
ALTER SEQUENCE IF EXISTS holding_point_master_seq RESTART WITH 37306;
ALTER SEQUENCE IF EXISTS meteo_id_seq RESTART WITH 322;
ALTER SEQUENCE IF EXISTS oldi_clients_seq RESTART WITH 2582;
ALTER SEQUENCE IF EXISTS route_id_seq RESTART WITH 4530;
ALTER SEQUENCE IF EXISTS sectoring_seq RESTART WITH 323;
ALTER SEQUENCE IF EXISTS template_fpl_seq RESTART WITH 2;
ALTER SEQUENCE IF EXISTS vehicle_route_seq RESTART WITH 2;
ALTER SEQUENCE IF EXISTS vehicle_plan_seq RESTART WITH 2;
ALTER SEQUENCE IF EXISTS zone_map_note_seq RESTART WITH 2;
ALTER SEQUENCE IF EXISTS airplane_speed_seq RESTART WITH 1034;
ALTER SEQUENCE IF EXISTS arc_notam_id_seq RESTART WITH 8302;
ALTER SEQUENCE IF EXISTS arinc_changes_seq RESTART WITH 462;
ALTER SEQUENCE IF EXISTS inputmessage_seq RESTART WITH 106620;
ALTER SEQUENCE IF EXISTS man_aftn_id_seq RESTART WITH 14526;
ALTER SEQUENCE IF EXISTS zone_airport_id_seq RESTART WITH 623;
ALTER SEQUENCE IF EXISTS exercise_stand_seq RESTART WITH 1842;
ALTER SEQUENCE IF EXISTS vehicle_exercise_seq RESTART WITH 2;
ALTER SEQUENCE IF EXISTS client_role_seq RESTART WITH 63;
ALTER SEQUENCE IF EXISTS client_sectoring_seq RESTART WITH 472;
ALTER SEQUENCE IF EXISTS currentstatistics_seq RESTART WITH 102;
ALTER SEQUENCE IF EXISTS man_notam_id_seq RESTART WITH 2;
ALTER SEQUENCE IF EXISTS users_id_seq RESTART WITH 266;
ALTER SEQUENCE IF EXISTS user_rights_id_seq RESTART WITH 336;
ALTER SEQUENCE IF EXISTS hist_outputtelegrams_seq RESTART WITH 1662;
ALTER SEQUENCE IF EXISTS vehicle_route_points_seq RESTART WITH 2;
ALTER SEQUENCE IF EXISTS archivecommands_seq RESTART WITH 237;
ALTER SEQUENCE IF EXISTS asterix_seq RESTART WITH 1102;
ALTER SEQUENCE IF EXISTS bearing_point_seq RESTART WITH 62;
ALTER SEQUENCE IF EXISTS currentstatus_seq RESTART WITH 1256;
ALTER SEQUENCE IF EXISTS hist_fpl_id_seq RESTART WITH 1965;
ALTER SEQUENCE IF EXISTS notam_id_seq RESTART WITH 12794;
ALTER SEQUENCE IF EXISTS rlp_id_seq RESTART WITH 2;
ALTER SEQUENCE IF EXISTS sectoring_zone_seq RESTART WITH 2111;
ALTER SEQUENCE IF EXISTS zone_boundary_seq RESTART WITH 33982;
ALTER SEQUENCE IF EXISTS received_aftn_seq RESTART WITH 242;
COMMIT;

