-- Generated by Ora2Pg, the Oracle database Schema converter, version 13.0
-- Copyright 2000-2014 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.20.1.81;sid=XE

SET client_encoding TO 'UTF8';

SET search_path = aero, pg_catalog;\set ON_ERROR_STOP ON

SET search_path = aero, pg_catalog;
INSERT INTO outputmessages (msgid,msgtime,msgfrom,msgto,msgtext,msgtype,msgstatus) VALUES (106611,'2014-06-24 12:34:55.442000',E'CWPA',E'FDP',E'(STSCWPA/FDP003-0-CWPA)',E'STS',0);
INSERT INTO outputmessages (msgid,msgtime,msgfrom,msgto,msgtext,msgtype,msgstatus) VALUES (106612,'2014-06-24 12:34:56.625000',E'CWPA',E'FDP',E'(STSCWPA/FDP004-0-CWPA-TSE1)',E'STS',0);
INSERT INTO outputmessages (msgid,msgtime,msgfrom,msgto,msgtext,msgtype,msgstatus) VALUES (106613,'2014-06-24 12:34:57.044000',E'CWPA',E'FDP',E'(STSCWPA/FDP005-0-CWPA)',E'STS',0);
INSERT INTO outputmessages (msgid,msgtime,msgfrom,msgto,msgtext,msgtype,msgstatus) VALUES (106614,'2014-06-24 12:35:06.667000',E'CWPA',E'FDP',E'(STSCWPA/FDP006-0-CWPA-TSE1)',E'STS',0);
INSERT INTO outputmessages (msgid,msgtime,msgfrom,msgto,msgtext,msgtype,msgstatus) VALUES (106615,'2014-06-24 12:36:02.651000',E'CWPA',E'FDP',E'(INFCWPA/FDP007-FPL- - - - - )',E'INF',0);
INSERT INTO outputmessages (msgid,msgtime,msgfrom,msgto,msgtext,msgtype,msgstatus) VALUES (106609,'2014-06-24 12:34:54.962000',E'CWPA',E'FDP',E'(INFCWPA/FDP001-FPL- - - - - )',E'INF',0);
INSERT INTO outputmessages (msgid,msgtime,msgfrom,msgto,msgtext,msgtype,msgstatus) VALUES (106610,'2014-06-24 12:34:55.410000',E'CWPA',E'FDP',E'(STSCWPA/FDP002-0-CWPA)',E'STS',0);
INSERT INTO outputmessages (msgid,msgtime,msgfrom,msgto,msgtext,msgtype,msgstatus) VALUES (106616,'2014-06-24 12:40:23.303000',E'CWPA',E'FDP',E'(INFCWPA/FDP008-FPL- - - - - )',E'INF',0);
INSERT INTO outputmessages (msgid,msgtime,msgfrom,msgto,msgtext,msgtype,msgstatus) VALUES (106617,'2014-06-24 12:42:41.773000',E'CWPA',E'FDP',E'(INFCWPA/FDP009-FPL- - - - - )',E'INF',0);
INSERT INTO outputmessages (msgid,msgtime,msgfrom,msgto,msgtext,msgtype,msgstatus) VALUES (106618,'2014-06-24 12:42:54.968000',E'CWPA',E'FDP',E'(STSCWPA/FDP010-0-CWPA)',E'STS',0);
