-- Generated by Ora2Pg, the Oracle database Schema converter, version 13.0
-- Copyright 2000-2014 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.20.1.81;sid=XE

SET client_encoding TO 'UTF8';

SET search_path = aero, pg_catalog;\set ON_ERROR_STOP ON

SET search_path = aero, pg_catalog;
INSERT INTO restriction_point_user (id,sn,type,latitude,longitude,arc_latitude,arc_longitude,arc_distance,restriction_id) VALUES (6675,10,67,0,0,39.78479004,59.26826512,94904.7929716935,2008);
INSERT INTO restriction_point_user (id,sn,type,latitude,longitude,arc_latitude,arc_longitude,arc_distance,restriction_id) VALUES (6676,40,71,39.23350234,62.1593873,0,0,0,2009);
INSERT INTO restriction_point_user (id,sn,type,latitude,longitude,arc_latitude,arc_longitude,arc_distance,restriction_id) VALUES (6677,30,71,37.60685216,65.26736982,0,0,0,2009);
INSERT INTO restriction_point_user (id,sn,type,latitude,longitude,arc_latitude,arc_longitude,arc_distance,restriction_id) VALUES (6678,20,71,39.22441558,65.43227358,0,0,0,2009);
INSERT INTO restriction_point_user (id,sn,type,latitude,longitude,arc_latitude,arc_longitude,arc_distance,restriction_id) VALUES (6679,10,71,37.72625167,62.19504504,0,0,0,2009);
INSERT INTO restriction_point_user (id,sn,type,latitude,longitude,arc_latitude,arc_longitude,arc_distance,restriction_id) VALUES (6681,40,71,42.08814553,63.84232255,0,0,0,2011);
INSERT INTO restriction_point_user (id,sn,type,latitude,longitude,arc_latitude,arc_longitude,arc_distance,restriction_id) VALUES (6682,30,71,42.38753313,65.02850285,0,0,0,2011);
INSERT INTO restriction_point_user (id,sn,type,latitude,longitude,arc_latitude,arc_longitude,arc_distance,restriction_id) VALUES (6683,20,71,42.70441042,62.74728828,0,0,0,2011);
INSERT INTO restriction_point_user (id,sn,type,latitude,longitude,arc_latitude,arc_longitude,arc_distance,restriction_id) VALUES (6684,10,71,43.29735052,64.66827971,0,0,0,2011);
INSERT INTO restriction_point_user (id,sn,type,latitude,longitude,arc_latitude,arc_longitude,arc_distance,restriction_id) VALUES (6685,10,67,0,0,41.71312269,64.64819372,28382.9125531542,2010);
INSERT INTO restriction_point_user (id,sn,type,latitude,longitude,arc_latitude,arc_longitude,arc_distance,restriction_id) VALUES (6695,10,67,0,0,44.32598184,67.99476126,83035.2224059164,2028);
INSERT INTO restriction_point_user (id,sn,type,latitude,longitude,arc_latitude,arc_longitude,arc_distance,restriction_id) VALUES (6615,10,67,0,0,45.5443818,52.25951911,426791.893175116,1948);
INSERT INTO restriction_point_user (id,sn,type,latitude,longitude,arc_latitude,arc_longitude,arc_distance,restriction_id) VALUES (6593,10,67,0,0,40.65459604,66.58558852,681498.093907826,1906);
INSERT INTO restriction_point_user (id,sn,type,latitude,longitude,arc_latitude,arc_longitude,arc_distance,restriction_id) VALUES (6575,10,67,0,0,39.04753972,69.56300035,11023.1750417019,1887);
INSERT INTO restriction_point_user (id,sn,type,latitude,longitude,arc_latitude,arc_longitude,arc_distance,restriction_id) VALUES (6613,10,67,0,0,42.69736053,73.26815698,258404.437763751,1926);
INSERT INTO restriction_point_user (id,sn,type,latitude,longitude,arc_latitude,arc_longitude,arc_distance,restriction_id) VALUES (6614,10,67,0,0,39.96449098,73.30116392,393313.360312105,1927);
INSERT INTO restriction_point_user (id,sn,type,latitude,longitude,arc_latitude,arc_longitude,arc_distance,restriction_id) VALUES (6655,10,67,0,0,40.52138856,64.8173318,33946.1145051978,1988);
INSERT INTO restriction_point_user (id,sn,type,latitude,longitude,arc_latitude,arc_longitude,arc_distance,restriction_id) VALUES (6656,10,67,0,0,40.24370507,65.85038921,51933,1989);
INSERT INTO restriction_point_user (id,sn,type,latitude,longitude,arc_latitude,arc_longitude,arc_distance,restriction_id) VALUES (6657,10,67,0,0,40.11423336,66.66661254,15859,1990);
INSERT INTO restriction_point_user (id,sn,type,latitude,longitude,arc_latitude,arc_longitude,arc_distance,restriction_id) VALUES (6715,10,67,0,0,42.24305606,66.3883647,27193.3058858242,2048);
INSERT INTO restriction_point_user (id,sn,type,latitude,longitude,arc_latitude,arc_longitude,arc_distance,restriction_id) VALUES (6716,10,67,0,0,41.85858357,66.26343743,40851.1675475745,2051);
INSERT INTO restriction_point_user (id,sn,type,latitude,longitude,arc_latitude,arc_longitude,arc_distance,restriction_id) VALUES (6717,10,67,0,0,42.33903215,64.76571379,27192.6438949948,2052);
INSERT INTO restriction_point_user (id,sn,type,latitude,longitude,arc_latitude,arc_longitude,arc_distance,restriction_id) VALUES (6718,10,67,0,0,42.25775854,64.73698354,19787.1922717701,2053);
INSERT INTO restriction_point_user (id,sn,type,latitude,longitude,arc_latitude,arc_longitude,arc_distance,restriction_id) VALUES (6735,10,67,0,0,41.67917716,66.9389081,56059.4450650379,2070);
