-- Generated by Ora2Pg, the Oracle database Schema converter, version 13.0
-- Copyright 2000-2014 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.20.1.81;sid=XE

SET client_encoding TO 'UTF8';

SET search_path = aero, pg_catalog;\set ON_ERROR_STOP ON

SET search_path = aero, pg_catalog;
INSERT INTO restriction_user (id,name,zone_id,h_min,h_max,time_start,time_end,type,guid) VALUES (2011,E'5',978,NULL,NULL,'2000-01-01 00:00:00.000000','2010-01-01 00:00:00.000000',91,E'{2dc69a98-8499-4c2d-865f-86172b7d5f10}');
INSERT INTO restriction_user (id,name,zone_id,h_min,h_max,time_start,time_end,type,guid) VALUES (2028,E'123',1085,NULL,NULL,NULL,'2010-01-01 00:00:00.000000',91,E'{5cb9cbc8-2ae5-4801-9e58-ae20892a4318}');
INSERT INTO restriction_user (id,name,zone_id,h_min,h_max,time_start,time_end,type,guid) VALUES (2010,E'4',978,NULL,NULL,'2000-01-01 00:00:00.000000','2010-01-01 00:00:00.000000',91,E'{707db45c-c214-4b46-a0d7-a271f092aac2}');
INSERT INTO restriction_user (id,name,zone_id,h_min,h_max,time_start,time_end,type,guid) VALUES (1990,E'3',978,0,0,'2013-01-23 13:15:34.000000','2015-01-23 13:15:34.000000',65,E'{70243726-f2e7-414c-a2ea-20e2a20dd777}');
INSERT INTO restriction_user (id,name,zone_id,h_min,h_max,time_start,time_end,type,guid) VALUES (1988,E'1',978,0,0,'2013-01-23 13:12:08.000000','2015-01-23 13:12:08.000000',90,E'{51d49bd0-bc58-45f9-b1a7-ca293499ce74}');
INSERT INTO restriction_user (id,name,zone_id,h_min,h_max,time_start,time_end,type,guid) VALUES (1989,E'2',978,0,0,'2013-01-23 13:13:06.000000','2015-01-23 13:13:06.000000',79,E'{64dc8be2-d8c3-4db6-b1c8-b7d5b6f642e9}');
