-- Generated by Ora2Pg, the Oracle database Schema converter, version 13.0
-- Copyright 2000-2014 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.20.1.81;sid=XE

SET client_encoding TO 'UTF8';

SET search_path = aero, pg_catalog;\set ON_ERROR_STOP ON

SET search_path = aero, pg_catalog;
INSERT INTO restriction_user_sync (id,type,lasttouch) VALUES (2056,0,'2013-05-16 10:28:05.071000');
INSERT INTO restriction_user_sync (id,type,lasttouch) VALUES (2068,0,'2013-05-16 10:34:13.281000');
INSERT INTO restriction_user_sync (id,type,lasttouch) VALUES (2069,0,'2013-05-16 10:54:04.036000');
INSERT INTO restriction_user_sync (id,type,lasttouch) VALUES (2070,0,'2013-05-16 11:19:34.122000');
INSERT INTO restriction_user_sync (id,type,lasttouch) VALUES (2071,0,'2013-05-16 11:46:01.292000');
INSERT INTO restriction_user_sync (id,type,lasttouch) VALUES (2072,0,'2013-05-16 13:08:37.111000');
INSERT INTO restriction_user_sync (id,type,lasttouch) VALUES (2073,0,'2013-05-16 13:11:52.556000');
