-- Generated by Ora2Pg, the Oracle database Schema converter, version 13.0
-- Copyright 2000-2014 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.20.1.81;sid=XE

SET client_encoding TO 'UTF8';

SET search_path = aero, pg_catalog;\set ON_ERROR_STOP ON

SET search_path = aero, pg_catalog;
INSERT INTO sectoring_zone (id,sect_id,zone_id,main_fir) VALUES (2094,283,978,0);
INSERT INTO sectoring_zone (id,sect_id,zone_id,main_fir) VALUES (2095,283,981,0);
INSERT INTO sectoring_zone (id,sect_id,zone_id,main_fir) VALUES (2096,284,978,0);
INSERT INTO sectoring_zone (id,sect_id,zone_id,main_fir) VALUES (2097,284,980,0);
INSERT INTO sectoring_zone (id,sect_id,zone_id,main_fir) VALUES (2098,302,984,0);
INSERT INTO sectoring_zone (id,sect_id,zone_id,main_fir) VALUES (2099,302,978,0);
