-- Generated by Ora2Pg, the Oracle database Schema converter, version 13.0
-- Copyright 2000-2014 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.20.1.81;sid=XE

SET client_encoding TO 'UTF8';

SET search_path = aero, pg_catalog;\set ON_ERROR_STOP ON

SET search_path = aero, pg_catalog;
INSERT INTO sectoring_type (id,name,permission) VALUES (101,E'Ground',E'Aerodrome (ground taxiing); List ACC; List SIL APP ARR; List SIL APP DEP; Toolbox time; Toolbox ground taxiing; ');
INSERT INTO sectoring_type (id,name,permission) VALUES (81,E'ACC',E'Toolbox time; Toolbox pressure/level; Toolbox aiplane/Length; Toolbox custom sector; Toolbox altitude filter; Toolbox user restrictions; List ACC; List SIL ACC; List SIL APP DEP; Toolbox ground taxiing; ');
INSERT INTO sectoring_type (id,name,permission) VALUES (82,E'APP',E'List SIL APP DEP; Toolbox time; Toolbox pressure/level; List APP; List SIL APP ARR; Toolbox aiplane/Length; Toolbox custom sector; Toolbox altitude filter; Toolbox user restrictions; ');
