-- Generated by Ora2Pg, the Oracle database Schema converter, version 13.0
-- Copyright 2000-2014 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.20.1.81;sid=XE

SET client_encoding TO 'UTF8';

SET search_path = aero, pg_catalog;\set ON_ERROR_STOP ON

SET search_path = aero, pg_catalog;
INSERT INTO settings (key,value) VALUES (E'cks_is_connected',E'\\000\\000\\000\\001\\000\\000');
INSERT INTO settings (key,value) VALUES (E'auto_answer_on_error',E'\\000\\000\\000\\002\\000\\000\\000\\000\\000');
INSERT INTO settings (key,value) VALUES (E'telegram_next_num_net',E'\\000\\000\\000\\002\\000\\000\\000\\000\\004');
