-- Generated by Ora2Pg, the Oracle database Schema converter, version 13.0
-- Copyright 2000-2014 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.20.1.81;sid=XE

SET client_encoding TO 'UTF8';

SET search_path = aero, pg_catalog;\set ON_ERROR_STOP ON

SET search_path = aero, pg_catalog;
INSERT INTO ssa_point_type (id,name) VALUES (0,E'Unknown');
INSERT INTO ssa_point_type (id,name) VALUES (1,E'IF');
INSERT INTO ssa_point_type (id,name) VALUES (2,E'TF');
INSERT INTO ssa_point_type (id,name) VALUES (3,E'CF');
INSERT INTO ssa_point_type (id,name) VALUES (4,E'DF');
INSERT INTO ssa_point_type (id,name) VALUES (5,E'CA');
INSERT INTO ssa_point_type (id,name) VALUES (6,E'CI');
