-- Generated by Ora2Pg, the Oracle database Schema converter, version 13.0
-- Copyright 2000-2014 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.20.1.81;sid=XE

SET client_encoding TO 'UTF8';

SET search_path = aero, pg_catalog;\set ON_ERROR_STOP ON

SET search_path = aero, pg_catalog;
INSERT INTO ssa_type (id,name) VALUES (4,E'VA');
INSERT INTO ssa_type (id,name) VALUES (5,E'MA');
INSERT INTO ssa_type (id,name) VALUES (0,E'Unknown');
INSERT INTO ssa_type (id,name) VALUES (1,E'SID');
INSERT INTO ssa_type (id,name) VALUES (2,E'STAR');
INSERT INTO ssa_type (id,name) VALUES (3,E'Approach');
