-- Generated by Ora2Pg, the Oracle database Schema converter, version 13.0
-- Copyright 2000-2014 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.20.1.81;sid=XE

SET client_encoding TO 'UTF8';

SET search_path = aero, pg_catalog;\set ON_ERROR_STOP ON

SET search_path = aero, pg_catalog;
INSERT INTO stand_state (id,name) VALUES (0,E'Free');
INSERT INTO stand_state (id,name) VALUES (1,E'Occupied');
INSERT INTO stand_state (id,name) VALUES (2,E'Closed');
