-- Generated by Ora2Pg, the Oracle database Schema converter, version 13.0
-- Copyright 2000-2014 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.20.1.81;sid=XE

SET client_encoding TO 'UTF8';

SET search_path = aero, pg_catalog;\set ON_ERROR_STOP ON

SET search_path = aero, pg_catalog;
INSERT INTO user_rights (id,user_id,object_id,rights) VALUES (295,205,E'RplBrowser',2);
INSERT INTO user_rights (id,user_id,object_id,rights) VALUES (315,205,E'NotamBrowser',0);
INSERT INTO user_rights (id,user_id,object_id,rights) VALUES (316,205,E'UserAccountsDialog',2);
INSERT INTO user_rights (id,user_id,object_id,rights) VALUES (317,205,E'AFTNServiceLog',2);
INSERT INTO user_rights (id,user_id,object_id,rights) VALUES (318,205,E'UserActionsBrowserHelper',2);
