-- Generated by Ora2Pg, the Oracle database Schema converter, version 13.0
-- Copyright 2000-2014 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.20.1.81;sid=XE

SET client_encoding TO 'UTF8';

SET search_path = aero, pg_catalog;\set ON_ERROR_STOP ON

SET search_path = aero, pg_catalog;
INSERT INTO users (id,created,user_name,password,isactive,lasttouch,fullname,addressbook,edittable) VALUES (0,'2010-11-25 11:09:45.953000',E'aftnservice',NULL,2,'2010-11-25 11:10:35.435000',NULL,NULL,NULL);
INSERT INTO users (id,created,user_name,password,isactive,lasttouch,fullname,addressbook,edittable) VALUES (1,'2010-07-19 10:21:55.000000',E'admin',E'0f6d0c59454c7947e2b8ad7398d4ec07',1,'2011-01-19 16:29:40.000000',E'Филоненко Михаил',1,1);
INSERT INTO users (id,created,user_name,password,isactive,lasttouch,fullname,addressbook,edittable) VALUES (205,'2012-02-08 14:12:12.000000',E'1111',E'39ced56a4641b5a31828e8b72c7195f3',1,'2012-02-08 14:12:12.000000',NULL,NULL,NULL);
INSERT INTO users (id,created,user_name,password,isactive,lasttouch,fullname,addressbook,edittable) VALUES (225,'2012-11-01 12:51:48.676000',E'empty',E'39ced56a4641b5a31828e8b72c7195f3',1,'2012-11-01 12:51:48.676000',NULL,NULL,NULL);
