-- Generated by Ora2Pg, the Oracle database Schema converter, version 13.0
-- Copyright 2000-2014 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.20.1.81;sid=XE

SET client_encoding TO 'UTF8';

SET search_path = aero, pg_catalog;\set ON_ERROR_STOP ON

SET search_path = aero, pg_catalog;
INSERT INTO zone_airport (id,zone_id,airport_id) VALUES (422,978,304);
INSERT INTO zone_airport (id,zone_id,airport_id) VALUES (423,978,305);
INSERT INTO zone_airport (id,zone_id,airport_id) VALUES (424,978,306);
INSERT INTO zone_airport (id,zone_id,airport_id) VALUES (425,978,307);
INSERT INTO zone_airport (id,zone_id,airport_id) VALUES (426,978,308);
INSERT INTO zone_airport (id,zone_id,airport_id) VALUES (482,1116,309);
INSERT INTO zone_airport (id,zone_id,airport_id) VALUES (483,1116,310);
INSERT INTO zone_airport (id,zone_id,airport_id) VALUES (484,1116,311);
INSERT INTO zone_airport (id,zone_id,airport_id) VALUES (485,1116,312);
INSERT INTO zone_airport (id,zone_id,airport_id) VALUES (486,1116,313);
INSERT INTO zone_airport (id,zone_id,airport_id) VALUES (487,1116,314);
INSERT INTO zone_airport (id,zone_id,airport_id) VALUES (488,1116,315);
INSERT INTO zone_airport (id,zone_id,airport_id) VALUES (470,1085,352);
INSERT INTO zone_airport (id,zone_id,airport_id) VALUES (442,1016,324);
INSERT INTO zone_airport (id,zone_id,airport_id) VALUES (443,1016,325);
INSERT INTO zone_airport (id,zone_id,airport_id) VALUES (444,1016,326);
INSERT INTO zone_airport (id,zone_id,airport_id) VALUES (445,1016,327);
INSERT INTO zone_airport (id,zone_id,airport_id) VALUES (446,1016,328);
INSERT INTO zone_airport (id,zone_id,airport_id) VALUES (447,1016,329);
INSERT INTO zone_airport (id,zone_id,airport_id) VALUES (448,1016,330);
INSERT INTO zone_airport (id,zone_id,airport_id) VALUES (449,1016,331);
INSERT INTO zone_airport (id,zone_id,airport_id) VALUES (450,1016,332);
INSERT INTO zone_airport (id,zone_id,airport_id) VALUES (451,1016,333);
INSERT INTO zone_airport (id,zone_id,airport_id) VALUES (452,1016,334);
INSERT INTO zone_airport (id,zone_id,airport_id) VALUES (453,1016,335);
INSERT INTO zone_airport (id,zone_id,airport_id) VALUES (454,1016,336);
INSERT INTO zone_airport (id,zone_id,airport_id) VALUES (455,1016,337);
INSERT INTO zone_airport (id,zone_id,airport_id) VALUES (456,1016,338);
INSERT INTO zone_airport (id,zone_id,airport_id) VALUES (457,1016,339);
INSERT INTO zone_airport (id,zone_id,airport_id) VALUES (458,1016,340);
INSERT INTO zone_airport (id,zone_id,airport_id) VALUES (459,1016,341);
INSERT INTO zone_airport (id,zone_id,airport_id) VALUES (469,1085,351);
INSERT INTO zone_airport (id,zone_id,airport_id) VALUES (472,1089,354);
INSERT INTO zone_airport (id,zone_id,airport_id) VALUES (477,1098,355);
INSERT INTO zone_airport (id,zone_id,airport_id) VALUES (462,1076,344);
INSERT INTO zone_airport (id,zone_id,airport_id) VALUES (463,1076,345);
INSERT INTO zone_airport (id,zone_id,airport_id) VALUES (464,1076,346);
INSERT INTO zone_airport (id,zone_id,airport_id) VALUES (465,1076,347);
INSERT INTO zone_airport (id,zone_id,airport_id) VALUES (466,1076,348);
INSERT INTO zone_airport (id,zone_id,airport_id) VALUES (467,1076,349);
INSERT INTO zone_airport (id,zone_id,airport_id) VALUES (468,1076,350);
INSERT INTO zone_airport (id,zone_id,airport_id) VALUES (471,1089,353);
INSERT INTO zone_airport (id,zone_id,airport_id) VALUES (582,1116,424);
INSERT INTO zone_airport (id,zone_id,airport_id) VALUES (602,1276,356);
INSERT INTO zone_airport (id,zone_id,airport_id) VALUES (603,1276,357);
INSERT INTO zone_airport (id,zone_id,airport_id) VALUES (604,1276,358);
INSERT INTO zone_airport (id,zone_id,airport_id) VALUES (605,1276,444);
