#include "NewPassword.h"
#include <QMessageBox>

NewPassword::NewPassword(QWidget* pParent)
	: QDialog(pParent)
{
	setupUi(this);

	PassEdit1->setFocus();
}

QString NewPassword::password() const
{
	return PassEdit1->text();
}

void NewPassword::accept()
{
	if (PassEdit1->text() != PassEdit2->text())
	{
		QMessageBox::critical(this, tr("Error"), tr("Passwords do not match. Please try again"));

		PassEdit1->clear();
		PassEdit2->clear();
		PassEdit1->setFocus();
	} else
		QDialog::accept();
}


void NewPassword::changeEvent(QEvent *event)
{
    //LanguageChange events should not be confused with LocaleChange events.
    if (event->type() == QEvent::LocaleChange)
    {
        // HERE we can un|install qtranslator
        //    Locale-Change events are generated by the system and tell the application,
        //    "Maybe you should load a new translation."
    }
    else if (event->type() == QEvent::LanguageChange)
    {
        //    LanguageChange events are generated by Qt and tell the application's widgets,
        //    "Maybe you should retranslate all your strings."
        retranslateUi(this);
    }

    QDialog::changeEvent(event);
}
