-- Generated by Ora2Pg, the Oracle database Schema converter, version 13.0
-- Copyright 2000-2014 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.20.1.81;sid=XE

SET client_encoding TO 'UTF8';

SET search_path = aero, pg_catalog;\set ON_ERROR_STOP ON

\i POINT_VIEW_output.sql
\i VW_FPL_output.sql
\i VW_FPL_WITH_NULL_output.sql
\i VW_SECTORING_output.sql

