-- Generated by Ora2Pg, the Oracle database Schema converter, version 13.0
-- Copyright 2000-2014 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.20.1.81;sid=XE

SET client_encoding TO 'UTF8';

SET search_path = aero, pg_catalog;\set ON_ERROR_STOP ON

CREATE OR REPLACE VIEW point_view (id, icao, type, name, latitude, longitude, airport) AS SELECT  id, icao, type, name, latitude, longitude, airport 
 FROM point
UNION 
select 0, '', 100, '_NULL_', 0, 0, ''
;
