-- Generated by Ora2Pg, the Oracle database Schema converter, version 13.0
-- Copyright 2000-2014 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.20.1.81;sid=XE

SET client_encoding TO 'UTF8';

SET search_path = aero, pg_catalog;\set ON_ERROR_STOP ON

CREATE OR REPLACE VIEW vw_fpl (id, fir_name, aircraft_id, taircraft, frules, tflight, num, wtc, equipment, adep, time, speed, flevel, route, ades, eet, alt1, alt2, other, trtime, exfpl, visibility, message_id, entry_fir_eet, additional_info) AS SELECT  fpl.*, fpl_additional.additional_info
	 FROM fpl
	INNER JOIN fpl_additional ON fpl_id_ref = id;

