-- Generated by Ora2Pg, the Oracle database Schema converter, version 13.0
-- Copyright 2000-2014 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.20.1.81;sid=XE

SET client_encoding TO 'UTF8';

SET search_path = aero, pg_catalog;\set ON_ERROR_STOP ON

CREATE OR REPLACE VIEW vw_fpl_with_null (id, aircraft_id) AS SELECT  id, aircraft_id 
    FROM fpl
UNION
   select null id, '(empty)' aircraft_id 
   ;

