-- Generated by Ora2Pg, the Oracle database Schema converter, version 13.0
-- Copyright 2000-2014 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.20.1.81;sid=XE

SET client_encoding TO 'UTF8';

SET search_path = aero, pg_catalog;\set ON_ERROR_STOP ON

CREATE OR REPLACE VIEW vw_sectoring (id, name, type_id) AS SELECT  id, name, type_id
	 FROM sectoring 
UNION
	SELECT 0, NULL, 0
	
UNION
	SELECT -1, NULL, 0
	
ORDER BY name;

