CREATE OR REPLACE TRIGGER SSA_POINT_PSEUDO_FK 
      AFTER DELETE ON POINT FOR EACH ROW
BEGIN
   UPDATE SSA_POINT SET POINT_ID = 0 WHERE POINT_ID = :old.ID;
END;
/
ALTER TRIGGER SSA_POINT_PSEUDO_FK ENABLE;
