ALTER TABLE SFPL_MASTER_TABLE 
ADD (EXFPL CHAR(1 BYTE) );

ALTER TABLE SFPL_MASTER_TABLE 
ADD (ENTRY_FIR_EET VARCHAR2(5 BYTE) );

ALTER TABLE SFPL_MASTER_TABLE  
MODIFY (TRTIME TIMESTAMP(6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) );

ALTER TABLE SFPL_MASTER_TABLE  
MODIFY (TIME TIMESTAMP(6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) );

ALTER TABLE SFPL_MASTER_TABLE  
MODIFY (EET DEFAULT NULL );
