DROP TABLE METEO_TYPE;
CREATE TABLE "METEO_TYPE" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"FULL_NAME" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "METEO_TYPE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
  
REM INSERTING into METEO_TYPE
Insert into METEO_TYPE (ID,NAME,FULL_NAME) values (0,'LVN','Cloudburst');
Insert into METEO_TYPE (ID,NAME,FULL_NAME) values (1,'(R)','LoStorm');
Insert into METEO_TYPE (ID,NAME,FULL_NAME) values (2,'R)','MedStorm');
Insert into METEO_TYPE (ID,NAME,FULL_NAME) values (3,'R','HiStorm');
Insert into METEO_TYPE (ID,NAME,FULL_NAME) values (4,'G','Hail');
Insert into METEO_TYPE (ID,NAME,FULL_NAME) values (5,'H00','Squall');
 
DELETE FROM METEO;
commit;

ALTER TABLE METEO  
MODIFY (TYPE NUMBER );

ALTER TABLE METEO
ADD CONSTRAINT METEO_METEO_TYPE_FK1 FOREIGN KEY
(
  TYPE 
)
REFERENCES METEO_TYPE
(
  ID 
)
ON DELETE CASCADE ENABLE;
