ALTER TABLE MAN_AFTN 
ADD (TYPE VARCHAR2(10 CHAR) );

ALTER TABLE MAN_AFTN 
ADD (SENDER VARCHAR2(8 CHAR) );

ALTER TABLE MAN_AFTN 
ADD (FILL_TIME VARCHAR2(6 CHAR) );

ALTER TABLE RECEIVED_AFTN 
ADD (TYPE VARCHAR2(10 CHAR) );

ALTER TABLE RECEIVED_AFTN 
ADD (SENDER VARCHAR2(8 CHAR) );

ALTER TABLE RECEIVED_AFTN 
ADD (FILL_TIME VARCHAR2(6 CHAR) );


ALTER TABLE SENT_AFTN 
ADD (TYPE VARCHAR2(10 CHAR) );

ALTER TABLE SENT_AFTN 
ADD (SERIAL_NUMBER VARCHAR2(10 CHAR) );

ALTER TABLE SENT_AFTN 
ADD (FILL_TIME VARCHAR2(6 CHAR) );

ALTER TABLE OUTPUTTELEGRAMS 
ADD (TYPE VARCHAR2(10 CHAR) );

ALTER TABLE OUTPUTTELEGRAMS 
ADD (FILL_TIME VARCHAR2(6 CHAR) );