-- Generated by Ora2Pg, the Oracle database Schema converter, version 13.0
-- Copyright 2000-2014 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.20.1.81;sid=XE

SET client_encoding TO 'UTF8';

SET search_path = aero, pg_catalog;\set ON_ERROR_STOP ON

DROP TRIGGER IF EXISTS airport_ac ON airport CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_airport_ac () RETURNS trigger AS $BODY$
DECLARE
	ac_flag numeric;

BEGIN
	ac_flag := sys_context('CLIENTCONTEXT', 'ARINC_CHANGES_FLAG');
	IF ac_flag = 777 THEN
		--DELETE
		IF TG_OP = 'DELETE' THEN
			INSERT INTO ARINC_CHANGES(STATEMENT)
			VALUES
			('DELETE FROM AIRPORT WHERE ICAO = ''' || OLD.ICAO || ''' AND NAME = ''' || OLD.NAME || '''');
		ELSE
			--INSERT
			IF TG_OP = 'INSERT' THEN
				INSERT INTO ARINC_CHANGES(STATEMENT)
				VALUES
				('INSERT INTO AIRPORT(ICAO, NAME, LATITUDE, LONGITUDE, ALTITUDE, DECLINATION) ' ||
					'VALUES(''' || NEW.ICAO || ''', ''' || NEW.NAME || ''', ''' || NEW.LATITUDE || ''', ''' || NEW.LONGITUDE || ''', ''' || NEW.ALTITUDE || ''', ''' || NEW.DECLINATION || ''')');
			--UPDATE
			ELSE
				INSERT INTO ARINC_CHANGES(STATEMENT)
				VALUES
				('UPDATE AIRPORT SET ' ||
					'ICAO = ''' || NEW.ICAO || ''', ' ||
					'NAME = ''' || NEW.NAME || ''', ' ||
					'LATITUDE = ''' || NEW.LATITUDE || ''', ' ||
					'LONGITUDE = ''' || NEW.LONGITUDE || ''', ' ||
          'ALTITUDE = ''' || NEW.ALTITUDE || ''', ' ||
					'DECLINATION = ''' || NEW.DECLINATION || ''' ' ||
					'WHERE ICAO = ''' || OLD.ICAO || ''' AND NAME = ''' || OLD.NAME || '''');
			END IF;
		END IF;
	END IF;
RETURN NEW;
END
$BODY$
 LANGUAGE 'plpgsql';

CREATE TRIGGER airport_ac
	AFTER INSERT OR UPDATE OR DELETE ON airport FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_airport_ac();

