-- Generated by Ora2Pg, the Oracle database Schema converter, version 13.0
-- Copyright 2000-2014 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.20.1.81;sid=XE

SET client_encoding TO 'UTF8';

SET search_path = aero, pg_catalog;\set ON_ERROR_STOP ON

DROP TRIGGER IF EXISTS bearing_point_trg ON bearing_point CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_bearing_point_trg () RETURNS trigger AS $BODY$
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    SELECT nextval('bearing_point_seq') INTO NEW.ID ;
  END COLUMN_SEQUENCES;
RETURN NEW;
END
$BODY$
 LANGUAGE 'plpgsql';

CREATE TRIGGER bearing_point_trg
	BEFORE INSERT ON bearing_point FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_bearing_point_trg();

