-- Generated by Ora2Pg, the Oracle database Schema converter, version 13.0
-- Copyright 2000-2014 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.20.1.81;sid=XE

SET client_encoding TO 'UTF8';

SET search_path = aero, pg_catalog;\set ON_ERROR_STOP ON

DROP TRIGGER IF EXISTS bi_archivecommands ON archivecommands CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_bi_archivecommands () RETURNS trigger AS $BODY$
begin   
    SELECT "ARCHIVECOMMANDS_SEQ".nextval into NEW.COMMANDID ; 
RETURN NEW;
end
$BODY$
 LANGUAGE 'plpgsql';

CREATE TRIGGER bi_archivecommands
	BEFORE INSERT ON archivecommands FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_bi_archivecommands();

