-- Generated by Ora2Pg, the Oracle database Schema converter, version 13.0
-- Copyright 2000-2014 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.20.1.81;sid=XE

SET client_encoding TO 'UTF8';

SET search_path = aero, pg_catalog;\set ON_ERROR_STOP ON

DROP TRIGGER IF EXISTS bi_currentstatus ON currentstatus CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_bi_currentstatus () RETURNS trigger AS $BODY$
begin   
    SELECT "CURRENTSTATUS_SEQ".nextval into NEW.STATUSID ; 
end; 
$BODY$
 LANGUAGE 'plpgsql';

CREATE TRIGGER bi_currentstatus
	BEFORE INSERT ON currentstatus FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_bi_currentstatus();

