-- Generated by Ora2Pg, the Oracle database Schema converter, version 13.0
-- Copyright 2000-2014 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.20.1.81;sid=XE

SET client_encoding TO 'UTF8';

SET search_path = aero, pg_catalog;\set ON_ERROR_STOP ON

DROP TRIGGER IF EXISTS change_replication_server ON server_list CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_change_replication_server () RETURNS trigger AS $BODY$
declare
    pragma autonomous_transaction;
BEGIN
      if TG_OP = 'DELETE' then
        RAISE EXCEPTION 'ERROR: deny to remove replcation server';
      elsif TG_OP = 'UPDATE' then
        AFTN.init();
        commit;
      elsif TG_OP = 'INSERT' then
        RAISE EXCEPTION 'ERROR: deny to add replcation server';
      end if;
    RETURN NEW;
END
$BODY$
 LANGUAGE 'plpgsql';

CREATE TRIGGER change_replication_server
	AFTER INSERT OR UPDATE OR DELETE ON server_list FOR EACH STATEMENT
	EXECUTE PROCEDURE trigger_fct_change_replication_server();

