-- Generated by Ora2Pg, the Oracle database Schema converter, version 13.0
-- Copyright 2000-2014 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.20.1.81;sid=XE

SET client_encoding TO 'UTF8';

SET search_path = aero, pg_catalog;\set ON_ERROR_STOP ON

DROP TRIGGER IF EXISTS exercise_stand__trg ON exercise CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_exercise_stand__trg () RETURNS trigger AS $BODY$
DECLARE
  stand_cur CURSOR
  FOR
	SELECT id FROM stand;
BEGIN
  FOR stand_rec IN stand_cur
  LOOP
    INSERT INTO exercise_stand(stand_id, exercise_id)
	  VALUES(stand_rec.id, NEW.id_exercise);
  END LOOP;
RETURN NEW;
END
$BODY$
 LANGUAGE 'plpgsql';

CREATE TRIGGER exercise_stand__trg
	AFTER INSERT ON exercise FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_exercise_stand__trg();

