-- Generated by Ora2Pg, the Oracle database Schema converter, version 13.0
-- Copyright 2000-2014 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.20.1.81;sid=XE

SET client_encoding TO 'UTF8';

SET search_path = aero, pg_catalog;\set ON_ERROR_STOP ON

DROP TRIGGER IF EXISTS fpl_on_future_lt ON fpl_on_future CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_fpl_on_future_lt () RETURNS trigger AS $BODY$
BEGIN
    -- Touch the row
      update sys_tables_info set lasttouch = now() AT TIME ZONE 'UTC' where tablename ='FPL_ON_FUTURE';
    RETURN NEW;
END
$BODY$
 LANGUAGE 'plpgsql';

CREATE TRIGGER fpl_on_future_lt
	AFTER INSERT OR UPDATE OR DELETE ON fpl_on_future FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_fpl_on_future_lt();

