-- Generated by Ora2Pg, the Oracle database Schema converter, version 13.0
-- Copyright 2000-2014 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.20.1.81;sid=XE

SET client_encoding TO 'UTF8';

SET search_path = aero, pg_catalog;\set ON_ERROR_STOP ON

DROP TRIGGER IF EXISTS fpl_master_before_insert ON fpl_master CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_fpl_master_before_insert () RETURNS trigger AS $BODY$
BEGIN
	SELECT (SELECT id
			FROM FPL 
			WHERE aircraft_id = NEW.aircraft_id AND adep = NEW.adep AND ades = NEW.ades) INTO NEW.id ;
RETURN NEW;
END
$BODY$
 LANGUAGE 'plpgsql';

CREATE TRIGGER fpl_master_before_insert 
      BEFORE INSERT ON FPL_MASTER FOR EACH ROW
 
	WHEN ( coalesce(new.id::text, '') = '' )
	EXECUTE PROCEDURE trigger_fct_fpl_master_before_insert();

