-- Generated by Ora2Pg, the Oracle database Schema converter, version 13.0
-- Copyright 2000-2014 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.20.1.81;sid=XE

SET client_encoding TO 'UTF8';

SET search_path = aero, pg_catalog;\set ON_ERROR_STOP ON

DROP TRIGGER IF EXISTS fpl_changes_master_trg ON fpl CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_fpl_changes_master_trg () RETURNS trigger AS $BODY$
DECLARE
	soper FPL_CHANGES_MASTER.oper%TYPE;
	ac_flag numeric;
	
BEGIN
	ac_flag := sys_context('CLIENTCONTEXT', 'FDP_TAN_FLAG');
	IF ac_flag = 777 THEN
		NULL;
	ELSE
		--DELETE
		IF TG_OP = 'DELETE' THEN
			DELETE FROM FPL_CHANGES_MASTER WHERE id = OLD.ID;
			INSERT INTO FPL_CHANGES_MASTER
			(
				ID,
				FIR_NAME,
				AIRCRAFT_ID,
				TAIRCRAFT,
				FRULES,
				TFLIGHT,
				NUM,
				WTC,
				EQUIPMENT,
				ADEP,
				TIME,
				SPEED,
				FLEVEL,
				ROUTE,
				ADES,
				EET,
				ALT1,
				ALT2,
				OTHER,
				TRTIME,
				EXFPL,
				VISIBILITY,
				MESSAGE_ID,
				ENTRY_FIR_EET,
				OPER,
				OPER_TIME,
				MESSAGE_TEXT
			)
			VALUES
			(
				OLD.ID,
				OLD.FIR_NAME,
				OLD.AIRCRAFT_ID,
				OLD.TAIRCRAFT,
				OLD.FRULES,
				OLD.TFLIGHT,
				OLD.NUM,
				OLD.WTC,
				OLD.EQUIPMENT,
				OLD.ADEP,
				OLD.TIME,
				OLD.SPEED,
				OLD.FLEVEL,
				OLD.ROUTE,
				OLD.ADES,
				OLD.EET,
				OLD.ALT1,
				OLD.ALT2,
				OLD.OTHER,
				OLD.TRTIME,
				OLD.EXFPL,
				OLD.VISIBILITY,
				OLD.MESSAGE_ID,
				OLD.ENTRY_FIR_EET,
				'D',
				now(),
				( SELECT text FROM ARC_AFTN WHERE id = OLD.MESSAGE_ID )
			);
		ELSE
			--INSERT
			IF TG_OP = 'INSERT' THEN
				soper := 'I';
			--UPDATE
			ELSE
				soper := 'U';
			END IF;
			
			DELETE FROM FPL_CHANGES_MASTER WHERE id = NEW.ID;
			INSERT INTO FPL_CHANGES_MASTER
			(
				ID,
				FIR_NAME,
				AIRCRAFT_ID,
				TAIRCRAFT,
				FRULES,
				TFLIGHT,
				NUM,
				WTC,
				EQUIPMENT,
				ADEP,
				TIME,
				SPEED,
				FLEVEL,
				ROUTE,
				ADES,
				EET,
				ALT1,
				ALT2,
				OTHER,
				TRTIME,
				EXFPL,
				VISIBILITY,
				MESSAGE_ID,
				ENTRY_FIR_EET,
				OPER,
				OPER_TIME,
				MESSAGE_TEXT
			)
			VALUES
			(
				NEW.ID,
				NEW.FIR_NAME,
				NEW.AIRCRAFT_ID,
				NEW.TAIRCRAFT,
				NEW.FRULES,
				NEW.TFLIGHT,
				NEW.NUM,
				NEW.WTC,
				NEW.EQUIPMENT,
				NEW.ADEP,
				NEW.TIME,
				NEW.SPEED,
				NEW.FLEVEL,
				NEW.ROUTE,
				NEW.ADES,
				NEW.EET,
				NEW.ALT1,
				NEW.ALT2,
				NEW.OTHER,
				NEW.TRTIME,
				NEW.EXFPL,
				NEW.VISIBILITY,
				NEW.MESSAGE_ID,
				NEW.ENTRY_FIR_EET,
				soper,
				now(),
				( SELECT text FROM ARC_AFTN WHERE id = NEW.MESSAGE_ID )
			);
		END IF;
	END IF;
RETURN NEW;
END
$BODY$
 LANGUAGE 'plpgsql';

CREATE TRIGGER fpl_changes_master_trg
	AFTER INSERT OR UPDATE OR DELETE ON fpl FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_fpl_changes_master_trg();

