-- Generated by Ora2Pg, the Oracle database Schema converter, version 13.0
-- Copyright 2000-2014 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.20.1.81;sid=XE

SET client_encoding TO 'UTF8';

SET search_path = aero, pg_catalog;\set ON_ERROR_STOP ON

DROP TRIGGER IF EXISTS fpl_sfpl_restrict_trg ON fpl CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_fpl_sfpl_restrict_trg () RETURNS trigger AS $BODY$
declare
  cnt numeric;
  BEGIN
  select count(*) into cnt from sfpl_table where aircraft_id = NEW.aircraft_id and adep = NEW.adep and ades = NEW.ades;
  if (cnt != 0) then
    RAISE EXCEPTION 'ERROR: Active FPL can not be edited.';
  end if;
RETURN NEW;
END
$BODY$
 LANGUAGE 'plpgsql';

CREATE TRIGGER fpl_sfpl_restrict_trg
	BEFORE INSERT OR UPDATE ON fpl FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_fpl_sfpl_restrict_trg();

