-- Generated by Ora2Pg, the Oracle database Schema converter, version 13.0
-- Copyright 2000-2014 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.20.1.81;sid=XE

SET client_encoding TO 'UTF8';

SET search_path = aero, pg_catalog;\set ON_ERROR_STOP ON

DROP TRIGGER IF EXISTS fpl_additional_trg ON fpl CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_fpl_additional_trg () RETURNS trigger AS $BODY$
BEGIN
	--INSERT
	IF TG_OP = 'INSERT' THEN
		INSERT INTO FPL_ADDITIONAL(FPL_ID_REF)
		VALUES(NEW.ID);
	END IF;
RETURN NEW;
END
$BODY$
 LANGUAGE 'plpgsql';

CREATE TRIGGER fpl_additional_trg
	AFTER INSERT ON fpl FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_fpl_additional_trg();

