-- Generated by Ora2Pg, the Oracle database Schema converter, version 13.0
-- Copyright 2000-2014 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.20.1.81;sid=XE

SET client_encoding TO 'UTF8';

SET search_path = aero, pg_catalog;\set ON_ERROR_STOP ON

DROP TRIGGER IF EXISTS hist_rpl_id_trg ON hist_rpl CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_hist_rpl_id_trg () RETURNS trigger AS $BODY$
BEGIN
  if coalesce(NEW.hist_id::text, '') = '' then
    SELECT "HIST_RPL_ID_SEQ".nextval INTO NEW.HIST_ID ;
  end if;
RETURN NEW;
END
$BODY$
 LANGUAGE 'plpgsql';

CREATE TRIGGER hist_rpl_id_trg
	BEFORE INSERT ON hist_rpl FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_hist_rpl_id_trg();

