-- Generated by Ora2Pg, the Oracle database Schema converter, version 13.0
-- Copyright 2000-2014 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.20.1.81;sid=XE

SET client_encoding TO 'UTF8';

SET search_path = aero, pg_catalog;\set ON_ERROR_STOP ON

DROP TRIGGER IF EXISTS oldi_clients_lt ON oldi_clients CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_oldi_clients_lt () RETURNS trigger AS $BODY$
BEGIN
  -- Touch the row
  UPDATE sys_tables_info
  SET lasttouch   = now() AT TIME ZONE 'UTC'
  WHERE tablename ='OLDI_CLIENTS';
RETURN NEW;
END
$BODY$
 LANGUAGE 'plpgsql';

CREATE TRIGGER oldi_clients_lt
	AFTER INSERT OR UPDATE OR DELETE ON oldi_clients FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_oldi_clients_lt();

