-- Generated by Ora2Pg, the Oracle database Schema converter, version 13.0
-- Copyright 2000-2014 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.20.1.81;sid=XE

SET client_encoding TO 'UTF8';

SET search_path = aero, pg_catalog;\set ON_ERROR_STOP ON

DROP TRIGGER IF EXISTS restriction_ac ON restriction CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_restriction_ac () RETURNS trigger AS $BODY$
DECLARE
	ac_flag numeric;

	cursorfir zone_pkg.zone_rec_type;
	curfir cursorfir%ROWTYPE;

BEGIN
	ac_flag := sys_context('CLIENTCONTEXT', 'ARINC_CHANGES_FLAG');
	IF ac_flag = 777 THEN
		--DELETE
		IF TG_OP = 'DELETE' THEN
			zone_pkg.get_cur_zone(OLD.zone_id, cursorfir);
			FETCH cursorfir INTO curfir;
			CLOSE cursorfir;
			INSERT INTO ARINC_CHANGES(STATEMENT)
			VALUES
			('DELETE FROM RESTRICTION WHERE ' ||
				'NAME ' || NVL2(OLD.NAME, '= ''' || OLD.NAME || '''', 'IS NULL') || ' AND ' ||
				'TYPE = ''' || OLD.TYPE || ''' AND ' ||
				'DESIGNATION = ''' || OLD.DESIGNATION || ''' AND ' ||
				'ZONE_ID = (SELECT ID FROM ZONE WHERE ID_NAME = ''' || curfir.ID_NAME || ''' AND TYPE = ''' || curfir.TYPE || ''' AND NAME = ''' || curfir.NAME || ''')'
			);
		ELSE
			zone_pkg.get_cur_zone(NEW.zone_id, cursorfir);
			FETCH cursorfir INTO curfir;
			CLOSE cursorfir;
			--INSERT
			IF TG_OP = 'INSERT' THEN
				INSERT INTO ARINC_CHANGES(STATEMENT)
				VALUES
				('INSERT INTO RESTRICTION(NAME, TYPE, DESIGNATION, ZONE_ID, MULTI_CODE, H_MIN, H_MAX, SCHEDULE_MODE) ' ||
				'VALUES(' ||
					'''' || NEW.NAME || ''', ' ||
					'''' || NEW.TYPE || ''', ' ||
					'''' || NEW.DESIGNATION || ''', ' ||
					'(SELECT ID FROM ZONE WHERE ID_NAME = ''' || curfir.ID_NAME || ''' AND TYPE = ''' || curfir.TYPE || ''' AND NAME = ''' || curfir.NAME || '''), ' ||
					'''' || NEW.MULTI_CODE || ''', ' ||
					'''' || NEW.H_MIN || ''', ' ||
					'''' || NEW.H_MAX || ''', ' ||
					'''' || NEW.SCHEDULE_MODE || '''' ||
					')');
			--UPDATE
			ELSE
				INSERT INTO ARINC_CHANGES(STATEMENT)
				VALUES
				('UPDATE RESTRICTION SET ' ||
					'NAME = ''' || NEW.NAME || ''', ' ||
					'TYPE = ''' || NEW.TYPE || ''', ' ||
					'DESIGNATION = ''' || NEW.DESIGNATION || ''', ' ||
					'MULTI_CODE = ''' || NEW.MULTI_CODE || ''', ' ||
					'H_MIN = ''' || NEW.H_MIN || ''', ' ||
					'H_MAX = ''' || NEW.H_MAX || ''', ' ||
					'SCHEDULE_MODE = ''' || NEW.SCHEDULE_MODE || ''' ' ||
				'WHERE ' ||
					'NAME ' || NVL2(OLD.NAME, '= ''' || OLD.NAME || '''', 'IS NULL') || ' AND ' ||
					'TYPE = ''' || OLD.TYPE || ''' AND ' ||
					'DESIGNATION = ''' || OLD.DESIGNATION || ''' AND ' ||
					'ZONE_ID = (SELECT ID FROM ZONE WHERE ID_NAME = ''' || curfir.ID_NAME || ''' AND TYPE = ''' || curfir.TYPE || ''' AND NAME = ''' || curfir.NAME || ''')'
				);
			END IF;
		END IF;
	END IF;
RETURN NEW;
END
$BODY$
 LANGUAGE 'plpgsql';

CREATE TRIGGER restriction_ac
	AFTER INSERT OR UPDATE OR DELETE ON restriction FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_restriction_ac();

