-- Generated by Ora2Pg, the Oracle database Schema converter, version 13.0
-- Copyright 2000-2014 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.20.1.81;sid=XE

SET client_encoding TO 'UTF8';

SET search_path = aero, pg_catalog;\set ON_ERROR_STOP ON

DROP TRIGGER IF EXISTS restriction_point_ac ON restriction_point CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_restriction_point_ac () RETURNS trigger AS $BODY$
DECLARE
	ac_flag numeric;
	
	cursorfir zone_pkg.zone_rec_type;
	curfir cursorfir%ROWTYPE;

	cursorrestriction zone_pkg.restriction_rec_type;
	currestriction cursorrestriction%ROWTYPE;

BEGIN
	ac_flag := sys_context('CLIENTCONTEXT', 'ARINC_CHANGES_FLAG');
	IF ac_flag = 777 THEN
		--DELETE
		IF TG_OP = 'DELETE' THEN
			zone_pkg.get_cur_restriction(OLD.restriction_id, cursorrestriction);
			FETCH cursorrestriction INTO currestriction;
			CLOSE cursorrestriction;
			zone_pkg.get_cur_zone(currestriction.zone_id, cursorfir);
			FETCH cursorfir INTO curfir;
			CLOSE cursorfir;
			INSERT INTO ARINC_CHANGES(STATEMENT)
			VALUES
			('DELETE FROM RESTRICTION_POINT WHERE ' ||
				'SN = ''' || OLD.SN || ''' AND ' ||
				'TYPE = ''' || OLD.TYPE || ''' AND ' ||
				'LATITUDE = ''' || OLD.LATITUDE || ''' AND ' ||
				'LONGITUDE = ''' || OLD.LONGITUDE || ''' AND ' ||
				'ARC_LATITUDE = ''' || OLD.ARC_LATITUDE || ''' AND ' ||
				'ARC_LONGITUDE = ''' || OLD.ARC_LONGITUDE || ''' AND ' ||
				'ARC_DISTANCE = ''' || OLD.ARC_DISTANCE || ''' AND ' ||
				'RESTRICTION_ID = (SELECT ID FROM RESTRICTION WHERE ' || 'NAME ' || NVL2(currestriction.NAME, '= ''' || currestriction.NAME || '''', 'IS NULL') || ' AND ' || 'TYPE = ''' || currestriction.TYPE || ''' AND ' || 'DESIGNATION = ''' || currestriction.DESIGNATION || ''' AND ' || 'ZONE_ID = (SELECT ID FROM ZONE WHERE ID_NAME = ''' || curfir.ID_NAME || ''' AND TYPE = ''' || curfir.TYPE || ''' AND NAME = ''' || curfir.NAME || ''')' || ')'
			);
		ELSE
			zone_pkg.get_cur_restriction(NEW.restriction_id, cursorrestriction);
			FETCH cursorrestriction INTO currestriction;
			CLOSE cursorrestriction;
			zone_pkg.get_cur_zone(currestriction.zone_id, cursorfir);
			FETCH cursorfir INTO curfir;
			CLOSE cursorfir;
			--INSERT
			IF TG_OP = 'INSERT' THEN
				INSERT INTO ARINC_CHANGES(STATEMENT)
				VALUES
				('INSERT INTO RESTRICTION_POINT(SN, TYPE, LATITUDE, LONGITUDE, ARC_LATITUDE, ARC_LONGITUDE, ARC_DISTANCE, RESTRICTION_ID) ' ||
				'VALUES(' ||
					'''' || NEW.SN || ''', ' ||
					'''' || NEW.TYPE || ''', ' ||
					'''' || NEW.LATITUDE || ''', ' ||
					'''' || NEW.LONGITUDE || ''', ' ||
					'''' || NEW.ARC_LATITUDE || ''', ' ||
					'''' || NEW.ARC_LONGITUDE || ''', ' ||
					'''' || NEW.ARC_DISTANCE || ''', ' ||
					'(SELECT ID FROM RESTRICTION WHERE ' || 'NAME ' || NVL2(currestriction.NAME, '= ''' || currestriction.NAME || '''', 'IS NULL') || ' AND ' || 'TYPE = ''' || currestriction.TYPE || ''' AND ' || 'DESIGNATION = ''' || currestriction.DESIGNATION || ''' AND ' || 'ZONE_ID = (SELECT ID FROM ZONE WHERE ID_NAME = ''' || curfir.ID_NAME || ''' AND TYPE = ''' || curfir.TYPE || ''' AND NAME = ''' || curfir.NAME || ''')' || ')' ||
					')');
			--UPDATE
			ELSE
				INSERT INTO ARINC_CHANGES(STATEMENT)
				VALUES
				('UPDATE RESTRICTION_POINT SET ' ||
					'SN = ''' || NEW.SN || ''', ' ||
					'TYPE = ''' || NEW.TYPE || ''', ' ||
					'LATITUDE = ''' || NEW.LATITUDE || ''', ' ||
					'LONGITUDE = ''' || NEW.LONGITUDE || ''', ' ||
					'ARC_LATITUDE = ''' || NEW.ARC_LATITUDE || ''', ' ||
					'ARC_LONGITUDE = ''' || NEW.ARC_LONGITUDE || ''', ' ||
					'ARC_DISTANCE = ''' || NEW.ARC_DISTANCE || ''' ' ||
				'WHERE ' ||
					'SN = ''' || OLD.SN || ''' AND ' ||
					'TYPE = ''' || OLD.TYPE || ''' AND ' ||
					'LATITUDE = ''' || OLD.LATITUDE || ''' AND ' ||
					'LONGITUDE = ''' || OLD.LONGITUDE || ''' AND ' ||
					'ARC_LATITUDE = ''' || OLD.ARC_LATITUDE || ''' AND ' ||
					'ARC_LONGITUDE = ''' || OLD.ARC_LONGITUDE || ''' AND ' ||
					'ARC_DISTANCE = ''' || OLD.ARC_DISTANCE || ''' AND ' ||
					'RESTRICTION_ID = (SELECT ID FROM RESTRICTION WHERE ' || 'NAME ' || NVL2(currestriction.NAME, '= ''' || currestriction.NAME || '''', 'IS NULL') || ' AND ' || 'TYPE = ''' || currestriction.TYPE || ''' AND ' || 'DESIGNATION = ''' || currestriction.DESIGNATION || ''' AND ' || 'ZONE_ID = (SELECT ID FROM ZONE WHERE ID_NAME = ''' || curfir.ID_NAME || ''' AND TYPE = ''' || curfir.TYPE || ''' AND NAME = ''' || curfir.NAME || ''')' || ')'
				);
			END IF;
		END IF;
	END IF;
RETURN NEW;
END
$BODY$
 LANGUAGE 'plpgsql';

CREATE TRIGGER restriction_point_ac
	AFTER INSERT OR UPDATE OR DELETE ON restriction_point FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_restriction_point_ac();

