-- Generated by Ora2Pg, the Oracle database Schema converter, version 13.0
-- Copyright 2000-2014 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.20.1.81;sid=XE

SET client_encoding TO 'UTF8';

SET search_path = aero, pg_catalog;\set ON_ERROR_STOP ON

DROP TRIGGER IF EXISTS rpl_after_query_trg ON rpl CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_rpl_after_query_trg () RETURNS trigger AS $BODY$
DECLARE
  modification_type char;
  current_user_id   numeric;
BEGIN
  BEGIN
    SELECT user_id INTO STRICT  current_user_id FROM login LIMIT 1;
   EXCEPTION
    WHEN NO_DATA_FOUND THEN
      current_user_id := -1;
  END;
  
  if current_user_id <> -1 then
  IF TG_OP = 'DELETE' THEN
    INSERT INTO hist_rpl
    (
      id,      fir_name, aircraft_id, taircraft, frules,
      tflight, num,      wtc,         equipment, adep,
      time,    speed,    flevel,      route,     ades,
      eet,     alt1,     alt2,        other,     trtime,
      exfpl,   days,     modified_by, modification_type, entry_fir_eet
      , valid_from, valid_to
    )
    VALUES
    (
      OLD.id,      OLD.fir_name, OLD.aircraft_id, OLD.taircraft, OLD.frules,
      OLD.tflight, OLD.num,      OLD.wtc,         OLD.equipment, OLD.adep,
      OLD.time,    OLD.speed,    OLD.flevel,      OLD.route,     OLD.ades,
      OLD.eet,     OLD.alt1,     OLD.alt2,        OLD.other,     OLD.trtime,
      OLD.exfpl,   OLD.days,      current_user_id,     'D', OLD.entry_fir_eet
      , OLD.valid_from, OLD.valid_to
    );
  ELSE
    IF TG_OP = 'INSERT' THEN
      modification_type := 'I';
    ELSE
      modification_type := 'U';
    END IF;
    INSERT INTO hist_rpl
    (
      id,      fir_name, aircraft_id, taircraft, frules,
      tflight, num,      wtc,         equipment, adep,
      time,    speed,    flevel,      route,     ades,
      eet,     alt1,     alt2,        other,     trtime,
      exfpl,   days,     modified_by, modification_type, entry_fir_eet
      , valid_from, valid_to
    )
    VALUES
    (
      NEW.id,      NEW.fir_name, NEW.aircraft_id, NEW.taircraft, NEW.frules,
      NEW.tflight, NEW.num,      NEW.wtc,         NEW.equipment, NEW.adep,
      NEW.time,    NEW.speed,    NEW.flevel,      NEW.route,     NEW.ades,
      NEW.eet,     NEW.alt1,     NEW.alt2,        NEW.other,     NEW.trtime,
      NEW.exfpl,   NEW.days,      current_user_id,     modification_type, NEW.entry_fir_eet
      , NEW.valid_from, NEW.valid_to
    );
  END IF;
  end if;
RETURN NEW;
END
$BODY$
 LANGUAGE 'plpgsql';

CREATE TRIGGER rpl_after_query_trg
	AFTER INSERT OR UPDATE OR DELETE ON rpl FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_rpl_after_query_trg();

