-- Generated by Ora2Pg, the Oracle database Schema converter, version 13.0
-- Copyright 2000-2014 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.20.1.81;sid=XE

SET client_encoding TO 'UTF8';

SET search_path = aero, pg_catalog;\set ON_ERROR_STOP ON

DROP TRIGGER IF EXISTS server_list_lt ON server_list CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_server_list_lt () RETURNS trigger AS $BODY$
BEGIN
    -- Touch the row
      update sys_tables_info set lasttouch = now() AT TIME ZONE 'UTC' where tablename ='SERVER_LIST';
    RETURN NEW;
END
$BODY$
 LANGUAGE 'plpgsql';

CREATE TRIGGER server_list_lt
	AFTER INSERT OR UPDATE OR DELETE ON server_list FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_server_list_lt();

