-- Generated by Ora2Pg, the Oracle database Schema converter, version 13.0
-- Copyright 2000-2014 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.20.1.81;sid=XE

SET client_encoding TO 'UTF8';

SET search_path = aero, pg_catalog;\set ON_ERROR_STOP ON

DROP TRIGGER IF EXISTS ssa_point_ac ON ssa_point CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_ssa_point_ac () RETURNS trigger AS $BODY$
DECLARE
	ac_flag numeric;

	cursorssa zone_pkg.ssa_rec_type;
	curssa cursorssa%ROWTYPE;

	cursorrunway zone_pkg.runway_rec_type;
	currunway cursorrunway%ROWTYPE;

	cursorairport zone_pkg.airport_rec_type;
	curairport cursorairport%ROWTYPE;

	cursorpoint zone_pkg.point_rec_type;
	newpoint cursorpoint%ROWTYPE;
	oldpoint cursorpoint%ROWTYPE;

	BEGIN
	ac_flag := sys_context('CLIENTCONTEXT', 'ARINC_CHANGES_FLAG');
	IF ac_flag = 777 THEN
		--DELETE
		IF TG_OP = 'DELETE' THEN
			zone_pkg.get_cur_ssa(OLD.ssa_id, cursorssa);
			FETCH cursorssa INTO curssa;
			CLOSE cursorssa;
			zone_pkg.get_cur_runway(curssa.runway_id, cursorrunway);
			FETCH cursorrunway INTO currunway;
			CLOSE cursorrunway;
			zone_pkg.get_cur_airport(currunway.airport_id, cursorairport);
			FETCH cursorairport INTO curairport;
			CLOSE cursorairport;

			zone_pkg.get_cur_point(OLD.point_id, cursorpoint);
			FETCH cursorpoint INTO oldpoint;
			CLOSE cursorpoint;

			INSERT INTO ARINC_CHANGES(STATEMENT)
			VALUES
			('DELETE FROM SSA_POINT WHERE ' ||
				'SSA_ID = (SELECT ID FROM SSA WHERE RUNWAY_ID = (SELECT ID FROM RUNWAY WHERE NAME = ''' || currunway.NAME || ''' AND LATITUDE = ''' || currunway.LATITUDE || ''' AND LONGITUDE = ''' || currunway.LONGITUDE || ''' AND LENGTH = ''' || currunway.LENGTH || ''' AND AZIMUTH = ''' || currunway.AZIMUTH || ''' AND AIRPORT_ID = (SELECT ID FROM AIRPORT WHERE ICAO = ''' || curairport.ICAO || ''' AND NAME = ''' || curairport.NAME || ''') AND WIDTH = ''' || currunway.WIDTH || ''') AND NAME = ''' || curssa.NAME || ''' AND TYPE ' || NVL2(curssa.TYPE, '= ''' || curssa.TYPE || '''', 'IS NULL') || ' AND TRANS_ALT ' || NVL2(curssa.TRANS_ALT, '= ''' || curssa.TRANS_ALT || '''', 'IS NULL') || ') AND ' ||
				'POINT_ID ' || NVL2((CASE WHEN OLD.POINT_ID=0 THEN NULL ELSE OLD.POINT_ID END), '= (SELECT ID FROM POINT WHERE TYPE = ''' || oldpoint.TYPE || ''' AND NAME = ''' || oldpoint.NAME || ''' AND LATITUDE = ''' || oldpoint.LATITUDE || ''' AND LONGITUDE = ''' || oldpoint.LONGITUDE || ''')', '= 0') || ' AND ' ||
				'SN = ''' || OLD.SN || ''' AND ' ||
				'FLEVEL ' || NVL2(OLD.FLEVEL, '= ''' || OLD.FLEVEL || '''', 'IS NULL') || ' AND ' ||
				'SPEED ' || NVL2(OLD.SPEED, '= ''' || OLD.SPEED || '''', 'IS NULL') || ' AND ' ||
				'TYPE = ''' || OLD.TYPE || ''' AND ' ||
				'COURSE ' || NVL2(OLD.COURSE, '= ''' || OLD.COURSE || '''', 'IS NULL') || ' AND ' ||
				'TURN ' || NVL2(OLD.TURN, '= ''' || OLD.TURN || '''', 'IS NULL') || ' AND ' ||
				'ALTITUDE1 ' || NVL2(OLD.ALTITUDE1, '= ''' || OLD.ALTITUDE1 || '''', 'IS NULL') || ' AND ' ||
				'FLY_OVER ' || NVL2(OLD.FLY_OVER, '= ''' || OLD.FLY_OVER || '''', 'IS NULL')
			);
		ELSE
			zone_pkg.get_cur_ssa(NEW.ssa_id, cursorssa);
			FETCH cursorssa INTO curssa;
			CLOSE cursorssa;
			zone_pkg.get_cur_runway(curssa.runway_id, cursorrunway);
			FETCH cursorrunway INTO currunway;
			CLOSE cursorrunway;
			zone_pkg.get_cur_airport(currunway.airport_id, cursorairport);
			FETCH cursorairport INTO curairport;
			CLOSE cursorairport;

			zone_pkg.get_cur_point(NEW.point_id, cursorpoint);
			FETCH cursorpoint INTO newpoint;
			CLOSE cursorpoint;
			--INSERT
			IF TG_OP = 'INSERT' THEN
				INSERT INTO ARINC_CHANGES(STATEMENT)
				VALUES
				('INSERT INTO SSA_POINT(SSA_ID, POINT_ID, SN, FLEVEL, SPEED, TYPE, COURSE, TURN, ALTITUDE1, FLY_OVER) ' ||
				'VALUES(' ||
					'(SELECT ID FROM SSA WHERE RUNWAY_ID = (SELECT ID FROM RUNWAY WHERE NAME = ''' || currunway.NAME || ''' AND LATITUDE = ''' || currunway.LATITUDE || ''' AND LONGITUDE = ''' || currunway.LONGITUDE || ''' AND LENGTH = ''' || currunway.LENGTH || ''' AND AZIMUTH = ''' || currunway.AZIMUTH || ''' AND AIRPORT_ID = (SELECT ID FROM AIRPORT WHERE ICAO = ''' || curairport.ICAO || ''' AND NAME = ''' || curairport.NAME || ''') AND WIDTH = ''' || currunway.WIDTH || ''') AND NAME = ''' || curssa.NAME || ''' AND TYPE ' || NVL2(curssa.TYPE, '= ''' || curssa.TYPE || '''', 'IS NULL') || ' AND TRANS_ALT ' || NVL2(curssa.TRANS_ALT, '= ''' || curssa.TRANS_ALT || '''', 'IS NULL') || '), ' ||
					NVL2((CASE WHEN NEW.POINT_ID=0 THEN NULL ELSE NEW.POINT_ID END), '(SELECT ID FROM POINT WHERE TYPE = ''' || newpoint.TYPE || ''' AND NAME = ''' || newpoint.NAME || ''' AND LATITUDE = ''' || newpoint.LATITUDE || ''' AND LONGITUDE = ''' || newpoint.LONGITUDE || ''')', '0') || ', ' ||
					'''' || NEW.SN || ''', ' ||
					'''' || NEW.FLEVEL || ''', ' ||
					'''' || NEW.SPEED || ''', ' ||
					'''' || NEW.TYPE || ''', ' ||
					'''' || NEW.COURSE || ''', ' ||
					'''' || NEW.TURN || ''', ' ||
					'''' || NEW.ALTITUDE1 || ''', ' ||
					'''' || NEW.FLY_OVER || '''' ||
					')');
			--UPDATE
			ELSE
				zone_pkg.get_cur_point(OLD.point_id, cursorpoint);
				FETCH cursorpoint INTO oldpoint;
				CLOSE cursorpoint;
				INSERT INTO ARINC_CHANGES(STATEMENT)
				VALUES
				('UPDATE SSA_POINT SET ' ||
					'POINT_ID = ' || NVL2((CASE WHEN NEW.POINT_ID=0 THEN NULL ELSE NEW.POINT_ID END), '(SELECT ID FROM POINT WHERE TYPE = ''' || newpoint.TYPE || ''' AND NAME = ''' || newpoint.NAME || ''' AND LATITUDE = ''' || newpoint.LATITUDE || ''' AND LONGITUDE = ''' || newpoint.LONGITUDE || ''')', '0') || ', ' ||
					'SN = ''' || NEW.SN || ''', ' ||
					'FLEVEL = ''' || NEW.FLEVEL || ''', ' ||
					'SPEED = ''' || NEW.SPEED || ''', ' ||
					'TYPE = ''' || NEW.TYPE || ''', ' ||
					'COURSE = ''' || NEW.COURSE || ''', ' ||
					'TURN = ''' || NEW.TURN || ''', ' ||
					'ALTITUDE1 = ''' || NEW.ALTITUDE1 || ''', ' ||
					'FLY_OVER = ''' || NEW.FLY_OVER || ''' ' ||
				'WHERE ' ||
					'SSA_ID = (SELECT ID FROM SSA WHERE RUNWAY_ID = (SELECT ID FROM RUNWAY WHERE NAME = ''' || currunway.NAME || ''' AND LATITUDE = ''' || currunway.LATITUDE || ''' AND LONGITUDE = ''' || currunway.LONGITUDE || ''' AND LENGTH = ''' || currunway.LENGTH || ''' AND AZIMUTH = ''' || currunway.AZIMUTH || ''' AND AIRPORT_ID = (SELECT ID FROM AIRPORT WHERE ICAO = ''' || curairport.ICAO || ''' AND NAME = ''' || curairport.NAME || ''') AND WIDTH = ''' || currunway.WIDTH || ''') AND NAME = ''' || curssa.NAME || ''' AND TYPE ' || NVL2(curssa.TYPE, '= ''' || curssa.TYPE || '''', 'IS NULL') || ' AND TRANS_ALT ' || NVL2(curssa.TRANS_ALT, '= ''' || curssa.TRANS_ALT || '''', 'IS NULL') || ') AND ' ||
					'POINT_ID ' || NVL2((CASE WHEN OLD.POINT_ID=0 THEN NULL ELSE OLD.POINT_ID END), '= (SELECT ID FROM POINT WHERE TYPE = ''' || oldpoint.TYPE || ''' AND NAME = ''' || oldpoint.NAME || ''' AND LATITUDE = ''' || oldpoint.LATITUDE || ''' AND LONGITUDE = ''' || oldpoint.LONGITUDE || ''')', '= 0') || ' AND ' ||
					'SN = ''' || OLD.SN || ''' AND ' ||
					'FLEVEL ' || NVL2(OLD.FLEVEL, '= ''' || OLD.FLEVEL || '''', 'IS NULL') || ' AND ' ||
					'SPEED ' || NVL2(OLD.SPEED, '= ''' || OLD.SPEED || '''', 'IS NULL') || ' AND ' ||
					'TYPE = ''' || OLD.TYPE || ''' AND ' ||
					'COURSE ' || NVL2(OLD.COURSE, '= ''' || OLD.COURSE || '''', 'IS NULL') || ' AND ' ||
					'TURN ' || NVL2(OLD.TURN, '= ''' || OLD.TURN || '''', 'IS NULL') || ' AND ' ||
					'ALTITUDE1 ' || NVL2(OLD.ALTITUDE1, '= ''' || OLD.ALTITUDE1 || '''', 'IS NULL') || ' AND ' ||
					'FLY_OVER ' || NVL2(OLD.FLY_OVER, '= ''' || OLD.FLY_OVER || '''', 'IS NULL')
				);
			END IF;
		END IF;
	END IF;
RETURN NEW;
END
$BODY$
 LANGUAGE 'plpgsql';

CREATE TRIGGER ssa_point_ac
	AFTER INSERT OR UPDATE OR DELETE ON ssa_point FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_ssa_point_ac();

