-- Generated by Ora2Pg, the Oracle database Schema converter, version 13.0
-- Copyright 2000-2014 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.20.1.81;sid=XE

SET client_encoding TO 'UTF8';

SET search_path = aero, pg_catalog;\set ON_ERROR_STOP ON

DROP TRIGGER IF EXISTS ssa_ac ON ssa CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_ssa_ac () RETURNS trigger AS $BODY$
DECLARE
	ac_flag numeric;

	cursorrunway zone_pkg.runway_rec_type;
	currunway cursorrunway%ROWTYPE;

	cursorairport zone_pkg.airport_rec_type;
	curairport cursorairport%ROWTYPE;

BEGIN
	ac_flag := sys_context('CLIENTCONTEXT', 'ARINC_CHANGES_FLAG');
	IF ac_flag = 777 THEN
		--DELETE
		IF TG_OP = 'DELETE' THEN
			zone_pkg.get_cur_runway(OLD.runway_id, cursorrunway);
			FETCH cursorrunway INTO currunway;
			CLOSE cursorrunway;
			zone_pkg.get_cur_airport(currunway.airport_id, cursorairport);
			FETCH cursorairport INTO curairport;
			CLOSE cursorairport;
			INSERT INTO ARINC_CHANGES(STATEMENT)
			VALUES
			('DELETE FROM SSA WHERE ' ||
				'RUNWAY_ID = (SELECT ID FROM RUNWAY WHERE NAME = ''' || currunway.NAME || ''' AND LATITUDE = ''' || currunway.LATITUDE || ''' AND LONGITUDE = ''' || currunway.LONGITUDE || ''' AND LENGTH = ''' || currunway.LENGTH || ''' AND AZIMUTH = ''' || currunway.AZIMUTH || ''' AND AIRPORT_ID = (SELECT ID FROM AIRPORT WHERE ICAO = ''' || curairport.ICAO || ''' AND NAME = ''' || curairport.NAME || ''') AND WIDTH = ''' || currunway.WIDTH || ''') AND ' ||
				'NAME = ''' || OLD.NAME || ''' AND ' ||
				'TYPE ' || NVL2(OLD.TYPE, '= ''' || OLD.TYPE || '''', 'IS NULL') || ' AND ' ||
				'TRANS_ALT ' || NVL2(OLD.TRANS_ALT, '= ''' || OLD.TRANS_ALT || '''', 'IS NULL')
			);
		ELSE
			zone_pkg.get_cur_runway(NEW.runway_id, cursorrunway);
			FETCH cursorrunway INTO currunway;
			CLOSE cursorrunway;
			zone_pkg.get_cur_airport(currunway.airport_id, cursorairport);
			FETCH cursorairport INTO curairport;
			CLOSE cursorairport;
			--INSERT
			IF TG_OP = 'INSERT' THEN
				INSERT INTO ARINC_CHANGES(STATEMENT)
				VALUES
				('INSERT INTO SSA(RUNWAY_ID, NAME, TYPE, TRANS_ALT) ' ||
				'VALUES(' ||
					'(SELECT ID FROM RUNWAY WHERE NAME = ''' || currunway.NAME || ''' AND LATITUDE = ''' || currunway.LATITUDE || ''' AND LONGITUDE = ''' || currunway.LONGITUDE || ''' AND LENGTH = ''' || currunway.LENGTH || ''' AND AZIMUTH = ''' || currunway.AZIMUTH || ''' AND AIRPORT_ID = (SELECT ID FROM AIRPORT WHERE ICAO = ''' || curairport.ICAO || ''' AND NAME = ''' || curairport.NAME || ''') AND WIDTH = ''' || currunway.WIDTH || '''), ' ||
					'''' || NEW.NAME || ''', ' ||
					'''' || NEW.TYPE || ''', ' ||
					'''' || NEW.TRANS_ALT || '''' ||
					')');
			--UPDATE
			ELSE
				INSERT INTO ARINC_CHANGES(STATEMENT)
				VALUES
				('UPDATE SSA SET ' ||
					'NAME = ''' || NEW.NAME || ''', ' ||
					'TYPE = ''' || NEW.TYPE || ''', ' ||
					'TRANS_ALT = ''' || NEW.TRANS_ALT || ''' ' ||
				'WHERE ' ||
					'RUNWAY_ID = (SELECT ID FROM RUNWAY WHERE NAME = ''' || currunway.NAME || ''' AND LATITUDE = ''' || currunway.LATITUDE || ''' AND LONGITUDE = ''' || currunway.LONGITUDE || ''' AND LENGTH = ''' || currunway.LENGTH || ''' AND AZIMUTH = ''' || currunway.AZIMUTH || ''' AND AIRPORT_ID = (SELECT ID FROM AIRPORT WHERE ICAO = ''' || curairport.ICAO || ''' AND NAME = ''' || curairport.NAME || ''') AND WIDTH = ''' || currunway.WIDTH || ''') AND ' ||
					'NAME = ''' || OLD.NAME || ''' AND ' ||
					'TYPE ' || NVL2(OLD.TYPE, '= ''' || OLD.TYPE || '''', 'IS NULL') || ' AND ' ||
					'TRANS_ALT ' || NVL2(OLD.TRANS_ALT, '= ''' || OLD.TRANS_ALT || '''', 'IS NULL')
				);
			END IF;
		END IF;
	END IF;
RETURN NEW;
END
$BODY$
 LANGUAGE 'plpgsql';

CREATE TRIGGER ssa_ac
	AFTER INSERT OR UPDATE OR DELETE ON ssa FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_ssa_ac();

