-- Generated by Ora2Pg, the Oracle database Schema converter, version 13.0
-- Copyright 2000-2014 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.20.1.81;sid=XE

SET client_encoding TO 'UTF8';

SET search_path = aero, pg_catalog;\set ON_ERROR_STOP ON

DROP TRIGGER IF EXISTS stand_exercise__trg ON stand CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_stand_exercise__trg () RETURNS trigger AS $BODY$
DECLARE
  stand_cur CURSOR
  FOR
	SELECT id_exercise FROM exercise;
BEGIN
  FOR stand_rec IN stand_cur
  LOOP
    INSERT INTO exercise_stand(stand_id, exercise_id)
	  VALUES(NEW.id, stand_rec.id_exercise);
  END LOOP;
RETURN NEW;
END
$BODY$
 LANGUAGE 'plpgsql';

CREATE TRIGGER stand_exercise__trg
	AFTER INSERT ON stand FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_stand_exercise__trg();

