-- Generated by Ora2Pg, the Oracle database Schema converter, version 13.0
-- Copyright 2000-2014 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.20.1.81;sid=XE

SET client_encoding TO 'UTF8';

SET search_path = aero, pg_catalog;\set ON_ERROR_STOP ON

DROP TRIGGER IF EXISTS zone_ac ON zone CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_zone_ac () RETURNS trigger AS $BODY$
DECLARE
	ac_flag numeric;

	cursorfir zone_pkg.zone_rec_type;
	curfir cursorfir%ROWTYPE;

BEGIN
	ac_flag := sys_context('CLIENTCONTEXT', 'ARINC_CHANGES_FLAG');
	IF ac_flag = 777 THEN
		--DELETE
		IF TG_OP = 'DELETE' THEN
			INSERT INTO ARINC_CHANGES(STATEMENT)
			VALUES
			('DELETE FROM ZONE WHERE ' ||
				'ID_NAME = ''' || OLD.ID_NAME || ''' AND ' ||
				'TYPE = ''' || OLD.TYPE || ''' AND ' ||
				'NAME = ''' || OLD.NAME || '''');
		ELSE
			zone_pkg.get_cur_zone(NEW.parent_id, cursorfir);
			FETCH cursorfir INTO curfir;
			CLOSE cursorfir;
			--INSERT
			IF TG_OP = 'INSERT' THEN
				INSERT INTO ARINC_CHANGES(STATEMENT)
				VALUES
				('INSERT INTO ZONE(NAME, TYPE, ID_NAME, PARENT_ID, LOW_LIMIT, UP_LIMIT, SHORT_NAME, LABEL_NAME, FREQUENCY) ' ||
				'VALUES(' ||
					'''' || NEW.NAME || ''', ' ||
					'''' || NEW.TYPE || ''', ' ||
					'''' || NEW.ID_NAME || ''', ' ||
					'(SELECT ID FROM ZONE WHERE ID_NAME = ''' || curfir.ID_NAME || ''' AND TYPE = ''' || curfir.TYPE || ''' AND NAME = ''' || curfir.NAME || '''), ' ||
					'''' || NEW.LOW_LIMIT || ''', ' ||
					'''' || NEW.UP_LIMIT || ''', ' ||
					'''' || NEW.SHORT_NAME || ''', ' ||
					'''' || NEW.LABEL_NAME || ''', ' ||
					'''' || NEW.FREQUENCY || '''' ||
					')');
			--UPDATE
			ELSE
				INSERT INTO ARINC_CHANGES(STATEMENT)
				VALUES
				('UPDATE ZONE SET ' ||
					'NAME = ''' || NEW.NAME || ''', ' ||
					'TYPE = ''' || NEW.TYPE || ''', ' ||
					'ID_NAME = ''' || NEW.ID_NAME || ''', ' ||
					'PARENT_ID = (SELECT ID FROM ZONE WHERE ID_NAME = ''' || curfir.ID_NAME || ''' AND TYPE = ''' || curfir.TYPE || ''' AND NAME = ''' || curfir.NAME || '''), ' ||
					'LOW_LIMIT = ''' || NEW.LOW_LIMIT || ''', ' ||
					'UP_LIMIT = ''' || NEW.UP_LIMIT || ''', ' ||
					'SHORT_NAME = ''' || NEW.SHORT_NAME || ''', ' ||
					'LABEL_NAME = ''' || NEW.LABEL_NAME || ''', ' ||
					'FREQUENCY = ''' || NEW.FREQUENCY || ''' ' ||
				'WHERE ID_NAME = ''' || OLD.ID_NAME || ''' AND TYPE = ''' || OLD.TYPE || ''' AND NAME = ''' || OLD.NAME || '''');
			END IF;
		END IF;
	END IF;
RETURN NEW;
END
$BODY$
 LANGUAGE 'plpgsql';

CREATE TRIGGER zone_ac
	AFTER INSERT OR UPDATE OR DELETE ON zone FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_zone_ac();

