-- Generated by Ora2Pg, the Oracle database Schema converter, version 13.0
-- Copyright 2000-2014 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.20.1.81;sid=XE

SET client_encoding TO 'UTF8';

SET search_path = aero, pg_catalog;\set ON_ERROR_STOP ON

DROP TRIGGER IF EXISTS zone_after_delete_trg ON zone CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_zone_after_delete_trg () RETURNS trigger AS $BODY$
DECLARE
    c numeric;
  BEGIN
    IF TG_OP = 'DELETE' THEN
     select count(*) into c from zone a where (a.parent_id IS NOT NULL AND a.parent_id::text <> '') and not exists (select * from zone b where  b.id = a.parent_id);
      if c<>0 then
        delete from zone a where (a.parent_id IS NOT NULL AND a.parent_id::text <> '') and not exists (select * from zone b where b.id = a.parent_id) ;
      end if;
    END IF;
  RETURN NEW;
END
$BODY$
 LANGUAGE 'plpgsql';

CREATE TRIGGER zone_after_delete_trg
	AFTER DELETE ON zone FOR EACH STATEMENT
	EXECUTE PROCEDURE trigger_fct_zone_after_delete_trg();

