ALTER TABLE VEHICLE_PLAN 
DROP CONSTRAINT VEHICLE_PLAN_VEHICLE_ROUT_FK1;

ALTER TABLE VEHICLE_PLAN  
MODIFY (ROUTE_ID NULL);

ALTER TABLE VEHICLE_PLAN
ADD CONSTRAINT VEHICLE_PLAN_VEHICLE_ROUT_FK1 FOREIGN KEY
(
  ROUTE_ID 
)
REFERENCES VEHICLE_ROUTE
(
  ID 
)
ON DELETE SET NULL ENABLE;


ALTER TABLE VEHICLE_PLAN 
DROP CONSTRAINT VEHICLE_PLAN_VEHICLE_FK1;

ALTER TABLE VEHICLE_PLAN  
MODIFY (VEHICLE_ID NULL);

ALTER TABLE VEHICLE_PLAN
ADD CONSTRAINT VEHICLE_PLAN_VEHICLE_FK1 FOREIGN KEY
(
  VEHICLE_ID 
)
REFERENCES VEHICLE
(
  ID 
)
ON DELETE SET NULL ENABLE;