ALTER TABLE FPL  
MODIFY (EQUIPMENT VARCHAR2(222 CHAR) );

ALTER TABLE FFPL  
MODIFY (EQUIPMENT VARCHAR2(222 CHAR) );

ALTER TABLE FPL_CHANGES_MASTER  
MODIFY (EQUIPMENT VARCHAR2(222 CHAR) );

ALTER TABLE FPL_MASTER  
MODIFY (EQUIPMENT VARCHAR2(222 CHAR) );

ALTER TABLE FPL_ON_FUTURE  
MODIFY (EQUIPMENT VARCHAR2(222 CHAR) );

ALTER TABLE HIST_FPL  
MODIFY (EQUIPMENT VARCHAR2(222 CHAR) );

ALTER TABLE HIST_RPL  
MODIFY (EQUIPMENT VARCHAR2(222 CHAR) );

ALTER TABLE MSG_FROM_FDP  
MODIFY (EQUIPMENT VARCHAR2(222 CHAR) );

ALTER TABLE MSG_FROM_TAN  
MODIFY (EQUIPMENT VARCHAR2(222 CHAR) );

ALTER TABLE RPL  
MODIFY (EQUIPMENT VARCHAR2(222 CHAR) );

ALTER TABLE SFPL_MASTER_TABLE  
MODIFY (EQUIPMENT VARCHAR2(222 CHAR) );

ALTER TABLE SFPL_TABLE  
MODIFY (EQUIPMENT VARCHAR2(222 CHAR) );

