
  DROP TABLE REPLICATION_TABLE_LINKS;
  DROP TABLE REPLICATION_TABLE_VALUES;
  DROP TABLE REPLICATION_TABLE;
  
  CREATE TABLE REPLICATION_TABLE
   (	"ID" NUMBER NOT NULL ENABLE, 
	"OPER_TYPE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"TABLE_NAME" VARCHAR2(250 BYTE) NOT NULL ENABLE, 
	"COL_GUID_VALUE" RAW(16) NOT NULL ENABLE, 
	"TIME" TIMESTAMP (6) DEFAULT systimestamp NOT NULL ENABLE, 
	 CONSTRAINT "REPLICATION_TABLE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
 
  CREATE SEQUENCE  REPLICATION_TABLE_SEQ  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
  
  CREATE OR REPLACE TRIGGER REPLICATION_TABLE_TRG BEFORE INSERT ON REPLICATION_TABLE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    SELECT REPLICATION_TABLE_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER REPLICATION_TABLE_TRG ENABLE;
 

  CREATE TABLE REPLICATION_TABLE_VALUES 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"OPER_ID" NUMBER NOT NULL ENABLE, 
	"COL_NAME" VARCHAR2(250 BYTE) NOT NULL ENABLE, 
	"COL_VALUE" VARCHAR2(4000 BYTE), 
	 CONSTRAINT "REPLICATION_TABLE_VALUES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "REPLICATION_TABLE_VALUES__FK1" FOREIGN KEY ("OPER_ID")
	  REFERENCES REPLICATION_TABLE ("ID") ON DELETE CASCADE ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
 
   CREATE SEQUENCE  REPLICATION_TABLE_VALUES_SEQ  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
 
  CREATE OR REPLACE TRIGGER REPLICATION_TABLE_VALUES_TRG BEFORE INSERT ON REPLICATION_TABLE_VALUES 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    SELECT REPLICATION_TABLE_VALUES_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER REPLICATION_TABLE_VALUES_TRG ENABLE;
 

  CREATE TABLE REPLICATION_TABLE_LINKS 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"TABLE_NAME" VARCHAR2(250 BYTE) NOT NULL ENABLE, 
	"COL_ID_NAME" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"COL_ID_VALUE" NUMBER NOT NULL ENABLE, 
	"COL_GUID_VALUE" RAW(16) DEFAULT sys_guid() NOT NULL ENABLE, 
	 CONSTRAINT "REPLICATION_TABLE_LINKS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
 
  CREATE UNIQUE INDEX REPLICATION_TABLE_LINKS_INDEX1 ON REPLICATION_TABLE_LINKS ("COL_GUID_VALUE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
 
  CREATE UNIQUE INDEX REPLICATION_TABLE_LINKS_PK ON REPLICATION_TABLE_LINKS ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
  
  CREATE SEQUENCE  REPLICATION_TABLE_LINKS_SEQ  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

  CREATE OR REPLACE TRIGGER REPLICATION_TABLE_LINKS_TRG BEFORE INSERT ON REPLICATION_TABLE_LINKS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    SELECT REPLICATION_TABLE_LINKS_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER REPLICATION_TABLE_LINKS_TRG ENABLE;
 
