
  CREATE TABLE "FPL_CHANGES_MASTER" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"FIR_NAME" VARCHAR2(4 BYTE) DEFAULT 'UMMV' NOT NULL ENABLE, 
	"AIRCRAFT_ID" VARCHAR2(7 BYTE) NOT NULL ENABLE, 
	"TAIRCRAFT" VARCHAR2(4 BYTE), 
	"FRULES" VARCHAR2(1 BYTE), 
	"TFLIGHT" VARCHAR2(1 BYTE), 
	"NUM" NUMBER(2,0), 
	"WTC" VARCHAR2(1 BYTE), 
	"EQUIPMENT" VARCHAR2(22 BYTE), 
	"ADEP" VARCHAR2(4 BYTE) NOT NULL ENABLE, 
	"TIME" TIMESTAMP (6), 
	"SPEED" VARCHAR2(5 BYTE) NOT NULL ENABLE, 
	"FLEVEL" VARCHAR2(5 BYTE) NOT NULL ENABLE, 
	"ROUTE" VARCHAR2(4000 BYTE), 
	"ADES" VARCHAR2(4 BYTE) NOT NULL ENABLE, 
	"EET" VARCHAR2(5 BYTE), 
	"ALT1" VARCHAR2(4 BYTE), 
	"ALT2" VARCHAR2(4 BYTE), 
	"OTHER" VARCHAR2(4000 BYTE), 
	"TRTIME" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL ENABLE, 
	"EXFPL" CHAR(1 BYTE), 
	"VISIBILITY" NUMBER(1,0), 
	"MESSAGE_ID" NUMBER, 
	"ENTRY_FIR_EET" VARCHAR2(5 BYTE), 
	"OPER" VARCHAR2(7 BYTE), 
	"OPER_TIME" TIMESTAMP (6), 
	"MESSAGE_TEXT" VARCHAR2(4000 BYTE),
	"STATUS" NUMBER(2,0) DEFAULT 0,
	"POD_IN" VARCHAR2(10 BYTE),
	"T_IN" TIMESTAMP (6),
	"H_IN" VARCHAR2(10 BYTE),
	"POD_OUT" VARCHAR2(10 BYTE),
	"T_OUT" TIMESTAMP (6),
	"H_OUT" VARCHAR2(10 BYTE),
	"FPL_ID" VARCHAR2(40 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "FPL_CHANGES_MASTER"."ID" IS 'Identificator';
 
   COMMENT ON COLUMN "FPL_CHANGES_MASTER"."FIR_NAME" IS 'Flight region identificator';
 
   COMMENT ON COLUMN "FPL_CHANGES_MASTER"."AIRCRAFT_ID" IS 'Aircraft identificator';
 
   COMMENT ON COLUMN "FPL_CHANGES_MASTER"."TAIRCRAFT" IS 'Aircraft type';
 
   COMMENT ON COLUMN "FPL_CHANGES_MASTER"."FRULES" IS 'Flight rules';
 
   COMMENT ON COLUMN "FPL_CHANGES_MASTER"."TFLIGHT" IS 'Flight type';
 
   COMMENT ON COLUMN "FPL_CHANGES_MASTER"."NUM" IS 'Number of aircrafts';
 
   COMMENT ON COLUMN "FPL_CHANGES_MASTER"."WTC" IS 'Turbulence category';
 
   COMMENT ON COLUMN "FPL_CHANGES_MASTER"."EQUIPMENT" IS 'Equipment on aircraft';
 
   COMMENT ON COLUMN "FPL_CHANGES_MASTER"."ADEP" IS 'Departure aerodrome';
 
   COMMENT ON COLUMN "FPL_CHANGES_MASTER"."TIME" IS 'Time of flight start';
 
   COMMENT ON COLUMN "FPL_CHANGES_MASTER"."SPEED" IS 'Speed of flight';
 
   COMMENT ON COLUMN "FPL_CHANGES_MASTER"."FLEVEL" IS 'Flight level';
 
   COMMENT ON COLUMN "FPL_CHANGES_MASTER"."ROUTE" IS 'Flight route';
 
   COMMENT ON COLUMN "FPL_CHANGES_MASTER"."ADES" IS 'Destination aerodrome';
 
   COMMENT ON COLUMN "FPL_CHANGES_MASTER"."EET" IS '??? Time of flight end';
 
   COMMENT ON COLUMN "FPL_CHANGES_MASTER"."ALT1" IS 'Alternative destination aerodrome';
 
   COMMENT ON COLUMN "FPL_CHANGES_MASTER"."ALT2" IS 'Another alternative destination aerodrome';
 
   COMMENT ON COLUMN "FPL_CHANGES_MASTER"."OTHER" IS 'Other information';
 
   COMMENT ON COLUMN "FPL_CHANGES_MASTER"."TRTIME" IS 'Time of getting this record by aftnservice';
 
   COMMENT ON COLUMN "FPL_CHANGES_MASTER"."EXFPL" IS 'FPL status (c - cancelled, d - delayed, a -arrived, f - departure,)';
 
   COMMENT ON COLUMN "FPL_CHANGES_MASTER"."VISIBILITY" IS 'Visibility of this fpl (customer asked this field)';
 
   COMMENT ON COLUMN "FPL_CHANGES_MASTER"."MESSAGE_ID" IS 'Message id in arc_aftn';
 
   COMMENT ON COLUMN "FPL_CHANGES_MASTER"."ENTRY_FIR_EET" IS 'EET on entry in fir';
 
   COMMENT ON COLUMN "FPL_CHANGES_MASTER"."OPER" IS 'Type operation';
 
   COMMENT ON COLUMN "FPL_CHANGES_MASTER"."OPER_TIME" IS 'Time operation';
 
   COMMENT ON COLUMN "FPL_CHANGES_MASTER"."MESSAGE_TEXT" IS 'Message text in arc_aftn';
 
   COMMENT ON COLUMN "FPL_CHANGES_MASTER"."STATUS" IS 'The current status of the plan: 0-free, 1-activated, 2-assumed, 3-transferred';
 
   COMMENT ON COLUMN "FPL_CHANGES_MASTER"."POD_IN" IS 'Entry point to the area of responsibility';
 
   COMMENT ON COLUMN "FPL_CHANGES_MASTER"."T_IN" IS 'Time of entry into the area of responsibility';
 
   COMMENT ON COLUMN "FPL_CHANGES_MASTER"."H_IN" IS 'Height of entry into the area of responsibility';
 
   COMMENT ON COLUMN "FPL_CHANGES_MASTER"."POD_OUT" IS 'Exit point from the area of responsibility';
 
   COMMENT ON COLUMN "FPL_CHANGES_MASTER"."T_OUT" IS 'Exit time';
 
   COMMENT ON COLUMN "FPL_CHANGES_MASTER"."H_OUT" IS 'Exit height';
 
   COMMENT ON COLUMN "FPL_CHANGES_MASTER"."FPL_ID" IS 'id in master';
 
   COMMENT ON TABLE "FPL_CHANGES_MASTER"  IS 'Changes in FPL table';
 
 

  CREATE OR REPLACE TRIGGER "FPL_CHANGES_MASTER_TRG" 
      AFTER INSERT OR UPDATE OR DELETE ON FPL FOR EACH ROW
DECLARE
	soper FPL_CHANGES_MASTER.oper%TYPE;
	
BEGIN
	--DELETE
	IF DELETING THEN
		DELETE FROM FPL_CHANGES_MASTER WHERE id = :old.ID;
		INSERT INTO FPL_CHANGES_MASTER
		(
			ID,
			FIR_NAME,
			AIRCRAFT_ID,
			TAIRCRAFT,
			FRULES,
			TFLIGHT,
			NUM,
			WTC,
			EQUIPMENT,
			ADEP,
			TIME,
			SPEED,
			FLEVEL,
			ROUTE,
			ADES,
			EET,
			ALT1,
			ALT2,
			OTHER,
			TRTIME,
			EXFPL,
			VISIBILITY,
			MESSAGE_ID,
			ENTRY_FIR_EET,
			OPER,
			OPER_TIME,
			MESSAGE_TEXT
		)
		VALUES
		(
			:old.ID,
			:old.FIR_NAME,
			:old.AIRCRAFT_ID,
			:old.TAIRCRAFT,
			:old.FRULES,
			:old.TFLIGHT,
			:old.NUM,
			:old.WTC,
			:old.EQUIPMENT,
			:old.ADEP,
			:old.TIME,
			:old.SPEED,
			:old.FLEVEL,
			:old.ROUTE,
			:old.ADES,
			:old.EET,
			:old.ALT1,
			:old.ALT2,
			:old.OTHER,
			:old.TRTIME,
			:old.EXFPL,
			:old.VISIBILITY,
			:old.MESSAGE_ID,
			:old.ENTRY_FIR_EET,
			'D',
			systimestamp,
			( SELECT text FROM ARC_AFTN WHERE id = :old.MESSAGE_ID )
		);
	ELSE
		--INSERT
		IF INSERTING THEN
			soper := 'I';
		--UPDATE
		ELSE
			soper := 'U';
		END IF;
		
		DELETE FROM FPL_CHANGES_MASTER WHERE id = :new.ID;
		INSERT INTO FPL_CHANGES_MASTER
		(
			ID,
			FIR_NAME,
			AIRCRAFT_ID,
			TAIRCRAFT,
			FRULES,
			TFLIGHT,
			NUM,
			WTC,
			EQUIPMENT,
			ADEP,
			TIME,
			SPEED,
			FLEVEL,
			ROUTE,
			ADES,
			EET,
			ALT1,
			ALT2,
			OTHER,
			TRTIME,
			EXFPL,
			VISIBILITY,
			MESSAGE_ID,
			ENTRY_FIR_EET,
			OPER,
			OPER_TIME,
			MESSAGE_TEXT
		)
		VALUES
		(
			:new.ID,
			:new.FIR_NAME,
			:new.AIRCRAFT_ID,
			:new.TAIRCRAFT,
			:new.FRULES,
			:new.TFLIGHT,
			:new.NUM,
			:new.WTC,
			:new.EQUIPMENT,
			:new.ADEP,
			:new.TIME,
			:new.SPEED,
			:new.FLEVEL,
			:new.ROUTE,
			:new.ADES,
			:new.EET,
			:new.ALT1,
			:new.ALT2,
			:new.OTHER,
			:new.TRTIME,
			:new.EXFPL,
			:new.VISIBILITY,
			:new.MESSAGE_ID,
			:new.ENTRY_FIR_EET,
			soper,
			systimestamp,
			( SELECT text FROM ARC_AFTN WHERE id = :new.MESSAGE_ID )
		);
	END IF;
END;
/
ALTER TRIGGER "FPL_CHANGES_MASTER_TRG" ENABLE;
 
  CREATE TABLE "MSG_FROM_FDP" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"FIR_NAME" VARCHAR2(4 BYTE) DEFAULT 'UMMV' NOT NULL ENABLE, 
	"AIRCRAFT_ID" VARCHAR2(7 BYTE) NOT NULL ENABLE, 
	"TAIRCRAFT" VARCHAR2(4 BYTE), 
	"FRULES" VARCHAR2(1 BYTE), 
	"TFLIGHT" VARCHAR2(1 BYTE), 
	"NUM" NUMBER(2,0), 
	"WTC" VARCHAR2(1 BYTE), 
	"EQUIPMENT" VARCHAR2(22 BYTE), 
	"ADEP" VARCHAR2(4 BYTE) NOT NULL ENABLE, 
	"TIME" TIMESTAMP (6), 
	"SPEED" VARCHAR2(5 BYTE) NOT NULL ENABLE, 
	"FLEVEL" VARCHAR2(5 BYTE) NOT NULL ENABLE, 
	"ROUTE" VARCHAR2(4000 BYTE), 
	"ADES" VARCHAR2(4 BYTE) NOT NULL ENABLE, 
	"EET" VARCHAR2(5 BYTE), 
	"ALT1" VARCHAR2(4 BYTE), 
	"ALT2" VARCHAR2(4 BYTE), 
	"OTHER" VARCHAR2(4000 BYTE), 
	"TRTIME" TIMESTAMP (6) DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL ENABLE, 
	"EXFPL" CHAR(1 BYTE), 
	"VISIBILITY" NUMBER(1,0), 
	"MESSAGE_ID" NUMBER, 
	"ENTRY_FIR_EET" VARCHAR2(5 BYTE), 
	"OPER" VARCHAR2(7 BYTE), 
	"OPER_TIME" TIMESTAMP (6), 
	"MESSAGE_TEXT" VARCHAR2(4000 BYTE),
	"STATUS" NUMBER(2,0) DEFAULT 0,
	"POD_IN" VARCHAR2(10 BYTE),
	"T_IN" TIMESTAMP (6),
	"H_IN" VARCHAR2(10 BYTE),
	"POD_OUT" VARCHAR2(10 BYTE),
	"T_OUT" TIMESTAMP (6),
	"H_OUT" VARCHAR2(10 BYTE),
	"FPL_ID" VARCHAR2(40 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
