CREATE TABLE ZONE_MAP_NOTE 
(
  ID NUMBER NOT NULL 
, ZONE_ID NUMBER NOT NULL 
, LATITUDE FLOAT DEFAULT 0 
, LONGITUDE FLOAT DEFAULT 0 
, DESCRIPTION VARCHAR2(2000) 
, CONSTRAINT ZONE_MAP_NOTE_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);
/
ALTER TABLE ZONE_MAP_NOTE
ADD CONSTRAINT ZONE_MAP_NOTE_ZONE_FK1 FOREIGN KEY
(
  ZONE_ID 
)
REFERENCES ZONE
(
  ID 
)
ON DELETE CASCADE ENABLE;
/


CREATE SEQUENCE  ZONE_MAP_NOTE_SEQ  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
 /

CREATE OR REPLACE TRIGGER ZONE_MAP_NOTE_TRG BEFORE INSERT ON ZONE_MAP_NOTE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF :NEW.ID IS NULL THEN
      SELECT ZONE_MAP_NOTE_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER ZONE_MAP_NOTE_TRG ENABLE;
 
