DROP TABLE IF EXISTS `msg_from_tan`;
CREATE TABLE `msg_from_tan` (
  `ID` int(10) unsigned NOT NULL,
  `FIR_NAME` varchar(4) NOT NULL,
  `AIRCRAFT_ID` varchar(7) NOT NULL,
  `TAIRCRAFT` varchar(4) DEFAULT NULL,
  `FRULES` varchar(1) DEFAULT NULL,
  `TFLIGHT` varchar(1) DEFAULT NULL,
  `NUM` int(10) unsigned DEFAULT NULL,
  `WTC` varchar(1) DEFAULT NULL,
  `EQUIPMENT` varchar(22) DEFAULT NULL,
  `ADEP` varchar(4) NOT NULL,
  `TIME` datetime DEFAULT NULL,
  `SPEED` varchar(5) NOT NULL,
  `FLEVEL` varchar(5) NOT NULL,
  `ROUTE` varchar(4000) DEFAULT NULL,
  `ADES` varchar(4) NOT NULL,
  `EET` varchar(5) DEFAULT NULL,
  `ALT1` varchar(4) DEFAULT NULL,
  `ALT2` varchar(4) DEFAULT NULL,
  `OTHER` varchar(4000) DEFAULT NULL,
  `TRTIME` datetime DEFAULT NULL,
  `EXFPL` varchar(1) DEFAULT NULL,
  `VISIBILITY` int(10) unsigned DEFAULT NULL,
  `ENTRY_FIR_EET` varchar(5) DEFAULT NULL,
  `OPER` varchar(7) DEFAULT NULL,
  `OPER_TIME` datetime DEFAULT NULL,
  `MESSAGE_TEXT` varchar(4000) DEFAULT NULL
) DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS `msg_from_fdp`;
CREATE TABLE `msg_from_fdp` (
  `ID` int(10) unsigned NOT NULL,
  `FIR_NAME` varchar(4) NOT NULL,
  `AIRCRAFT_ID` varchar(7) NOT NULL,
  `TAIRCRAFT` varchar(4) DEFAULT NULL,
  `FRULES` varchar(1) DEFAULT NULL,
  `TFLIGHT` varchar(1) DEFAULT NULL,
  `NUM` int(10) unsigned DEFAULT NULL,
  `WTC` varchar(1) DEFAULT NULL,
  `EQUIPMENT` varchar(22) DEFAULT NULL,
  `ADEP` varchar(4) NOT NULL,
  `TIME` datetime DEFAULT NULL,
  `SPEED` varchar(5) NOT NULL,
  `FLEVEL` varchar(5) NOT NULL,
  `ROUTE` varchar(4000) DEFAULT NULL,
  `ADES` varchar(4) NOT NULL,
  `EET` varchar(5) DEFAULT NULL,
  `ALT1` varchar(4) DEFAULT NULL,
  `ALT2` varchar(4) DEFAULT NULL,
  `OTHER` varchar(4000) DEFAULT NULL,
  `TRTIME` datetime DEFAULT NULL,
  `EXFPL` varchar(1) DEFAULT NULL,
  `VISIBILITY` int(10) unsigned DEFAULT NULL,
  `ENTRY_FIR_EET` varchar(5) DEFAULT NULL,
  `OPER` varchar(7) DEFAULT NULL,
  `OPER_TIME` datetime DEFAULT NULL,
  `MESSAGE_TEXT` varchar(4000) DEFAULT NULL,
  `STATUS`	int(10) DEFAULT 0,
  `POD_IN`	varchar(10) DEFAULT NULL,
  `T_IN`	datetime DEFAULT NULL,
  `H_IN`	varchar(10) DEFAULT NULL,
  `POD_OUT`	varchar(10) DEFAULT NULL,
  `T_OUT`	datetime DEFAULT NULL,
  `H_OUT` 	varchar(10) DEFAULT NULL,
  `FPL_ID` 	varchar(40) DEFAULT NULL
) DEFAULT CHARSET=utf8;
